export type Primitive = string | number | boolean | null;
export type QueryValue = Primitive | undefined;
export type Pagination = { current_page:number; last_page:number; total:number; per_page:number };
export type ApiEnvelope<T> = { success?:boolean; data?:T; message?:string; errors?:Record<string,string[]> };
export type AdminList<T> = Pagination & { data:T[] };

/** Canonical PriyasaCore /api/v1 admin contract. Keep every admin UI call behind this map. */
export const API_ROUTES = {
 health:'/health', ready:'/ready',
 auth:{sendOtp:'/admin/auth/send-otp',verifyOtp:'/admin/auth/verify-otp',me:'/admin/me',logout:'/admin/auth/logout'},

 dashboard:'/admin/analytics',
 controlCenter:{overview:'/admin/control-center/overview',orders:'/admin/control-center/orders',inventory:'/admin/control-center/inventory',operations:'/admin/control-center/operations'},
 actions:{orderTransition:(id:string|number)=>`/admin/actions/orders/${id}/transition`,inventoryAdjust:'/admin/actions/inventory/adjust',transfer:'/admin/actions/inventory/transfer',fulfillment:(id:string|number)=>`/admin/actions/fulfillment/allocations/${id}`,return:(id:string|number)=>`/admin/actions/returns/${id}`,refund:(id:string|number)=>`/admin/actions/refunds/${id}`},

 catalog:{products:'/admin/catalog/products',product:(id:string|number)=>`/admin/catalog/products/${id}`,variants:(id:string|number)=>`/admin/catalog/products/${id}/variants`,variant:(p:string|number,v:string|number)=>`/admin/catalog/products/${p}/variants/${v}`,generateVariants:(id:string|number)=>`/admin/catalog/products/${id}/variants/generate`,variantOptions:(p:string|number,v:string|number)=>`/admin/catalog/products/${p}/variants/${v}/attribute-options`,attributes:'/admin/catalog/attributes',attribute:(id:string|number)=>`/admin/catalog/attributes/${id}`,attributeOptions:(id:string|number)=>`/admin/catalog/attributes/${id}/options`,categories:'/admin/catalog/categories',category:(id:string|number)=>`/admin/catalog/categories/${id}`,media:(id:string|number)=>`/admin/catalog/products/${id}/media`,bulkPrice:'/admin/catalog/products/bulk-price'},

 collections:{list:'/admin/collections',detail:(id:string|number)=>`/admin/collections/${id}`},
 orders:{list:'/admin/orders',detail:(id:string|number)=>`/admin/orders/${id}`,status:(id:string|number)=>`/admin/orders/${id}/status`,confirmCod:(id:string|number)=>`/admin/orders/${id}/confirm-cod`,refund:(id:string|number)=>`/admin/orders/${id}/refund`,invoice:(id:string|number)=>`/admin/orders/${id}/invoice`},
 inventory:{list:'/admin/inventory',variant:(id:string|number)=>`/admin/inventory/${id}`,adjust:(id:string|number)=>`/admin/inventory/${id}/adjust`,stock:(id:string|number)=>`/admin/inventory/${id}/stock`,movements:(id:string|number)=>`/admin/inventory/${id}/movements`,bulk:'/admin/inventory/bulk-stock'},
 customers:{list:'/admin/customers',detail:(id:string|number)=>`/admin/customers/${id}`,status:(id:string|number)=>`/admin/customers/${id}/status`},
 promotions:{list:'/admin/promotions',detail:(id:string|number)=>`/admin/promotions/${id}`,toggle:(id:string|number)=>`/admin/promotions/${id}/toggle`,campaigns:'/admin/promotions/campaigns',campaign:(id:string|number)=>`/admin/promotions/campaigns/${id}`,campaignToggle:(id:string|number)=>`/admin/promotions/campaigns/${id}/toggle`},
 reviews:{list:'/admin/reviews',status:(id:string|number)=>`/admin/reviews/${id}/status`},
 returns:{list:'/admin/returns',status:(id:string|number)=>`/admin/returns/${id}/status`},
 shipping:{shipments:'/admin/shipping/shipments',create:(orderId:string|number)=>`/admin/shipping/orders/${orderId}/shipments`,awb:(id:string|number)=>`/admin/shipping/shipments/${id}/awb`,track:(id:string|number)=>`/admin/shipping/shipments/${id}/track`,cancel:(id:string|number)=>`/admin/shipping/shipments/${id}/cancel`},
 cms:{list:'/admin/cms',detail:(id:string|number)=>`/admin/cms/${id}`,reorder:'/admin/cms/reorder',preview:'/admin/cms/preview',drafts:'/admin/cms/drafts',versions:'/admin/cms/versions',publish:(id:string|number)=>`/admin/cms/versions/${id}/publish`,themes:'/admin/cms/themes',theme:(id:string|number)=>`/admin/cms/themes/${id}`,activateTheme:(id:string|number)=>`/admin/cms/themes/${id}/activate`,deactivateTheme:(id:string|number)=>`/admin/cms/themes/${id}/deactivate`},
 merchandising:{products:'/admin/merchandising/products',product:(id:string|number)=>`/admin/merchandising/products/${id}`,reorder:'/admin/merchandising/products/reorder',collectionReorder:(id:string|number)=>`/admin/merchandising/collections/${id}/reorder`},
 settings:'/admin/settings',storefrontConfig:'/admin/storefront-config',
 analytics:{overview:'/admin/analytics/overview',daily:'/admin/analytics/daily',products:'/admin/analytics/products',rebuild:'/admin/analytics/rebuild'},
 audit:'/admin/audit-logs',
 admins:{list:'/admin/admins',roles:'/admin/roles',create:'/admin/admins',detail:(id:string|number)=>`/admin/admins/${id}`,status:(id:string|number)=>`/admin/admins/${id}/status`},
 integrations:{list:'/admin/integrations',woocommerceStatus:'/admin/integrations/woocommerce/status',woocommerceSync:'/admin/integrations/woocommerce/sync',woocommerceProductsSync:'/admin/integrations/woocommerce/sync/products',woocommerceOrdersSync:'/admin/integrations/woocommerce/sync/orders',metaStatus:'/admin/integrations/meta/status',metaConnect:'/admin/integrations/meta/connect',connect:(key:string)=>`/admin/integrations/${key}/connect`,disconnect:(key:string)=>`/admin/integrations/${key}/disconnect`},
 whatsapp:{status:'/admin/whatsapp/status',conversations:'/admin/whatsapp/conversations',conversation:(phone:string)=>`/admin/whatsapp/conversations/${encodeURIComponent(phone)}`,reply:(phone:string)=>`/admin/whatsapp/conversations/${encodeURIComponent(phone)}/reply`,templates:'/admin/whatsapp/templates',templateSync:'/admin/whatsapp/templates/sync',orderAutomations:'/admin/whatsapp/order-automations',orderAutomation:(event:string)=>`/admin/whatsapp/order-automations/${event}`,approvedTemplateSync:'/admin/whatsapp/templates/sync-approved'},
 notifications:{templates:'/admin/notifications/templates',outbox:'/admin/notifications/outbox',test:'/admin/notifications/test'},
 automations:{list:'/admin/automations',detail:(id:string|number)=>`/admin/automations/${id}`,toggle:(id:string|number)=>`/admin/automations/${id}/toggle`},
 marketing:{campaigns:'/admin/marketing/campaigns',campaign:(id:string|number)=>`/admin/marketing/campaigns/${id}`,lifecycle:(id:string|number,action:string)=>`/admin/marketing/campaigns/${id}/${action}`,stats:(id:string|number)=>`/admin/marketing/campaigns/${id}/stats`,events:'/admin/marketing/events',segments:'/admin/marketing/segments',segmentPreview:(id:string|number)=>`/admin/marketing/segments/${id}/preview`,providers:'/admin/marketing/providers'},
 ads:{status:'/admin/ads/status',assets:'/admin/ads/assets',adAccount:'/admin/ads/assets/ad-account',accounts:'/admin/ads/accounts',campaigns:'/admin/ads/campaigns',adsets:'/admin/ads/adsets',creatives:'/admin/ads/creatives',ads:'/admin/ads/ads',audiences:'/admin/ads/audiences',retarget:(id:string|number)=>`/admin/ads/audiences/${id}/retarget`,insights:'/admin/ads/insights',aiGenerate:'/admin/ads/ai/generate'},
 ai:{providers:'/admin/ai/providers',health:'/admin/ai/health',provider:(id:string)=>`/admin/ai/providers/${id}`,generate:'/admin/ai/generate',productGenerate:(id:string|number)=>`/admin/ai/products/${id}/generate`,productApply:(id:string|number)=>`/admin/ai/products/${id}/apply`},
 events:{list:'/admin/events',detail:(id:string|number)=>`/admin/events/${id}`},
 ops:{metrics:'/admin/ops/metrics',audit:'/admin/ops/audit'},security:{me:'/admin/security/me',roles:'/admin/security/roles',permissions:'/admin/security/permissions',users:'/admin/security/users',audit:'/admin/security/audit',assignRole:(user:string|number,role:string|number)=>`/admin/security/users/${user}/roles/${role}`,revokeRole:(user:string|number,role:string|number)=>`/admin/security/users/${user}/roles/${role}`},
 fulfillment:{order:(id:string|number)=>`/admin/fulfillment/orders/${id}`,allocate:(id:string|number)=>`/admin/fulfillment/orders/${id}/allocate`,pick:(id:string|number)=>`/admin/fulfillment/allocations/${id}/pick`,pack:(id:string|number)=>`/admin/fulfillment/allocations/${id}/pack`,shipments:(id:string|number)=>`/admin/fulfillment/orders/${id}/shipments`},warehouses:{list:'/admin/warehouses',inventory:'/admin/warehouse-inventory',adjust:'/admin/warehouse-inventory/adjust'},support:{tickets:'/admin/support/tickets',ticket:(id:string|number)=>`/admin/support/tickets/${id}`,reply:(id:string|number)=>`/admin/support/tickets/${id}/reply`},events:{list:'/admin/events',detail:(id:string|number)=>`/admin/events/${id}`},search:{rebuildRelations:'/admin/search/rebuild-relations'},
} as const;
export const DEVICE_API_ROOT = '/api/device';
