'use client';
import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,Download,FileUp,RefreshCw,Save} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Paginated,Product} from '@/lib/types';
import {Badge,Button,Card,ErrorState,Loading,PageHeader} from '@/components/ui';

type ImportRow={id:string;name:string;slug:string;sku:string;price:string;mrp:string;status:string;category_id:string;image_url:string;description:string;short_description:string};
const headers=['id','name','slug','sku','price','mrp','status','category_id','image_url','description','short_description'];
function csvCell(v:unknown){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function toCsv(rows:ImportRow[]){return [headers.join(','),...rows.map(r=>headers.map(h=>csvCell((r as any)[h])).join(','))].join('\n')}
function parseCsv(text:string){const out:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')quoted=false;else cell+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell);out.push(row);row=[];cell='';}else if(ch!=='\r')cell+=ch}row.push(cell);if(row.length>1||row[0])out.push(row);return out}
function download(name:string,text:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export default function CatalogTools(){
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[rows,setRows]=useState<ImportRow[]>([]),[mode,setMode]=useState<'products'|'variants'>('products');
 async function load(){setLoading(true);setError('');try{const r=await api<Paginated<Product>>('/admin/catalog/products?per_page=100');setProducts(r.data?.data||[])}catch(e){setError(apiMessage(e,'Unable to load catalog'))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const exportRows=useMemo(()=>products.map(p=>({id:String(p.id),name:p.name,slug:p.slug,sku:p.sku||'',price:String(p.price??''),mrp:String(p.mrp??''),status:p.status,category_id:String(p.category?.id??''),image_url:String((p as any).image_url||''),description:String((p as any).description||''),short_description:String((p as any).short_description||'')})),[products]);
 function exportCatalog(){download(`priyasa-products-${new Date().toISOString().slice(0,10)}.csv`,toCsv(exportRows))}
 function onImport(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=parseCsv(String(reader.result||''));if(!data.length)throw new Error('CSV is empty.');const map=data[0].map(x=>x.trim().toLowerCase());const required=['id','name','slug','price'];for(const h of required)if(!map.includes(h))throw new Error(`CSV must include '${h}' column.`);const parsed=data.slice(1).filter(r=>r.some(Boolean)).map((r,i)=>{const o:any={};map.forEach((h,n)=>o[h]=r[n]??'');return {...o,id:String(o.id||''),name:String(o.name||''),slug:String(o.slug||''),sku:String(o.sku||''),price:String(o.price||''),mrp:String(o.mrp||''),status:String(o.status||'draft'),category_id:String(o.category_id||''),image_url:String(o.image_url||''),description:String(o.description||''),short_description:String(o.short_description||'') } as ImportRow});if(parsed.some(r=>!r.id||!r.name||!r.slug||!Number.isFinite(Number(r.price))))throw new Error('Every imported row needs id, name, slug and a numeric price.');setRows(parsed);setMessage(`${parsed.length} product rows loaded for review.`)}catch(err){setError(err instanceof Error?err.message:'Invalid CSV')}finally{e.target.value=''}};reader.readAsText(file)}
 async function applyImport(){if(!rows.length)return;setBusy(true);setError('');setMessage('');let done=0;try{for(const r of rows){await api(`/admin/catalog/products/${encodeURIComponent(r.id)}`,{method:'PUT',body:JSON.stringify({name:r.name,slug:r.slug,sku:r.sku||null,price:Number(r.price),mrp:r.mrp===''?null:Number(r.mrp),status:r.status,category_id:r.category_id||null,image_url:r.image_url||null,description:r.description,short_description:r.short_description})});done++}setRows([]);setMessage(`${done} products imported successfully.`);await load()}catch(e){setError(apiMessage(e,`Import stopped after ${done} products.`))}finally{setBusy(false)}}
 return <section className="content"><div className="form-actions" style={{justifyContent:'flex-start',marginBottom:10}}><Link href="/products"><Button><ArrowLeft size={14}/> Products</Button></Link></div><PageHeader title="Catalog Import / Export" description="Move catalog data safely with a review-first CSV workflow. Writes go directly to PriyasaCore." action={<Button onClick={load}><RefreshCw size={14}/> Refresh</Button>}/>{error&&<ErrorState error={error} onRetry={load}/>} {message&&<div className="status green" style={{marginBottom:14}}>{message}</div>}
 <div className="section-grid"><Card><div className="section-head"><div><h2>Export catalog</h2><p>Download the currently loaded product records, edit them in Excel/Sheets, then import the reviewed file.</p></div><Badge>{products.length} loaded</Badge></div>{loading?<Loading/>:<div className="form-actions"><Button className="primary" disabled={!products.length} onClick={exportCatalog}><Download size={15}/> Download product CSV</Button></div>}</Card><Card><div className="section-head"><div><h2>Import products</h2><p>Only existing product IDs are updated. No implicit product creation or deletion is performed.</p></div></div><label>CSV file<input type="file" accept=".csv,text/csv" onChange={onImport}/><span className="muted">Required columns: id, name, slug, price. Optional: sku, mrp, status, category_id, image_url, description, short_description.</span></label></Card></div>
 <div style={{marginTop:15}}><Card><div className="section-head"><div><h2>Review import</h2><p>Nothing is written until you explicitly apply the reviewed rows.</p></div><Badge>{rows.length} pending</Badge></div>{!rows.length?<div className="empty"><strong>No import pending</strong><span>Choose a CSV file above. The parser validates the required columns before showing rows.</span></div>:<><div className="table-wrap"><table className="table"><thead><tr><th>ID</th><th>Product</th><th>SKU</th><th>Price</th><th>MRP</th><th>Status</th><th>Category</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.id}><td><code>{r.id}</code></td><td><b>{r.name}</b><div className="muted">{r.slug}</div></td><td>{r.sku||'—'}</td><td>₹ {Number(r.price).toLocaleString('en-IN')}</td><td>{r.mrp||'—'}</td><td><Badge>{r.status}</Badge></td><td>{r.category_id||'—'}</td></tr>)}</tbody></table></div>{rows.length>100&&<p className="muted">Showing first 100 rows; all {rows.length} validated rows will be applied.</p>}<div className="form-actions" style={{marginTop:14,justifyContent:'flex-end'}}><Button onClick={()=>setRows([])}>Discard</Button><Button className="primary" disabled={busy} onClick={applyImport}><Save size={14}/>{busy?'Applying…':`Apply ${rows.length} updates`}</Button></div></>}</Card></div>
 <Card className="notice" style={{marginTop:15}}><b>Safety model</b><span>CSV import is deliberately update-only: it cannot create products, archive products, alter variants, or change inventory. Use Variant Matrix for SKU-level variant work.</span></Card>
 </section>
}
