'use client';

import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {apiMessage,dateTime} from '@/lib/format';
import {API_ROUTES} from '@/lib/api-contract';
import {Card,PageHeader,DataToolbar,Modal,Button,Badge,Loading,ErrorState,Empty} from '@/components/ui';

type Ticket={id:number|string;subject?:string;title?:string;status?:string;priority?:string;assigned_to?:string|null;customer?:{name?:string;phone?:string};phone?:string;created_at?:string;messages?:Array<{id?:number|string;message?:string;created_at?:string;sender?:string}>};
type List={data:Ticket[];current_page:number;last_page:number;total:number};

export default function Support(){
 const [list,setList]=useState<List|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState('');
 const [detail,setDetail]=useState<Ticket|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setError('');try{const p=new URLSearchParams({per_page:'50'});if(q)p.set('search',q);if(status)p.set('status',status);const r=await api<List>(API_ROUTES.support.tickets+'?'+p);setList(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load support tickets'))}}
 async function open(id:Ticket['id']){try{const r=await api<Ticket>(API_ROUTES.support.ticket(id));setDetail(r.data||null);setMessage('')}catch(e){setError(apiMessage(e,'Unable to load ticket'))}}
 async function update(patch:Record<string,unknown>){if(!detail)return;setBusy(true);setError('');try{await api(API_ROUTES.support.update(detail.id),{method:'PUT',body:JSON.stringify(patch)});await open(detail.id);await load()}catch(e){setError(apiMessage(e,'Unable to update ticket'))}finally{setBusy(false)}}
 async function reply(){if(!detail||!message.trim())return;setBusy(true);setError('');try{await api(API_ROUTES.support.reply(detail.id),{method:'POST',body:JSON.stringify({message:message.trim()})});setMessage('');await open(detail.id)}catch(e){setError(apiMessage(e,'Unable to send reply'))}finally{setBusy(false)}}
 useEffect(()=>{load()},[status]);useEffect(()=>{const t=setTimeout(load,300);return()=>clearTimeout(t)},[q]);
 return <section className="content"><PageHeader title="Support Command Center" description="Customer service queue with assignment, priority, status and conversation controls." action={<Button onClick={load}>Refresh</Button>}/>{error&&<ErrorState error={error} onRetry={load}/>}
 <Card><DataToolbar value={q} onChange={setQ} placeholder="Search ticket, customer or phone…"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['open','pending','in_progress','resolved','closed'].map(x=><option key={x}>{x}</option>)}</select></DataToolbar>
 {!list&&!error?<Loading/>:list?.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Ticket</th><th>Customer</th><th>Priority</th><th>Status</th><th>Created</th><th/></tr></thead><tbody>{list.data.map(t=><tr key={String(t.id)}><td><b>#{t.id}</b><div className="muted">{t.subject||t.title||'Support request'}</div></td><td>{t.customer?.name||t.customer?.phone||t.phone||'—'}</td><td><Badge>{t.priority||'normal'}</Badge></td><td><Badge>{t.status||'open'}</Badge></td><td>{dateTime(t.created_at)}</td><td><Button onClick={()=>open(t.id)}>Open</Button></td></tr>)}</tbody></table></div>:<Empty title="No support tickets" text="The support queue is empty for the selected filters."/>}</Card>
 {detail&&<Modal title={'Ticket #'+detail.id} onClose={()=>setDetail(null)}><div className="detail-stack"><Card><div className="card-title">{detail.subject||detail.title||'Support request'}</div><p className="muted">{detail.customer?.name||'Customer'} · {detail.customer?.phone||detail.phone||'—'}</p><div className="form-grid"><label>Status<select value={detail.status||'open'} disabled={busy} onChange={e=>update({status:e.target.value})}>{['open','pending','in_progress','resolved','closed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={detail.priority||'normal'} disabled={busy} onChange={e=>update({priority:e.target.value})}>{['low','normal','high','urgent'].map(x=><option key={x}>{x}</option>)}</select></label><label>Assigned to<input value={detail.assigned_to||''} disabled={busy} placeholder="Operator ID/email" onChange={e=>setDetail({...detail,assigned_to:e.target.value})}/></label><Button disabled={busy} onClick={()=>update({assigned_to:detail.assigned_to||null})}>Save assignment</Button></div></Card>
 <Card><div className="card-title">Conversation</div>{detail.messages?.length?<div className="quick">{detail.messages.map((m,i)=><div key={String(m.id??i)}><b>{m.sender||'Message'}</b><span>{m.message||'—'} · {dateTime(m.created_at)}</span></div>)}</div>:<div className="empty">No messages returned.</div>}<textarea className="wide-control note" rows={4} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Reply to customer…"/><div className="form-actions"><Button className="primary" disabled={busy||!message.trim()} onClick={reply}>{busy?'Sending…':'Send reply'}</Button></div></Card></div></Modal>}
 </section>
}