'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';import {money,dateTime,titleCase,apiMessage} from '@/lib/format';
import {PageHeader,Card,DataToolbar,Pagination,Modal,Button,Badge,Loading,ErrorState,Empty} from '@/components/ui';

type Shipment={id:number|string;order_id?:number|string;order_number?:string;status:string;provider?:string|null;awb?:string|null;tracking_number?:string|null;courier?:string|null;shipping_cost?:number|string;created_at?:string;updated_at?:string};
type List={data:Shipment[];current_page:number;last_page:number;total:number;per_page:number};
const statuses=['','pending','ready','shipped','in_transit','delivered','cancelled','failed'];
const terminal=new Set(['cancelled','delivered']);
export default function Shipping(){const [list,setList]=useState<List|null>(null);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [detail,setDetail]=useState<Shipment|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [action,setAction]=useState('');
async function load(){setError('');try{const p=new URLSearchParams({page:String(page),per_page:'50'});if(q)p.set('search',q);if(status)p.set('status',status);const r=await api<List>(`/admin/shipping/shipments?${p}`);setList(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load shipments'))}}
useEffect(()=>{load()},[page,status]);useEffect(()=>{const t=setTimeout(()=>{setPage(1);load()},350);return()=>clearTimeout(t)},[q]);
async function perform(){if(!detail||!action)return;setBusy(true);setError('');try{if(action==='track'){const r=await api<Shipment>(`/admin/shipments/${detail.id}`);setDetail(r.data||detail)}else if(action==='cancel'){await api(`/admin/shipments/${detail.id}/cancel`,{method:'POST'});setDetail(null);await load()}else if(action==='create'&&detail.order_id){const r=await api<Shipment>(`/admin/orders/${detail.order_id}/shipment`,{method:'POST',body:JSON.stringify({provider:detail.provider||'shiprocket'})});setDetail(r.data||detail);await load()} }catch(e){setError(apiMessage(e,'Shipping operation failed'))}finally{setBusy(false);setAction('')}}
return <section className="content"><PageHeader title="Shipping" description="Create shipments, track parcels and control fulfilment from the Core shipping service."/><Card><DataToolbar value={q} onChange={v=>{setPage(1);setQ(v)}} placeholder="Search order, AWB, tracking…"><select className="filter-select" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}>{statuses.map(s=><option key={s} value={s}>{s?titleCase(s):'All statuses'}</option>)}</select></DataToolbar>{error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:list?.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Order</th><th>Provider</th><th>AWB</th><th>Courier</th><th>Tracking</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{list.data.map(s=><tr key={String(s.id)}><td><b>#{s.order_number||s.order_id||'—'}</b></td><td>{s.provider||'—'}</td><td>{s.awb||'—'}</td><td>{s.courier||'—'}</td><td>{s.tracking_number||'—'}</td><td><Badge>{titleCase(s.status)}</Badge></td><td>{dateTime(s.updated_at||s.created_at)}</td><td><Button onClick={()=>setDetail(s)}>Manage</Button></td></tr>)}</tbody></table></div>:<Empty title="No shipments" text="Shipments will appear here after an order is prepared for fulfilment."/>}<Pagination page={list?.current_page||1} lastPage={list?.last_page||1} onChange={setPage}/></Card>{detail&&<Modal title={`Shipment #${detail.id}`} onClose={()=>setDetail(null)}><div className="detail-stack"><div className="form-grid"><Card><div className="metric-label">Order</div><b>#{detail.order_number||detail.order_id||'—'}</b></Card><Card><div className="metric-label">Shipping cost</div><b>{money(detail.shipping_cost)}</b></Card></div><div className="card"><div className="card-title">Shipment</div><p className="muted">Provider: {detail.provider||'—'} · Courier: {detail.courier||'—'}</p><p className="muted">AWB: {detail.awb||'Not assigned'} · Tracking: {detail.tracking_number||'Not available'}</p><div className="form-actions"><Button disabled={busy} onClick={()=>setAction('track')}>Refresh tracking</Button>{!terminal.has(detail.status)&&<Button disabled={busy} onClick={()=>setAction('cancel')}>Cancel shipment</Button>}</div>{action&&<div className="form-actions"><span className="muted">Confirm {action.replace('_',' ')}?</span><Button onClick={()=>setAction('')} disabled={busy}>No</Button><Button className="primary" onClick={perform} disabled={busy}>{busy?'Working…':'Confirm'}</Button></div>}</div></div></Modal>}</section>}
