'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Card,PageHeader,DataToolbar,Button,Modal,Loading,ErrorState,Badge} from '@/components/ui';

type Row=any;
function quantity(row:Row){return Number(row.quantity??row.stock??row.inventory?.quantity??0)}
function reserved(row:Row){return Number(row.reserved??row.reserved_quantity??row.inventory?.reserved??row.inventory?.reserved_quantity??0)}
function available(row:Row){const explicit=row.available??row.inventory?.available;return explicit==null?quantity(row)-reserved(row):Number(explicit)}
function threshold(row:Row){return Number(row.low_stock_threshold??row.inventory?.low_stock_threshold??3)}
function sku(row:Row){return row.variant?.sku??row.sku??'—'}
function variantName(row:Row){return row.variant?.name??row.variant?.product?.name??row.name??row.variant_name??'—'}
export default function Inventory(){
 const [rows,setRows]=useState<Row[]>([]);const [q,setQ]=useState('');const [filter,setFilter]=useState<'all'|'low'|'out'>('all');
 const [selected,setSelected]=useState<Row|null>(null);const [qty,setQty]=useState('');const [reason,setReason]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);
 async function load(){setError('');setLoading(true);try{const r=await api<any>('/admin/inventory');const d=r.data;setRows(Array.isArray(d)?d:d?.data||d?.items||[])}catch(e){setError(apiMessage(e,'Unable to load inventory'))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{let low=0,out=0,total=0,availableTotal=0;for(const r of rows){const a=available(r);total+=quantity(r);availableTotal+=a;if(a<=0)out++;else if(a<=threshold(r))low++}return{skus:rows.length,total,available:availableTotal,low,out}},[rows]);
 const filtered=useMemo(()=>rows.filter(v=>{const text=JSON.stringify(v).toLowerCase();if(q.trim()&&!text.includes(q.trim().toLowerCase()))return false;const a=available(v);if(filter==='out')return a<=0;if(filter==='low')return a>0&&a<=threshold(v);return true}),[rows,q,filter]);
 const variantId=selected?.variant?.id??selected?.variant_id??selected?.id;
 async function adjust(){if(!selected||!variantId)return;setBusy(true);setError('');try{const delta=Number(qty);if(!Number.isInteger(delta)||delta===0)throw new Error('Enter a non-zero whole-number adjustment.');await api(`/admin/inventory/${variantId}/adjust`,{method:'POST',body:JSON.stringify({delta,reason:reason.trim()||'Admin adjustment'})});setSelected(null);setQty('');setReason('');await load()}catch(e){setError(apiMessage(e,'Inventory adjustment failed'))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Inventory" description="Monitor SKU-level availability, identify stock risk and make controlled adjustments."/>
  {error&&<ErrorState error={error} onRetry={load}/>}<div className="stats-grid"><Card><span>SKUs</span><strong>{stats.skus}</strong></Card><Card><span>Units on hand</span><strong>{stats.total}</strong></Card><Card><span>Available</span><strong>{stats.available}</strong></Card><Card><span>Low / out</span><strong>{stats.low} / {stats.out}</strong></Card></div>
  <Card><DataToolbar value={q} onChange={setQ} placeholder="Search SKU, product, variant…"><select className="filter-select" value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">All stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select><Button onClick={load}>Refresh</Button></DataToolbar>
   {loading?<Loading/>:filtered.length?<div className="table-wrap"><table className="table"><thead><tr><th>Variant</th><th>SKU</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Threshold</th><th>Health</th><th/></tr></thead><tbody>{filtered.map((v:Row,i:number)=>{const a=available(v);const t=threshold(v);const health=a<=0?'out':a<=t?'low':'healthy';return <tr key={String(v.id??v.variant_id??i)}><td><b>{variantName(v)}</b>{v.variant?.product?.name&&<div style={{color:'#999',marginTop:3}}>{v.variant.product.name}</div>}</td><td>{sku(v)}</td><td>{quantity(v)}</td><td>{reserved(v)}</td><td><b>{a}</b></td><td>{t}</td><td><Badge>{health}</Badge></td><td><Button onClick={()=>{setSelected(v);setQty('');setReason('')}}>Adjust</Button></td></tr>})}</tbody></table></div>:<div className="empty"><strong>No inventory records</strong><span>{rows.length?'No records match the current filters.':'Inventory records will appear after sellable variants are created.'}</span></div>}
  </Card>{selected&&<Modal title="Adjust inventory" onClose={()=>setSelected(null)}><form className="form" onSubmit={e=>{e.preventDefault();adjust()}}><div style={{fontSize:12,color:'#777'}}>Variant: <b>{variantName(selected)}</b> · SKU <b>{sku(selected)}</b></div><div className="form-grid"><Card><span>On hand</span><strong>{quantity(selected)}</strong></Card><Card><span>Available</span><strong>{available(selected)}</strong></Card></div><label>Quantity change<input autoFocus type="number" step="1" required value={qty} onChange={e=>setQty(e.target.value)} placeholder="e.g. 10 or -2"/><span className="muted">Use a positive number for received stock and a negative number for shrinkage, damage or corrections.</span></label><label>Reason<textarea required value={reason} onChange={e=>setReason(e.target.value)} placeholder="Stock receipt, damaged item, cycle count…"/></label><div className="form-actions"><Button type="button" onClick={()=>setSelected(null)}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Saving…':'Apply adjustment'}</Button></div></form></Modal>}
 </section>
}