'use client';

import {useEffect,useMemo,useState} from 'react';
import {BarChart3,Bell,ChevronRight,Clock3,Mail,MessageCircle,Pause,Play,Plus,RefreshCw,Send,Smartphone,Target,Users,XCircle} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage,dateTime} from '@/lib/format';
import {Badge,Button,Card,DataToolbar,Empty,ErrorState,Loading,Modal,PageHeader} from '@/components/ui';

type Channel='push'|'email'|'whatsapp'|'rcs';
type Promotion={id:number|string;code:string;type:string;value:number|string;is_active:boolean;usage_count:number;usage_limit?:number|null;starts_at?:string|null;ends_at?:string|null};
type Automation={id:number|string;name:string;event_key:string;enabled:boolean;email_enabled:boolean;whatsapp_enabled:boolean;fcm_enabled:boolean;delay_seconds?:number;updated_at?:string};
type Campaign={campaign_id:string;name:string;status:string;audience:any;channels:any[];schedule:any;frequency_cap:any;quiet_hours:any;goal:any;created_at?:string;updated_at?:string};
type Segment={segment_id:string;name:string;is_active:boolean;logic:string;rules:any[]};
type Provider={channel:string;status:string;latency_ms:number|null};
type Stats={queued:number;sent:number;delivered:number;opened:number;clicked:number;failed:number;converted:number;unsubscribed:number};
type CampaignDraft={name:string;channel:Channel;segmentId:string;templateKey:string;sendAt:string;frequencyCap:string;quietStart:string;quietEnd:string;goalType:'order'|'revenue'|'click';goalWindow:string};
const channelMeta:{key:Channel;label:string;icon:typeof Send;description:string}[]=[
 {key:'push',label:'FCM Push',icon:Bell,description:'App and web push notifications'},
 {key:'email',label:'Email',icon:Mail,description:'Promotional email campaigns'},
 {key:'whatsapp',label:'WhatsApp',icon:MessageCircle,description:'Approved template messaging'},
 {key:'rcs',label:'RCS',icon:Smartphone,description:'Rich business messaging'},
];
const emptyDraft:CampaignDraft={name:'',channel:'push',segmentId:'',templateKey:'',sendAt:'',frequencyCap:'3',quietStart:'22:00',quietEnd:'08:00',goalType:'order',goalWindow:'72'};
const idempotency=()=>crypto.randomUUID();

export default function Marketing(){
 const[tab,setTab]=useState<'overview'|'campaigns'|'automation'|'promotions'>('overview');
 const[promotions,setPromotions]=useState<Promotion[]>([]);const[automations,setAutomations]=useState<Automation[]>([]);const[campaigns,setCampaigns]=useState<Campaign[]>([]);const[segments,setSegments]=useState<Segment[]>([]);const[providers,setProviders]=useState<Provider[]>([]);
 const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[message,setMessage]=useState('');const[composer,setComposer]=useState(false);const[draft,setDraft]=useState<CampaignDraft>(emptyDraft);const[busy,setBusy]=useState(false);const[q,setQ]=useState('');const[selected,setSelected]=useState<Campaign|null>(null);const[stats,setStats]=useState<Stats|null>(null);
 async function load(){setLoading(true);setError('');try{const[p,a,c,s,pr]=await Promise.all([api<any>('/admin/promotions?per_page=100'),api<any>('/admin/automations?per_page=100'),api<any>('/admin/marketing/campaigns?per_page=100'),api<any>('/admin/marketing/segments?per_page=100'),api<any>('/admin/marketing/providers')]);setPromotions(p.data?.data||[]);setAutomations(a.data?.data||[]);setCampaigns(c.data?.data||[]);setSegments(s.data?.data||[]);setProviders(pr.data||[])}catch(e){setError(apiMessage(e,'Unable to load Priyasa marketing command center.'))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const activePromotions=promotions.filter(p=>p.is_active).length;const activeAutomations=automations.filter(a=>a.enabled).length;const activeCampaigns=campaigns.filter(c=>['scheduled','running'].includes(c.status)).length;const enabledChannels=useMemo(()=>({push:providers.find(p=>p.channel==='push')?.status==='configured',email:providers.find(p=>p.channel==='email')?.status==='configured',whatsapp:providers.find(p=>p.channel==='whatsapp')?.status==='configured',rcs:providers.find(p=>p.channel==='rcs')?.status==='configured'}),[providers]);
 const filteredCampaigns=campaigns.filter(c=>!q||`${c.name} ${c.status} ${c.campaign_id}`.toLowerCase().includes(q.toLowerCase()));const filteredPromotions=promotions.filter(p=>!q||p.code.toLowerCase().includes(q.toLowerCase()));
 function startCreate(){setDraft(emptyDraft);setError('');setMessage('');setComposer(true)}
 async function createCampaign(){if(!draft.name.trim()){setError('Campaign name is required.');return}if(!draft.templateKey.trim()){setError('Template key is required. Configure a real provider template before scheduling.');return}setBusy(true);setError('');setMessage('');try{const channelPayload={channel:draft.channel,template_key:draft.templateKey.trim(),fallback_after_seconds:0};const payload:any={name:draft.name.trim(),status:'draft',audience:{filters:{}} ,channels:[channelPayload],frequency_cap:{per_customer_per_24h:Math.min(20,Math.max(1,Number(draft.frequencyCap)||3))},quiet_hours:{start:draft.quietStart||undefined,end:draft.quietEnd||undefined},goal:{type:draft.goalType,window_hours:Math.min(720,Math.max(1,Number(draft.goalWindow)||72))}};if(draft.segmentId)payload.audience={segment_id:draft.segmentId,filters:{}};const r=await api<any>('/admin/marketing/campaigns',{method:'POST',headers:{'Idempotency-Key':idempotency(),'Content-Type':'application/json'},body:JSON.stringify(payload)});const created=r.data as Campaign;setComposer(false);setDraft(emptyDraft);setTab('campaigns');setMessage('Campaign saved as draft. No customer message was sent.');if(draft.sendAt){await scheduleCampaign(created,draft.sendAt)}else await load()}catch(e){setError(apiMessage(e,'Campaign API rejected this draft. No message was sent.'))}finally{setBusy(false)}}
 async function scheduleCampaign(c:Campaign,sendAt:string){const iso=new Date(sendAt).toISOString();await api(`/admin/marketing/campaigns/${encodeURIComponent(c.campaign_id)}/schedule`,{method:'POST',headers:{'Idempotency-Key':idempotency(),'Content-Type':'application/json'},body:JSON.stringify({send_at:iso,timezone:'Asia/Kolkata'})});setMessage('Campaign scheduled in PriyasaCore.');await load()}
 async function lifecycle(c:Campaign,action:'pause'|'resume'|'cancel'){setBusy(true);setError('');try{await api(`/admin/marketing/campaigns/${encodeURIComponent(c.campaign_id)}/${action}`,{method:'POST',headers:{'Idempotency-Key':idempotency(),'Content-Type':'application/json'},body:'{}'});setMessage(`Campaign ${action} action completed.`);await load();if(selected?.campaign_id===c.campaign_id)setSelected(null)}catch(e){setError(apiMessage(e,`Unable to ${action} campaign.`))}finally{setBusy(false)}}
 async function showStats(c:Campaign){setBusy(true);setError('');try{const r=await api<any>(`/admin/marketing/campaigns/${encodeURIComponent(c.campaign_id)}/stats`);setSelected(c);setStats(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load campaign performance.'))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Marketing & Promotions" description="Native Priyasa Store growth control: campaigns, audiences, promotions, providers and measurable customer outcomes." action={<div style={{display:'flex',gap:8}}><Button onClick={load} disabled={loading||busy}><RefreshCw size={15}/> Refresh</Button><Button className="primary" onClick={startCreate}><Plus size={15}/> Create campaign</Button></div>}/>{error&&<ErrorState error={error} onRetry={load}/>} {message&&<div className="form-success" role="status">{message}</div>}
 {loading?<Loading/>:<><div className="stats-grid"><Card><div className="metric-label">Active campaigns</div><div className="metric">{activeCampaigns}</div><div className="muted">Scheduled + running in Core</div></Card><Card><div className="metric-label">Active automations</div><div className="metric">{activeAutomations}</div><div className="muted">Event-driven customer journeys</div></Card><Card><div className="metric-label">Live promotions</div><div className="metric">{activePromotions}</div><div className="muted">Native Priyasa checkout offers</div></Card><Card><div className="metric-label">Saved audiences</div><div className="metric">{segments.filter(s=>s.is_active).length}</div><div className="muted">Reusable customer segments</div></Card></div>
 <Card><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}>{[['overview','Overview'],['campaigns','Campaigns'],['automation','Automation'],['promotions','Promotions']].map(([k,l])=><Button key={k} className={tab===k?'primary':''} onClick={()=>setTab(k as typeof tab)}>{l}</Button>)}</div>
 {tab==='overview'&&<><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}>{channelMeta.map(({key,label,icon:Icon,description})=><div key={key} style={{padding:18,border:'1px solid var(--border,#e6e6e6)',borderRadius:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Icon size={21}/><Badge>{enabledChannels[key]?'Ready':'Not configured'}</Badge></div><h3 style={{margin:'14px 0 5px'}}>{label}</h3><p className="muted" style={{margin:0}}>{description}</p></div>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:12,marginTop:16}}>{[['Customer audiences','Create reusable segments from real Priyasa customer data.','/marketing/segments'],['Order notifications','Control lifecycle status messages separately from marketing campaigns.','/notifications/order-status'],['Promotion engine','Manage checkout discounts without WooCommerce dependency.','/promotions'],['Attribution','Campaign events expose delivery, engagement and conversion metrics.','/analytics']].map(([title,text,href])=><button key={title} onClick={()=>window.location.assign(href)} style={{textAlign:'left',padding:18,border:'1px solid var(--border,#e6e6e6)',borderRadius:16,background:'transparent',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>{title}</strong><ChevronRight size={17}/></div><p className="muted" style={{margin:'8px 0 14px'}}>{text}</p><span className="muted">Open workspace</span></button>)}</div></>}
 {tab==='campaigns'&&<><DataToolbar value={q} onChange={setQ} placeholder="Search campaign…"/><div className="table-wrap"><table className="table"><thead><tr><th>Campaign</th><th>Channel</th><th>Audience</th><th>Status</th><th>Schedule</th><th>Actions</th></tr></thead><tbody>{filteredCampaigns.map(c=><tr key={c.campaign_id}><td><b>{c.name}</b><div className="muted"><code>{c.campaign_id}</code></div></td><td>{(c.channels||[]).map((x:any)=>x.channel).join(' · ')||'—'}</td><td>{c.audience?.segment_id||'All customers'}</td><td><Badge>{c.status}</Badge></td><td>{dateTime(c.schedule?.send_at||c.updated_at)}</td><td><div className="form-actions">{c.status==='scheduled'||c.status==='running'?<Button onClick={()=>lifecycle(c,'pause')} disabled={busy}><Pause size={13}/> Pause</Button>:c.status==='paused'?<Button onClick={()=>lifecycle(c,'resume')} disabled={busy}><Play size={13}/> Resume</Button>:null}{['draft','scheduled','paused','running'].includes(c.status)&&<Button onClick={()=>lifecycle(c,'cancel')} disabled={busy}><XCircle size={13}/> Cancel</Button>}<Button onClick={()=>showStats(c)} disabled={busy}><BarChart3 size={13}/> Stats</Button></div></td></tr>)}</tbody></table></div>{!filteredCampaigns.length&&<Empty title="No campaigns" text="Create a native PriyasaCore campaign draft; scheduling is a separate explicit action."/>}</>}
 {tab==='automation'&&<><DataToolbar value={q} onChange={setQ} placeholder="Search automation or event…"/><div className="table-wrap"><table className="table"><thead><tr><th>Journey</th><th>Trigger</th><th>Channels</th><th>Delay</th><th>Status</th><th>Updated</th></tr></thead><tbody>{automations.filter(a=>!q||`${a.name} ${a.event_key}`.toLowerCase().includes(q.toLowerCase())).map(a=><tr key={String(a.id)}><td><b>{a.name}</b></td><td><code>{a.event_key}</code></td><td>{[a.fcm_enabled&&'FCM',a.email_enabled&&'Email',a.whatsapp_enabled&&'WhatsApp'].filter(Boolean).join(' · ')||'None'}</td><td>{a.delay_seconds?`${Math.round(a.delay_seconds/60)} min`:'Immediate'}</td><td><Badge>{a.enabled?'Enabled':'Paused'}</Badge></td><td>{dateTime(a.updated_at)}</td></tr>)}</tbody></table></div>{!automations.length&&<Empty title="No automation rules" text="Configure lifecycle automation in the dedicated Automation workspace."/>}</>}
 {tab==='promotions'&&<><DataToolbar value={q} onChange={setQ} placeholder="Search promotion code…"/><div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Offer</th><th>Usage</th><th>Validity</th><th>Status</th></tr></thead><tbody>{filteredPromotions.map(p=><tr key={String(p.id)}><td><b>{p.code}</b></td><td>{p.type==='percentage'?`${p.value}%`:`₹${p.value}`}</td><td>{p.usage_count}{p.usage_limit!=null?` / ${p.usage_limit}`:' / ∞'}</td><td>{p.starts_at||p.ends_at?`${dateTime(p.starts_at||undefined)}${p.ends_at?` → ${dateTime(p.ends_at)}`:''}`:'Always'}</td><td><Badge>{p.is_active?'Active':'Inactive'}</Badge></td></tr>)}</tbody></table></div>{!filteredPromotions.length&&<Empty title="No promotions" text="Create offers in Promotions to use them in Priyasa Store campaigns."/>}</>}
 </Card></>}
 {composer&&<Modal title="Create Priyasa Store campaign" onClose={()=>!busy&&setComposer(false)}><div className="form-stack"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:10}}>{channelMeta.map(({key,label,icon:Icon})=><button key={key} type="button" onClick={()=>setDraft({...draft,channel:key})} style={{padding:13,textAlign:'left',border:'1px solid',borderColor:draft.channel===key?'currentColor':'var(--border,#e6e6e6)',borderRadius:12,background:'transparent',cursor:'pointer'}}><Icon size={17}/><div style={{fontWeight:700,marginTop:6}}>{label}</div><small className="muted">{enabledChannels[key]?'Provider ready':'Provider not configured'}</small></button>)}</div><div className="form-grid"><label>Campaign name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Festive winback"/></label><label>Audience<select value={draft.segmentId} onChange={e=>setDraft({...draft,segmentId:e.target.value})}><option value="">All customers</option>{segments.filter(s=>s.is_active).map(s=><option key={s.segment_id} value={s.segment_id}>{s.name}</option>)}</select></label><label>Template key<input value={draft.templateKey} onChange={e=>setDraft({...draft,templateKey:e.target.value})} placeholder="approved_template_key"/><small className="muted">Use a provider-approved/registered template key.</small></label><label>Schedule (optional)<input type="datetime-local" value={draft.sendAt} onChange={e=>setDraft({...draft,sendAt:e.target.value})}/></label><label>Frequency cap / 24h<input type="number" min="1" max="20" value={draft.frequencyCap} onChange={e=>setDraft({...draft,frequencyCap:e.target.value})}/></label><label>Goal<select value={draft.goalType} onChange={e=>setDraft({...draft,goalType:e.target.value as CampaignDraft['goalType']})}><option value="order">Orders</option><option value="revenue">Revenue</option><option value="click">Clicks</option></select></label><label>Goal window (hours)<input type="number" min="1" max="720" value={draft.goalWindow} onChange={e=>setDraft({...draft,goalWindow:e.target.value})}/></label><label>Quiet hours start<input type="time" value={draft.quietStart} onChange={e=>setDraft({...draft,quietStart:e.target.value})}/></label><label>Quiet hours end<input type="time" value={draft.quietEnd} onChange={e=>setDraft({...draft,quietEnd:e.target.value})}/></label></div><div className="integration-security-banner"><Target size={18}/><span>Campaign creation only saves configuration. Scheduling is explicit, and PriyasaCore owns execution, retries, provider calls and event tracking.</span></div><div className="form-actions"><Button onClick={()=>setComposer(false)} disabled={busy}>Cancel</Button><Button className="primary" onClick={createCampaign} disabled={busy}><SaveIcon/>{busy?'Saving…':draft.sendAt?'Save & schedule':'Save draft'}</Button></div></div></Modal>}
 {selected&&<Modal title={`Campaign performance — ${selected.name}`} onClose={()=>setSelected(null)}>{stats?<div><div className="stats-grid">{[['Queued',stats.queued],['Sent',stats.sent],['Delivered',stats.delivered],['Opened',stats.opened],['Clicked',stats.clicked],['Converted',stats.converted],['Failed',stats.failed],['Unsubscribed',stats.unsubscribed]].map(([label,value])=><Card key={String(label)}><div className="metric-label">{label}</div><div className="metric">{Number(value).toLocaleString()}</div></Card>)}</div><p className="muted" style={{marginTop:14}}>Stats come directly from PriyasaCore campaign events for <code>{selected.campaign_id}</code>.</p></div>:<Loading/>}</Modal>}
 </section>
}
function SaveIcon(){return <Send size={15}/>}
