'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {apiMessage,dateTime} from '@/lib/format';
import {Badge,Button,Card,DataToolbar,Empty,ErrorState,Loading,Modal,PageHeader} from '@/components/ui';

type Section={id:number|string;key:string;type:string;title?:string|null;subtitle?:string|null;image_url?:string|null;cta_label?:string|null;cta_href?:string|null;payload?:Record<string,unknown>|null;sort_order:number;is_active:boolean;updated_at?:string|null};
type List={data:Section[]};
type Form={key:string;type:string;title:string;subtitle:string;image_url:string;cta_label:string;cta_href:string;sort_order:number;is_active:boolean;payload:string};
const templates=[
 {label:'Hero banner',type:'hero',hint:'Large editorial hero with CTA',payload:{slides:[]}},
 {label:'Image carousel',type:'image-carousel',hint:'Multi-image campaign carousel',payload:{slides:[]}},
 {label:'Product rail',type:'products-latest',hint:'Dynamic product collection',payload:{limit:12}},
 {label:'Sale rail',type:'products-sale',hint:'Promotional product rail',payload:{limit:18}},
 {label:'Category grid',type:'category-grid',hint:'Shop-by-category discovery',payload:{limit:8}},
 {label:'Promo banner',type:'banner',hint:'Split editorial promotion',payload:{}},
];
const blank:Form={key:'home',type:'banner',title:'',subtitle:'',image_url:'',cta_label:'Shop Now',cta_href:'/shop',sort_order:0,is_active:true,payload:'{}'};
export default function Merchandising(){
 const [list,setList]=useState<List|null>(null),[q,setQ]=useState(''),[editing,setEditing]=useState<Section|null>(null),[form,setForm]=useState<Form>({...blank}),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setError('');try{const p=new URLSearchParams({per_page:'100',key:q||'home'});const r=await api<List>(`/admin/cms?${p}`);setList(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load merchandising'))}}
 useEffect(()=>{load()},[]);useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q]);
 const sections=useMemo(()=>[...(list?.data||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)),[list]);
 function openEditor(s?:Section,template?:typeof templates[number]){setEditing(s||null);setForm(s?{key:s.key,type:s.type,title:s.title||'',subtitle:s.subtitle||'',image_url:s.image_url||'',cta_label:s.cta_label||'',cta_href:s.cta_href||'',sort_order:s.sort_order||0,is_active:s.is_active,payload:JSON.stringify(s.payload||{},null,2)}:{...blank,type:template?.type||blank.type,payload:JSON.stringify(template?.payload||{},null,2)});setOpen(true)}
 async function save(){setBusy(true);setError('');try{let payload:Record<string,unknown>;try{payload=JSON.parse(form.payload||'{}')}catch{throw new Error('Payload must be valid JSON.')}const body={...form,payload};const r=editing?await api(`/admin/cms/${editing.id}`,{method:'PUT',body:JSON.stringify(body)}):await api('/admin/cms',{method:'POST',body:JSON.stringify(body)});if(!r.success&&r.success!==undefined)throw new Error(r.message||'Save failed');setOpen(false);await load()}catch(e){setError(apiMessage(e,'Unable to save section'))}finally{setBusy(false)}}
 async function remove(id:Section['id']){if(!confirm('Delete this storefront section?'))return;setBusy(true);try{await api(`/admin/cms/${id}`,{method:'DELETE'});await load()}catch(e){setError(apiMessage(e,'Unable to delete section'))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Merchandising Studio" description="Control the Priyasa home experience like a modern fashion marketplace — hero, carousels, product rails, categories and campaigns." action={<div className="form-actions"><a className="btn" href="/cms">Advanced CMS</a><Button className="primary" onClick={()=>openEditor()}>+ New section</Button></div>}/>
  <div className="grid">{templates.map(t=><button key={t.type} className="card" style={{textAlign:'left',cursor:'pointer'}} onClick={()=>openEditor(undefined,t)}><div className="metric-label">{t.type}</div><div className="card-title" style={{marginTop:6}}>{t.label}</div><div className="muted" style={{marginTop:6}}>{t.hint}</div></button>)}</div>
  <Card><DataToolbar value={q} onChange={setQ} placeholder="Filter home sections…"/></Card>
  {error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:sections.length?<Card><div className="table-wrap"><table className="table"><thead><tr><th>Order</th><th>Preview</th><th>Type</th><th>Title</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{sections.map(s=><tr key={String(s.id)}><td><b>{s.sort_order}</b></td><td>{s.image_url?<img src={s.image_url} alt="" style={{width:72,height:44,objectFit:'cover',borderRadius:8}}/>:<span className="muted">No image</span>}</td><td><Badge>{s.type}</Badge></td><td><b>{s.title||'Untitled'}</b><div className="muted">{s.key}</div></td><td><Badge>{s.is_active?'Live':'Draft'}</Badge></td><td>{dateTime(s.updated_at)}</td><td><div className="form-actions"><Button onClick={()=>openEditor(s)}>Edit</Button><Button onClick={()=>remove(s.id)}>Delete</Button></div></td></tr>)}</tbody></table></div></Card>:<Card><Empty title="No home sections" text="Choose a merchandising template above to build the storefront."/></Card>}
  {open&&<Modal title={editing?'Edit merchandising section':'Create merchandising section'} onClose={()=>setOpen(false)}><div className="form-grid"><label>Key<input className="wide-control" value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/></label><label>Type<input className="wide-control" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}/></label><label>Title<input className="wide-control" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Subtitle<input className="wide-control" value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><label>Image URL<input className="wide-control" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label>CTA label<input className="wide-control" value={form.cta_label} onChange={e=>setForm({...form,cta_label:e.target.value})}/></label><label>CTA link<input className="wide-control" value={form.cta_href} onChange={e=>setForm({...form,cta_href:e.target.value})}/></label><label>Sort order<input className="wide-control" type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label><label className="address-default"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Published</label><label className="full-span">Payload JSON<textarea className="wide-control note" rows={10} value={form.payload} onChange={e=>setForm({...form,payload:e.target.value})}/></label><div className="form-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save & publish'}</Button></div></div></Modal>}
 </section>
}
