'use client';

import {useEffect,useState} from 'react';
import {ArrowDown,ArrowUp,RefreshCw,Save,Star} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Badge,Button,Card,DataToolbar,ErrorState,Loading,PageHeader} from '@/components/ui';

type Product={id:number;name:string;sku?:string;brand?:string;price?:number;is_featured?:boolean;merchandising_score?:number;sort_order?:number;badge?:string};
export default function Merchandising(){
 const[rows,setRows]=useState<Product[]>([]),[q,setQ]=useState(''),[featured,setFeatured]=useState('all'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function load(){setLoading(true);setError('');try{const p=new URLSearchParams({per_page:'100'});if(q.trim())p.set('search',q.trim());if(featured!=='all')p.set('featured',featured);const r=await api<any>(`/admin/merchandising/products?${p}`);const raw=r.data;setRows(Array.isArray(raw)?raw:Array.isArray(raw?.data)?raw.data:[])}catch(e){setError(apiMessage(e,'Unable to load merchandising controls.'))}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>clearTimeout(t)},[q,featured]);
 const patch=(id:number,p:Partial<Product>)=>setRows(v=>v.map(x=>x.id===id?{...x,...p}:x));
 async function save(p:Product){setBusy(true);setError('');try{await api(`/admin/merchandising/products/${p.id}`,{method:'PATCH',body:JSON.stringify({is_featured:p.is_featured,merchandising_score:Number(p.merchandising_score||0),sort_order:Number(p.sort_order||0),badge:p.badge||null})});setMessage(`${p.name} saved.`)}catch(e){setError(apiMessage(e,'Unable to save merchandising settings.'))}finally{setBusy(false)}}
 async function move(i:number,d:-1|1){const n=i+d;if(n<0||n>=rows.length)return;const copy=[...rows];[copy[i],copy[n]]=[copy[n],copy[i]];setRows(copy.map((p,index)=>({...p,sort_order:index})));setBusy(true);try{await api('/admin/merchandising/products/reorder',{method:'POST',body:JSON.stringify({products:copy.map((p,index)=>({id:p.id,sort_order:index}))})});setMessage('Product order saved.')}catch(e){setError(apiMessage(e,'Unable to save product order.'));await load()}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Merchandising" description="Control product ranking, featured placement, merchandising score and storefront badges from Priyasa Admin." action={<Button onClick={load} disabled={loading||busy}><RefreshCw size={14}/> Refresh</Button>}/>{message&&<div className="form-success">{message}</div>}{error&&<ErrorState error={error} onRetry={load}/>}<DataToolbar value={q} onChange={setQ} placeholder="Search product, SKU or brand…"><select value={featured} onChange={e=>setFeatured(e.target.value)}><option value="all">All products</option><option value="true">Featured only</option><option value="false">Not featured</option></select><Badge>{rows.length} loaded</Badge></DataToolbar>{loading?<Loading/>:<Card><div className="table-wrap"><table className="table"><thead><tr><th>Rank</th><th>Product</th><th>Price</th><th>Featured</th><th>Score</th><th>Badge</th><th/></tr></thead><tbody>{rows.map((p,i)=><tr key={p.id}><td><div className="form-actions"><Button onClick={()=>move(i,-1)} disabled={i===0||busy}><ArrowUp size={14}/></Button><Button onClick={()=>move(i,1)} disabled={i===rows.length-1||busy}><ArrowDown size={14}/></Button><b>{i+1}</b></div></td><td><b>{p.name}</b><div className="muted">{p.brand||'—'} · {p.sku||p.id}</div></td><td>₹{Number(p.price||0).toLocaleString('en-IN')}</td><td><label className="check"><input type="checkbox" checked={Boolean(p.is_featured)} onChange={e=>patch(p.id,{is_featured:e.target.checked})}/><Star size={14}/></label></td><td><input className="compact-input" type="number" value={p.merchandising_score??0} onChange={e=>patch(p.id,{merchandising_score:Number(e.target.value)})}/></td><td><input className="compact-input" value={p.badge||''} maxLength={80} onChange={e=>patch(p.id,{badge:e.target.value})} placeholder="NEW / TRENDING"/></td><td><Button className="primary" onClick={()=>save(p)} disabled={busy}><Save size={14}/> Save</Button></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty">No products match the current filter.</div>}</Card>}</section>;
}
