'use client';

import Link from 'next/link';
import {useEffect, useMemo, useState} from 'react';
import {ArrowDown, ArrowUp, Eye, LayoutTemplate, Plus, Save, Trash2} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Badge, Button, Card, ErrorState, Loading, Modal, PageHeader} from '@/components/ui';

type Section={id:number|string;key:string;type:string;title?:string;subtitle?:string;image_url?:string;cta_label?:string;cta_url?:string;sort_order?:number;active?:boolean;payload?:Record<string,unknown>;content?:Record<string,unknown>};

const TYPES=[
 ['hero_slider','Hero slider'],['service_strip','Service strip'],['category_tiles','Category tiles'],['product_carousel','Product carousel'],['product_grid','Product grid'],['flash_sale','Flash sale'],['offer_banner','Offer banner'],['editorial_grid','Editorial grid'],['brand_carousel','Brand carousel'],['review_carousel','Review carousel'],['recommendations','Recommendations'],
];
const blank=():Section=>({id:'new',key:`home-section-${Date.now()}`,type:'product_carousel',title:'',subtitle:'',image_url:'',cta_label:'',cta_url:'',sort_order:0,active:true,payload:{}});

export default function HomeBuilder(){
 const[sections,setSections]=useState<Section[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[editing,setEditing]=useState<Section|null>(null);
 async function load(){setLoading(true);setError('');try{const r=await api<any>('/admin/cms?per_page=200');const raw=r.data;const rows=Array.isArray(raw)?raw:Array.isArray(raw?.data)?raw.data:[];setSections(rows.filter((s:any)=>String(s.key||'').startsWith('home-')).sort((a:any,b:any)=>(Number(a.sort_order??0)-Number(b.sort_order??0))));}catch(e){setError(apiMessage(e,'Unable to load homepage sections.'))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const activeCount=useMemo(()=>sections.filter(s=>s.active!==false).length,[sections]);
 async function save(){if(!editing)return;setBusy(true);setError('');setMessage('');try{let r:any;if(editing.id==='new'){r=await api('/admin/cms',{method:'POST',body:JSON.stringify({key:editing.key,type:editing.type,title:editing.title,subtitle:editing.subtitle,image_url:editing.image_url,cta_label:editing.cta_label,cta_url:editing.cta_url,sort_order:editing.sort_order,active:editing.active,payload:editing.payload||{}})}else{r=await api(`/admin/cms/${encodeURIComponent(String(editing.id))}`,{method:'PUT',body:JSON.stringify({key:editing.key,type:editing.type,title:editing.title,subtitle:editing.subtitle,image_url:editing.image_url,cta_label:editing.cta_label,cta_url:editing.cta_url,sort_order:editing.sort_order,active:editing.active,payload:editing.payload||{}})})}setMessage(r.message||'Homepage section saved.');setEditing(null);await load()}catch(e){setError(apiMessage(e,'Unable to save homepage section.'))}finally{setBusy(false)}}
 async function remove(id:number|string){if(!window.confirm('Delete this homepage section?'))return;setBusy(true);try{await api(`/admin/cms/${encodeURIComponent(String(id))}`,{method:'DELETE'});setMessage('Homepage section deleted.');await load()}catch(e){setError(apiMessage(e,'Unable to delete section.'))}finally{setBusy(false)}}
 async function move(index:number,direction:-1|1){const next=index+direction;if(next<0||next>=sections.length)return;const copy=[...sections];[copy[index],copy[next]]=[copy[next],copy[index]];setSections(copy);try{await api('/admin/cms/reorder',{method:'POST',body:JSON.stringify({sections:copy.map((s,i)=>({id:s.id,sort_order:i}))})});setMessage('Homepage order updated.')}catch(e){setError(apiMessage(e,'Unable to persist homepage order.'));await load()}}
 const update=(patch:Partial<Section>)=>setEditing(v=>v?{...v,...patch}:v);
 return <section className="content"><PageHeader title="Storefront Home Builder" description="Control Priyasa Store homepage sections, content, visibility and merchandising order without editing code." action={<div className="form-actions"><Link href="/cms" className="btn">CMS records</Link><Link href="/cms/themes" className="btn">Themes</Link><Button className="primary" onClick={()=>setEditing(blank())}><Plus size={15}/> Add section</Button></div>}/>{message&&<div className="form-success" role="status">{message}</div>}{error&&<ErrorState error={error} onRetry={load}/>} {loading?<Loading/>:<><div className="grid"><Card><div className="metric-label">Homepage sections</div><div className="metric">{sections.length}</div><div className="metric-label">All configured home-* blocks</div></Card><Card><div className="metric-label">Published/active</div><div className="metric">{activeCount}</div><div className="metric-label">Visible to storefront</div></Card><Card><div className="metric-label">Control mode</div><div className="metric">API</div><div className="metric-label">PriyasaCore is the source of truth</div></Card></div><Card><div className="table-wrap"><table className="table"><thead><tr><th>Order</th><th>Section</th><th>Type</th><th>Status</th><th>Content</th><th/></tr></thead><tbody>{sections.map((s,i)=><tr key={String(s.id)}><td><div className="form-actions"><Button onClick={()=>move(i,-1)} disabled={i===0||busy} aria-label="Move up"><ArrowUp size={14}/></Button><Button onClick={()=>move(i,1)} disabled={i===sections.length-1||busy} aria-label="Move down"><ArrowDown size={14}/></Button></div></td><td><b>{s.title||s.key}</b><div className="muted"><code>{s.key}</code></div></td><td><Badge>{s.type}</Badge></td><td><Badge>{s.active===false?'Inactive':'Active'}</Badge></td><td>{s.subtitle||s.image_url||'Typed section payload'}</td><td><div className="form-actions"><Button onClick={()=>setEditing({...s,payload:s.payload||s.content||{}})}><LayoutTemplate size={14}/> Edit</Button><Button onClick={()=>remove(s.id)} disabled={busy}><Trash2 size={14}/></Button></div></td></tr>)}</tbody></table></div>{!sections.length&&<div className="empty">No home sections yet. Add the first section to start building the storefront.</div>}</Card></>}</section>;

 function Editor(){return null}
}
