'use client';

import Link from 'next/link';
import {useEffect, useMemo, useState} from 'react';
import {ArrowDown, ArrowUp, Eye, LayoutTemplate, Plus, Save, Trash2} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Badge, Button, Card, ErrorState, Loading, Modal, PageHeader} from '@/components/ui';

type Section={id:number|string;key:string;type:string;title?:string;subtitle?:string;image_url?:string;cta_label?:string;cta_href?:string;sort_order?:number;is_active?:boolean;content?:Record<string,unknown>};
const TYPES=[['hero_slider','Hero slider'],['service_strip','Service strip'],['category_tiles','Category tiles'],['product_carousel','Product carousel'],['product_grid','Product grid'],['flash_sale','Flash sale'],['offer_banner','Offer banner'],['editorial_grid','Editorial grid'],['brand_carousel','Brand carousel'],['review_carousel','Review carousel'],['recommendations','Recommendations']];
const blank=():Section=>({id:'new',key:`home-section-${Date.now()}`,type:'product_carousel',title:'',subtitle:'',image_url:'',cta_label:'',cta_href:'',sort_order:0,is_active:true,content:{}});

export default function HomeBuilder(){
 const[sections,setSections]=useState<Section[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Section|null>(null),[json,setJson]=useState('{}');
 async function load(){setLoading(true);setError('');try{const r=await api<any>('/admin/cms?per_page=200');const raw=r.data;const rows=Array.isArray(raw)?raw:Array.isArray(raw?.data)?raw.data:[];setSections(rows.filter((s:any)=>String(s.key||'').startsWith('home-')).sort((a:any,b:any)=>Number(a.sort_order??0)-Number(b.sort_order??0)))}catch(e){setError(apiMessage(e,'Unable to load homepage sections.'))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const activeCount=useMemo(()=>sections.filter(s=>s.is_active!==false).length,[sections]);
 function edit(s:Section){setEditing({...s,content:s.content||{}});setJson(JSON.stringify(s.content||{},null,2))}
 function editNew(){const s=blank();setEditing(s);setJson('{}')}
 const update=(patch:Partial<Section>)=>setEditing(v=>v?{...v,...patch}:v);
 async function save(){if(!editing)return;let content:Record<string,unknown>;try{const parsed=JSON.parse(json);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('Content must be a JSON object.');content=parsed}catch(e){setError(e instanceof Error?e.message:'Invalid JSON content.');return}if(!editing.key.trim())return setError('Section key is required.');setBusy(true);setError('');setMessage('');try{const data={key:editing.key.trim(),type:editing.type,title:editing.title||null,subtitle:editing.subtitle||null,image_url:editing.image_url||null,cta_label:editing.cta_label||null,cta_href:editing.cta_href||null,sort_order:Number(editing.sort_order??0),is_active:editing.is_active!==false,content};const r=editing.id==='new'?await api('/admin/cms',{method:'POST',body:JSON.stringify(data)}):await api(`/admin/cms/${encodeURIComponent(String(editing.id))}`,{method:'PUT',body:JSON.stringify(data)});setMessage(r.message||'Homepage section saved.');setEditing(null);await load()}catch(e){setError(apiMessage(e,'Unable to save homepage section.'))}finally{setBusy(false)}}
 async function remove(id:number|string){if(!window.confirm('Delete this homepage section?'))return;setBusy(true);setError('');try{await api(`/admin/cms/${encodeURIComponent(String(id))}`,{method:'DELETE'});setMessage('Homepage section deactivated.');await load()}catch(e){setError(apiMessage(e,'Unable to delete section.'))}finally{setBusy(false)}}
 async function move(index:number,direction:-1|1){const next=index+direction;if(next<0||next>=sections.length)return;const copy=[...sections];[copy[index],copy[next]]=[copy[next],copy[index]];setSections(copy);setBusy(true);try{await api('/admin/cms/reorder',{method:'POST',body:JSON.stringify({sections:copy.map((s,i)=>({id:Number(s.id),sort_order:i}))})});setMessage('Homepage order updated.')}catch(e){setError(apiMessage(e,'Unable to persist homepage order.'));await load()}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Storefront Home Builder" description="Control Priyasa Store homepage sections, content, visibility and merchandising order without editing code." action={<div className="form-actions"><Link href="/cms" className="btn">CMS records</Link><Link href="/cms/themes" className="btn">Themes</Link><Button className="primary" onClick={editNew}><Plus size={15}/> Add section</Button></div>}/>{message&&<div className="form-success" role="status">{message}</div>}{error&&<ErrorState error={error} onRetry={load}/>} {loading?<Loading/>:<><div className="grid"><Card><div className="metric-label">Homepage sections</div><div className="metric">{sections.length}</div><div className="metric-label">Configured home-* blocks</div></Card><Card><div className="metric-label">Active</div><div className="metric">{activeCount}</div><div className="metric-label">Visible to storefront</div></Card><Card><div className="metric-label">Source of truth</div><div className="metric">API</div><div className="metric-label">PriyasaCore CMS</div></Card></div><Card><div className="table-wrap"><table className="table"><thead><tr><th>Order</th><th>Section</th><th>Type</th><th>Status</th><th>Content</th><th>Actions</th></tr></thead><tbody>{sections.map((s,i)=><tr key={String(s.id)}><td><div className="form-actions"><Button onClick={()=>move(i,-1)} disabled={i===0||busy} aria-label="Move up"><ArrowUp size={14}/></Button><Button onClick={()=>move(i,1)} disabled={i===sections.length-1||busy} aria-label="Move down"><ArrowDown size={14}/></Button></div></td><td><b>{s.title||s.key}</b><div className="muted"><code>{s.key}</code></div></td><td><Badge>{s.type}</Badge></td><td><Badge>{s.is_active===false?'Inactive':'Active'}</Badge></td><td>{s.subtitle||s.image_url||'Structured content'}</td><td><div className="form-actions"><Button onClick={()=>edit(s)}><LayoutTemplate size={14}/> Edit</Button><Button onClick={()=>remove(s.id)} disabled={busy}><Trash2 size={14}/></Button></div></td></tr>)}</tbody></table></div>{!sections.length&&<div className="empty">No homepage sections yet. Add the first section to start building the storefront.</div>}</Card></>}
 {editing&&<Modal title={editing.id==='new'?'Add homepage section':'Edit homepage section'} onClose={()=>!busy&&setEditing(null)}><div className="section-grid"><label className="form">Section key<input value={editing.key} onChange={e=>update({key:e.target.value})} placeholder="home-new-arrivals"/></label><label className="form">Section type<select value={editing.type} onChange={e=>update({type:e.target.value})}>{TYPES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><div className="section-grid"><label className="form">Title<input value={editing.title||''} onChange={e=>update({title:e.target.value})}/></label><label className="form">Subtitle<input value={editing.subtitle||''} onChange={e=>update({subtitle:e.target.value})}/></label></div><div className="section-grid"><label className="form">Image URL<input value={editing.image_url||''} onChange={e=>update({image_url:e.target.value})}/></label><label className="form">Sort order<input type="number" value={editing.sort_order??0} onChange={e=>update({sort_order:Number(e.target.value)})}/></label></div><div className="section-grid"><label className="form">CTA label<input value={editing.cta_label||''} onChange={e=>update({cta_label:e.target.value})}/></label><label className="form">CTA URL<input value={editing.cta_href||''} onChange={e=>update({cta_href:e.target.value})}/></label></div><label className="form">Content JSON<textarea value={json} onChange={e=>setJson(e.target.value)} spellCheck={false} style={{minHeight:180}}/></label><label className="form"><span>Visibility</span><select value={editing.is_active===false?'inactive':'active'} onChange={e=>update({is_active:e.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="form-actions"><Button onClick={()=>setEditing(null)} disabled={busy}>Cancel</Button><Button className="primary" onClick={save} disabled={busy}><Save size={14}/>{busy?'Saving…':'Save section'}</Button><Link href="/cms" className="btn"><Eye size={14}/> CMS</Link></div></Modal>}
 </section>;
}
