'use client';

import {useEffect,useMemo,useState} from 'react';
import {Check,Clock3,Palette,RefreshCw,Sparkles,Zap} from 'lucide-react';
import {api} from '@/lib/api';

type Setting={key:string;value:string|number|boolean|null};
type HomeResponse={data?:{theme?:{key:string;name:string;status:string;version:number;schedule?:{starts_at?:string|null;ends_at?:string|null}}}};

type ThemePreset={key:string;name:string;subtitle:string;icon:string;primary:string;secondary:string;accent:string;background:string;mode:'manual'|'automatic';startsAt?:string;endsAt?:string;tags:string[]};

const themes:ThemePreset[]=[
 {key:'default',name:'PRIYASA Default',subtitle:'Clean premium storefront for everyday commerce.',icon:'✦',primary:'#171717',secondary:'#737373',accent:'#D4AF37',background:'#FFFFFF',mode:'manual',tags:['Always available','Premium']},
 {key:'navratri-2026',name:'Navratri 2026',subtitle:'Festive fashion with rich plum, rose and antique-gold accents.',icon:'✦',primary:'#8B1E3F',secondary:'#64132D',accent:'#F4B942',background:'#FFF8F2',mode:'automatic',startsAt:'2026-10-11T00:00:00+05:30',endsAt:'2026-10-20T23:59:59+05:30',tags:['Festive','Garba','9-day edit']},
 {key:'dussehra-2026',name:'Dussehra 2026',subtitle:'Bold ceremonial red, saffron and gold for the festive finale.',icon:'◈',primary:'#A52A1F',secondary:'#7A1C16',accent:'#D9A441',background:'#FFF7EA',mode:'automatic',startsAt:'2026-10-20T00:00:00+05:30',endsAt:'2026-10-22T23:59:59+05:30',tags:['Festive','Dussehra']},
 {key:'diwali-2026',name:'Diwali 2026',subtitle:'Luxury midnight plum, champagne gold and warm diya glow.',icon:'◉',primary:'#4A173C',secondary:'#24101F',accent:'#E8BE63',background:'#FFF9F0',mode:'automatic',startsAt:'2026-11-01T00:00:00+05:30',endsAt:'2026-11-12T23:59:59+05:30',tags:['Festive','Diwali','Luxury']},
 {key:'holi-2026',name:'Holi 2026',subtitle:'A playful colour-forward fashion theme with soft editorial surfaces.',icon:'✺',primary:'#C02667',secondary:'#6D28D9',accent:'#F59E0B',background:'#FFF8FB',mode:'automatic',startsAt:'2026-02-28T00:00:00+05:30',endsAt:'2026-03-06T23:59:59+05:30',tags:['Colour','Holi','Playful']},
 {key:'independence-2026',name:'Independence Day 2026',subtitle:'Elegant saffron, ivory and green accents with a restrained national palette.',icon:'◆',primary:'#C65A11',secondary:'#176B45',accent:'#D5A83A',background:'#FFFDF7',mode:'automatic',startsAt:'2026-08-10T00:00:00+05:30',endsAt:'2026-08-18T23:59:59+05:30',tags:['Independence','Tricolour']},
 {key:'republic-2026',name:'Republic Day 2026',subtitle:'A refined tricolour-inspired editorial theme.',icon:'◆',primary:'#1F4E79',secondary:'#A84A19',accent:'#D6A72C',background:'#F8FBFF',mode:'automatic',startsAt:'2026-01-23T00:00:00+05:30',endsAt:'2026-01-29T23:59:59+05:30',tags:['Republic Day','Tricolour']},
];

export default function Themes(){
 const [settings,setSettings]=useState<Setting[]>([]); const [active,setActive]=useState('default'); const [mode,setMode]=useState<'manual'|'automatic'>('automatic');
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState('');
 const [home,setHome]=useState<HomeResponse|null>(null);
 const load=async()=>{setLoading(true);setError('');try{const [s,h]=await Promise.all([api<{settings:Setting[]}>('/admin/settings'),api<HomeResponse>('/storefront/home').catch(()=>null)]);const rows=s.data?.settings||[];setSettings(rows);const key=String(rows.find(x=>x.key==='storefront.theme_key')?.value||'default');const m=String(rows.find(x=>x.key==='storefront.theme_mode')?.value||'automatic');setActive(key);setMode(m==='manual'?'manual':'automatic');setHome(h as HomeResponse|null)}catch(e){setError(e instanceof Error?e.message:'Unable to load themes')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const activeTheme=useMemo(()=>themes.find(t=>t.key===active)||themes[0],[active]);
 async function applyTheme(theme:ThemePreset){setSaving(true);setError('');setSaved('');try{await api('/admin/settings',{method:'PUT',body:JSON.stringify({settings:{'storefront.theme_key':theme.key,'storefront.theme_mode':'manual'}})});setActive(theme.key);setMode('manual');setSaved(`${theme.name} is now active on the storefront.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to apply theme')}finally{setSaving(false)}}
 async function enableAutomation(){setSaving(true);setError('');setSaved('');try{await api('/admin/settings',{method:'PUT',body:JSON.stringify({settings:{'storefront.theme_key':'default','storefront.theme_mode':'automatic'}})});setMode('automatic');setSaved('Automatic seasonal scheduling is enabled. The storefront will select the highest-priority published theme whose schedule matches the current date.');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to enable automation')}finally{setSaving(false)}}
 const storefrontTheme=home?.data?.theme;
 return <main className="space-y-6">
  <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-medium" style={{borderColor:`${activeTheme.accent}55`,background:`${activeTheme.accent}12`,color:activeTheme.primary}}><Sparkles size={13}/> Seasonal Theme Studio</div><h1 className="text-3xl font-semibold tracking-tight">Storefront Themes</h1><p className="mt-1 max-w-3xl text-sm text-zinc-500">Choose a ready-made PRIYASA festive experience and apply it instantly, or enable automation so the homepage changes itself on scheduled dates.</p></div><button onClick={load} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-medium shadow-sm disabled:opacity-50"><RefreshCw size={15} className={loading?'animate-spin':''}/> Refresh</button></header>
  {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  {saved&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{saved}</div>}
  <section className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="grid gap-0 lg:grid-cols-[1.35fr_.65fr]"><div className="relative min-h-[270px] overflow-hidden p-7 text-white" style={{background:`radial-gradient(circle at 80% 10%, ${activeTheme.accent}55, transparent 35%), linear-gradient(135deg, ${activeTheme.secondary}, ${activeTheme.primary})`}}><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full border" style={{borderColor:`${activeTheme.accent}55`}}/><div className="absolute -bottom-24 left-1/3 h-56 w-56 rounded-full border" style={{borderColor:`${activeTheme.accent}35`}}/><div className="relative z-10 flex h-full flex-col justify-between"><div><div className="text-xs uppercase tracking-[.25em] opacity-70">Currently selected</div><div className="mt-3 flex items-center gap-3"><span className="text-4xl">{activeTheme.icon}</span><h2 className="text-3xl font-semibold">{activeTheme.name}</h2></div><p className="mt-3 max-w-xl text-sm leading-6 text-white/75">{activeTheme.subtitle}</p></div><div className="flex flex-wrap gap-2">{activeTheme.tags.map(x=><span key={x} className="rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs">{x}</span>)}</div></div></div><div className="flex flex-col justify-between p-7"><div><div className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Storefront state</div><div className="mt-3 flex items-center gap-2 text-sm font-medium"><span className="h-2.5 w-2.5 rounded-full bg-emerald-500"/>{mode==='automatic'?'Automatic seasonal mode':'Manual theme mode'}</div>{storefrontTheme&&<p className="mt-2 text-xs text-zinc-500">API currently resolves: <b>{storefrontTheme.name}</b></p>}</div><div className="mt-6 space-y-3"><button onClick={enableAutomation} disabled={saving||mode==='automatic'} className="flex w-full items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-medium disabled:opacity-50"><Clock3 size={15}/> {mode==='automatic'?'Automation enabled':'Enable automatic scheduling'}</button><div className="text-center text-xs text-zinc-400">Manual selection always takes effect immediately.</div></div></div></div></section>
  <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Choose a theme</h2><p className="text-sm text-zinc-500">Every preset controls colours, surfaces, festive decorations and the dynamic homepage theme identity.</p></div></div>{loading?<div className="rounded-2xl border bg-white p-8 text-sm text-zinc-500">Loading theme catalogue…</div>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{themes.map(theme=><article key={theme.key} className={`overflow-hidden rounded-2xl border bg-white shadow-sm transition ${active===theme.key&&mode==='manual'?'ring-2':''}`} style={{outlineColor:active===theme.key&&mode==='manual'?theme.accent:'transparent'}}><div className="h-28 p-5" style={{background:`radial-gradient(circle at 80% 20%, ${theme.accent}66, transparent 30%), linear-gradient(135deg, ${theme.secondary}, ${theme.primary})`}}><div className="flex items-start justify-between text-white"><span className="text-3xl">{theme.icon}</span>{active===theme.key&&mode==='manual'?<span className="inline-flex items-center gap-1 rounded-full bg-white/15 px-2.5 py-1 text-[11px]"><Check size={12}/> Active</span>:<span className="rounded-full bg-white/10 px-2.5 py-1 text-[11px]">{theme.mode==='automatic'?'Scheduled':'Base'}</span>}</div></div><div className="p-5"><h3 className="font-semibold">{theme.name}</h3><p className="mt-1 min-h-10 text-xs leading-5 text-zinc-500">{theme.subtitle}</p><div className="mt-4 flex gap-1.5">{[theme.primary,theme.secondary,theme.accent,theme.background].map((c,i)=><span key={i} className="h-6 w-6 rounded-full border" style={{background:c}} title={c}/>)}</div><div className="mt-4 flex flex-wrap gap-1.5">{theme.tags.map(x=><span key={x} className="rounded-full bg-zinc-100 px-2.5 py-1 text-[11px] text-zinc-600">{x}</span>)}</div>{theme.startsAt&&<div className="mt-4 flex items-center gap-2 text-xs text-zinc-400"><Clock3 size={13}/> {new Date(theme.startsAt).toLocaleDateString('en-IN')} – {new Date(theme.endsAt||theme.startsAt).toLocaleDateString('en-IN')}</div>}<button onClick={()=>applyTheme(theme)} disabled={saving||active===theme.key&&mode==='manual'} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50" style={{background:theme.primary}}><Zap size={15}/>{active===theme.key&&mode==='manual'?'Currently Active':'Apply Theme'}</button></div></article>)}</div>}</section>
  <section className="rounded-2xl border bg-zinc-50 p-5"><div className="flex gap-3"><Palette className="mt-0.5 text-zinc-500" size={18}/><div><h3 className="font-semibold">How automation works</h3><p className="mt-1 text-sm leading-6 text-zinc-500">In automatic mode, PriyasaCore resolves the published seasonal theme whose start/end window contains the current time. Priority decides which theme wins if windows overlap. In manual mode, the selected theme is applied immediately.</p></div></div></section>
 </main>
}
