'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {apiMessage,dateTime,titleCase} from '@/lib/format';
import {Badge,Button,Card,DataToolbar,Empty,ErrorState,Loading,PageHeader,Pagination} from '@/components/ui';

type Audit={id:number|string;action:string;actor_type?:string|null;actor_id?:string|number|null;entity_type?:string|null;entity_id?:string|number|null;data?:Record<string,unknown>|null;ip?:string|null;request_id?:string|null;created_at?:string};
type Page<T>={data:T[];current_page:number;last_page:number;total:number};

export default function Audit(){
 const [items,setItems]=useState<Audit[]>([]),[page,setPage]=useState(1),[lastPage,setLastPage]=useState(1),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[action,setAction]=useState(''),[entity,setEntity]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selected,setSelected]=useState<Audit|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const qs=new URLSearchParams({page:String(page),per_page:'25'});if(search)qs.set('search',search);if(action)qs.set('action',action);if(entity)qs.set('entity_type',entity);if(from)qs.set('from',from);if(to)qs.set('to',to);const r=await api<{audit_logs:Page<Audit>}>(`/admin/audit-logs?${qs}`);const p=r.data?.audit_logs;setItems(p?.data||[]);setLastPage(p?.last_page||1);setTotal(p?.total||0)}catch(e){setError(apiMessage(e))}finally{setLoading(false)}};
 useEffect(()=>{load()},[page,action,entity,from,to]);
 useEffect(()=>{const t=setTimeout(()=>{if(page!==1)setPage(1);else load()},350);return()=>clearTimeout(t)},[search]);
 return <div className="page">
  <PageHeader title="Audit Logs" description="Immutable administrative activity and security-sensitive changes." />
  <Card><DataToolbar value={search} onChange={setSearch} placeholder="Search action, actor, entity or request ID…"><select value={action} onChange={e=>{setAction(e.target.value);setPage(1)}}><option value="">All actions</option><option value="settings.updated">Settings updated</option><option value="order.status_changed">Order status changed</option><option value="customer.status_changed">Customer status changed</option></select><select value={entity} onChange={e=>{setEntity(e.target.value);setPage(1)}}><option value="">All entities</option><option value="system_setting">System setting</option><option value="order">Order</option><option value="customer">Customer</option><option value="product">Product</option></select><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/><Button onClick={load}>Refresh</Button></DataToolbar>
   {loading?<Loading/>:error?<ErrorState error={error} onRetry={load}/>:items.length===0?<Empty title="No audit events" text="Try changing the filters or date range."/>:<><div className="table-wrap"><table><thead><tr><th>Time</th><th>Action</th><th>Actor</th><th>Entity</th><th>IP</th><th>Request ID</th></tr></thead><tbody>{items.map(x=><tr key={x.id} onClick={()=>setSelected(x)} style={{cursor:'pointer'}}><td>{dateTime(x.created_at)}</td><td><Badge>{titleCase(x.action)}</Badge></td><td>{x.actor_id?`${titleCase(x.actor_type)} #${x.actor_id}`:'System'}</td><td>{x.entity_type?`${titleCase(x.entity_type)} #${x.entity_id??'—'}`:'—'}</td><td>{x.ip||'—'}</td><td>{x.request_id||'—'}</td></tr>)}</tbody></table></div><Pagination page={page} lastPage={lastPage} onChange={setPage}/><div className="muted">{total.toLocaleString('en-IN')} total events</div></>}
  </Card>
  {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="modal"><div className="modal-head"><h2>Audit event #{selected.id}</h2><button onClick={()=>setSelected(null)} aria-label="Close">×</button></div><div className="detail-grid"><div><small>Action</small><strong>{selected.action}</strong></div><div><small>Time</small><strong>{dateTime(selected.created_at)}</strong></div><div><small>Actor</small><strong>{selected.actor_id?`${selected.actor_type||'User'} #${selected.actor_id}`:'System'}</strong></div><div><small>Entity</small><strong>{selected.entity_type?`${selected.entity_type} #${selected.entity_id??'—'}`:'—'}</strong></div><div><small>IP</small><strong>{selected.ip||'—'}</strong></div><div><small>Request ID</small><strong>{selected.request_id||'—'}</strong></div></div><pre style={{whiteSpace:'pre-wrap',overflow:'auto'}}>{JSON.stringify(selected.data||{},null,2)}</pre></div></div>}
 </div>
}