'use client';
import {useEffect,useState} from 'react';import {api} from '@/lib/api';import {Order,Paginated,Address} from '@/lib/types';import {money,dateTime,titleCase,apiMessage} from '@/lib/format';import {PageHeader,Card,DataToolbar,Pagination,Modal,Button,Badge,Loading,ErrorState} from '@/components/ui';
const statuses=['','pending_payment','payment_failed','confirmed','processing','packed','shipped','in_transit','out_for_delivery','delivered','return_requested','returned','refunded','cancelled'];
const terminalStatuses=new Set(['delivered','returned','refunded','cancelled']);
const shipmentBlockedStatuses=new Set(['pending_payment','payment_failed','return_requested','returned','refunded','cancelled']);
function AddressBlock({a}:{a?:Address|null}){if(!a)return <div className="muted">No address returned.</div>;return <div className="muted">{a.recipient_name} · {a.phone}<br/>{a.line1}{a.line2?`, ${a.line2}`:''}{a.area?`, ${a.area}`:''}<br/>{a.city}, {a.state} {a.postal_code}{a.landmark?` · ${a.landmark}`:''}</div>}
function ReturnBlock({value}:{value?:Record<string,unknown>|null}){if(!value)return <div className="muted">No active return record.</div>;const entries=Object.entries(value).filter(([,v])=>v!==null&&v!==undefined&&v!=='');return <div className="quick">{entries.map(([k,v])=><div key={k}><b>{titleCase(k.replaceAll('_',' '))}</b><span>{typeof v==='object'?JSON.stringify(v):String(v)}</span></div>)}</div>}
export default function Orders(){const [list,setList]=useState<Paginated<Order>|null>(null);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [detail,setDetail]=useState<Order|null>(null);const [nextStatus,setNextStatus]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
async function load(){setError('');try{const p=new URLSearchParams({page:String(page),per_page:'50'});if(q)p.set('search',q);if(status)p.set('status',status);const r=await api<Paginated<Order>>(`/admin/orders?${p}`);setList(r.data||null)}catch(e){setError(apiMessage(e))}}useEffect(()=>{load()},[page,status]);useEffect(()=>{const t=setTimeout(()=>{setPage(1);load()},350);return()=>clearTimeout(t)},[q]);
async function open(id:Order['id']){setError('');try{const r=await api<Order>(`/admin/orders/${id}`);setDetail(r.data||null);setNextStatus(r.data?.status||'')}catch(e){setError(apiMessage(e,'Unable to load order'))}}
async function transition(){if(!detail||!nextStatus||nextStatus===detail.status||terminalStatuses.has(detail.status))return;setBusy(true);try{const r=await api<Order>(`/admin/orders/${detail.id}/status`,{method:'POST',body:JSON.stringify({status:nextStatus,note})});setDetail({...detail,status:nextStatus,statusHistory:r.data?.statusHistory||detail.statusHistory});setNote('');await load()}catch(e){setError(apiMessage(e,'Status update failed'))}finally{setBusy(false)}}
async function shipmentAction(action:'create'|'refresh'|'cancel'){if(!detail)return;if(action==='create'&&shipmentBlockedStatuses.has(detail.status))return;if(action==='cancel'){if(!detail.shipment||terminalStatuses.has(detail.status))return;if(!window.confirm('Cancel this shipment? This action may not be reversible with the carrier.'))return}setBusy(true);try{if(action==='create')await api(`/admin/orders/${detail.id}/shipment`,{method:'POST',body:JSON.stringify({provider:'shiprocket'})});else if(detail.shipment)await api(`/admin/shipments/${detail.shipment.id}${action==='cancel'?'/cancel':''}`,{method:'POST'});await open(detail.id)}catch(e){setError(apiMessage(e,'Shipping operation failed'))}finally{setBusy(false)}}
const statusLocked=!!detail&&terminalStatuses.has(detail.status);const shipmentCreateBlocked=!!detail&&shipmentBlockedStatuses.has(detail.status);const shipmentCancelBlocked=!!detail&&(!detail.shipment||terminalStatuses.has(detail.status));
return <section className="content"><PageHeader title="Orders" description="Review orders and control the complete payment-to-delivery lifecycle."/><Card><DataToolbar value={q} onChange={v=>{setPage(1);setQ(v)}} placeholder="Search order number…"><select className="filter-select" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}>{statuses.map(s=><option key={s} value={s}>{s?titleCase(s):'All statuses'}</option>)}</select></DataToolbar>{error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:list?.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Order</th><th>Customer</th><th>Created</th><th>Total</th><th>Status</th><th/></tr></thead><tbody>{list.data.map(o=><tr key={String(o.id)}><td><b>#{o.order_number||o.id}</b></td><td>{o.customer?.name||o.customer?.phone||'—'}</td><td>{dateTime(o.created_at)}</td><td>{money(o.grand_total??o.total,o.currency||'INR')}</td><td><Badge>{titleCase(o.status)}</Badge></td><td><Button onClick={()=>open(o.id)}>View</Button></td></tr>)}</tbody></table></div>:<div className="empty"><strong>No orders</strong><span>No records match the current filters.</span></div>}<Pagination page={list?.current_page||1} lastPage={list?.last_page||1} onChange={setPage}/></Card>
{detail&&<Modal title={`Order #${detail.order_number||detail.id}`} onClose={()=>setDetail(null)}><div className="detail-stack">
 <div className="form-grid"><Card><div className="metric-label">Customer</div><b>{detail.customer?.name||'Guest/customer'}</b><div className="muted">{detail.customer?.phone||'—'}<br/>{detail.customer?.email||'—'}</div></Card><Card><div className="metric-label">Order value</div><b>{money(detail.grand_total??detail.total,detail.currency||'INR')}</b><div className="muted">{dateTime(detail.created_at)}</div></Card></div>
 <div className="form-grid"><Card><div className="card-title">Delivery address</div><AddressBlock a={detail.shipping_address}/></Card><Card><div className="card-title">Billing address</div><AddressBlock a={detail.billing_address||detail.shipping_address}/></Card></div>
 <div className="card"><div className="card-title">Status & internal operations</div><select className="wide-control" value={nextStatus} disabled={statusLocked} onChange={e=>setNextStatus(e.target.value)}>{statuses.filter(Boolean).map(s=><option key={s}>{s}</option>)}</select><textarea className="wide-control note" disabled={statusLocked} placeholder={statusLocked?'Order is in a terminal state':'Internal note (optional)'} value={note} onChange={e=>setNote(e.target.value)}/><div className="form-actions"><Button className="primary" disabled={busy||statusLocked||nextStatus===detail.status} onClick={transition}>{busy?'Updating…':'Update status'}</Button></div></div>
 <div className="card"><div className="card-title">Items</div>{detail.items?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>SKU</th><th>Qty</th><th>Unit</th><th>Subtotal</th></tr></thead><tbody>{detail.items.map((i,n)=><tr key={String(i.id??n)}><td>{i.name||'—'}</td><td>{i.sku||'—'}</td><td>{i.quantity}</td><td>{money(i.unit_price,detail.currency||'INR')}</td><td>{money(i.subtotal,detail.currency||'INR')}</td></tr>)}</tbody></table></div>:<div className="muted">No item detail returned.</div>}</div>
 <div className="form-grid"><Card><div className="card-title">Payment</div><Badge>{titleCase(detail.payment?.status||'unknown')}</Badge><p className="muted">{detail.payment?.method||detail.payment?.provider||'—'} · {money(detail.payment?.amount??detail.grand_total??detail.total,detail.currency||'INR')}</p><p className="muted">Provider payment: {detail.payment?.provider_payment_id||'—'}</p></Card><Card><div className="card-title">Shipment</div><Badge>{titleCase(detail.shipment?.status||'not created')}</Badge><p className="muted">{detail.shipment?.courier||detail.shipment?.provider||'—'} · AWB {detail.shipment?.awb||'—'}</p><p className="muted">Tracking {detail.shipment?.tracking_number||'—'}</p><div className="form-actions">{!detail.shipment?<Button disabled={busy||shipmentCreateBlocked} onClick={()=>shipmentAction('create')}>Create shipment</Button>:<><Button disabled={busy} onClick={()=>shipmentAction('refresh')}>Refresh tracking</Button><Button disabled={busy||shipmentCancelBlocked} onClick={()=>shipmentAction('cancel')}>Cancel shipment</Button></>}</div>{shipmentCreateBlocked&&<div className="muted">Shipment creation is unavailable for this order state.</div>}</Card></div>
 <div className="card"><div className="card-title">Status timeline</div>{(detail.statusHistory||detail.status_history)?.length?<div className="quick">{(detail.statusHistory||detail.status_history)!.map((h,n)=><div key={String(h.id??n)}><b>{titleCase(h.to_status||'—')}</b><span>{h.from_status?`${titleCase(h.from_status)} → `:''}{dateTime(h.created_at)}{h.note?` · ${h.note}`:''}</span></div>)}</div>:<div className="muted">No status history returned.</div>}</div>
 <div className="card"><div className="card-title">Return</div><ReturnBlock value={detail.return}/></div>
 </div></Modal>}</section>}
