'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {money,apiMessage} from '@/lib/format';
import {PageHeader,Card,Button,ErrorState,Loading,Empty} from '@/components/ui';

type Tx={id?:string|number;status?:string;amount?:number|string;currency?:string;provider?:string;order_number?:string;created_at?:string};
type Page={data:Tx[]};
const statuses=['paid','failed','refunded','pending','cancelled'];
export default function FinanceDashboard(){const[rows,setRows]=useState<Tx[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');async function load(){setLoading(true);setError('');try{const r=await api<any>('/admin/payments/transactions?per_page=100');const d=r.data?.transactions??r.data?.data??r.data;setRows(Array.isArray(d)?d:[])}catch(e){setError(apiMessage(e,'Unable to load finance data'))}finally{setLoading(false)}}useEffect(()=>{load()},[]);const m=useMemo(()=>({paid:rows.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount||0),0),refunded:rows.filter(x=>x.status==='refunded').reduce((s,x)=>s+Number(x.amount||0),0),failed:rows.filter(x=>x.status==='failed').length,pending:rows.filter(x=>['pending','created','authorized'].includes(String(x.status))).length}),[rows]);const counts=useMemo(()=>statuses.map(s=>({s,n:rows.filter(x=>x.status===s).length})),[rows]);return <section className="content"><PageHeader title="Finance Command Center" description="Payment reconciliation and financial operational visibility from PriyasaCore." action={<Button onClick={load} disabled={loading}>Refresh</Button>}/>{error&&<ErrorState error={error} onRetry={load}/>} {loading?<Loading/>:<><div className="metrics-grid"><Card><div className="metric-label">Captured / paid</div><div className="metric-value">{money(m.paid)}</div></Card><Card><div className="metric-label">Refunded</div><div className="metric-value">{money(m.refunded)}</div></Card><Card><div className="metric-label">Failed transactions</div><div className="metric-value">{m.failed}</div></Card><Card><div className="metric-label">Pending / authorized</div><div className="metric-value">{m.pending}</div></Card></div><Card><h2>Transaction state distribution</h2>{rows.length?<div className="metrics-grid">{counts.map(x=><div key={x.s} className="card"><div className="metric-label">{x.s}</div><div className="metric-value">{x.n}</div></div>)}</div>:<Empty title="No payment transactions" text="PriyasaCore returned no transaction records for the current feed."/>}</Card><Card><div className="section-head"><div><h2>Reconciliation workflow</h2><p>Gateway transaction → order → payment state → refund state</p></div><Button onClick={()=>window.location.assign('/finance/transactions')}>Open reconciliation</Button></div><p className="muted">This dashboard is read-only. Refunds, settlement actions and gateway mutations are deliberately kept behind explicit Core endpoints rather than guessed client routes.</p></Card></>}</section>}
