'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {api} from '@/lib/api';
import {Button} from '@/components/ui';

type OtpResponse={request_id?:string;requestId?:string;expires_in?:number;retry_after?:number};
type VerifyResponse={token?:string;token_type?:string;user?:{id?:string|number;name?:string;email?:string;role?:string}};

export default function Login(){
 const [email,setEmail]=useState('');const [otp,setOtp]=useState('');const [requestId,setRequestId]=useState('');const [sent,setSent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [seconds,setSeconds]=useState(0);const router=useRouter();
 useEffect(()=>{if(!seconds)return;const timer=window.setInterval(()=>setSeconds(value=>Math.max(0,value-1)),1000);return()=>window.clearInterval(timer)},[seconds]);
 async function sendOtp(){const normalized=email.trim().toLowerCase();if(!normalized){setError('Enter your administrator email.');return}setBusy(true);setError('');try{const response=await api<OtpResponse>('/admin/auth/send-otp',{method:'POST',body:JSON.stringify({email:normalized})});const data=response.data||response;const id=data.request_id||data.requestId;setSeconds(Number(data.retry_after||60));if(!id){setSent(false);setRequestId('');setOtp('');setError('If this email belongs to an authorized PRIYASA administrator, a verification code will be sent shortly.');return}setRequestId(id);setSent(true);setOtp('')}catch(err){setError(err instanceof Error?err.message:'Unable to send OTP. Please try again.')}finally{setBusy(false)}}
 async function verifyOtp(){if(!requestId){setError('Your OTP session has expired. Please request a new code.');return}if(otp.length!==6){setError('Enter the 6-digit OTP.');return}setBusy(true);setError('');try{const response=await api<VerifyResponse>('/admin/auth/verify-otp',{method:'POST',body:JSON.stringify({email:email.trim().toLowerCase(),otp,request_id:requestId})});const data=response.data||response;if(!data.token)throw new Error('Login succeeded but no admin session token was returned.');localStorage.setItem('priyasa_admin_token',data.token);localStorage.setItem('priyasa_admin_user',JSON.stringify({id:data.user?.id,name:data.user?.name,email:data.user?.email,role:data.user?.role}));router.replace('/');router.refresh()}catch(err){setError(err instanceof Error?err.message:'Invalid or expired OTP. Please try again.')}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();if(sent)await verifyOtp();else await sendOtp()}
 function changeEmail(){setSent(false);setRequestId('');setOtp('');setSeconds(0);setError('')}
 return <main className="login-page"><div className="login-card"><div className="login-brand">PRIYASA <span>✦</span></div><h1>Admin portal</h1><p>Secure access to your commerce operations.</p><form onSubmit={submit}>{!sent?<label>Administrator email<input autoFocus type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@priyasa.com" required/></label>:<><label>One-time password<input autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder="••••••" required/></label><div className="form-actions" style={{justifyContent:'space-between'}}><button type="button" className="text-button" onClick={changeEmail} disabled={busy}>Change email</button><button type="button" className="text-button" disabled={busy||seconds>0} onClick={sendOtp}>{seconds>0?`Resend in ${seconds}s`:'Resend OTP'}</button></div></>}{error&&<div className="form-error" role="alert">{error}</div>}<Button className="primary-btn" disabled={busy||(!sent?email.trim().length===0:otp.length!==6)}>{busy?'Please wait…':sent?'Verify & continue':'Send OTP'}</Button></form><small>Only authorized PRIYASA administrators can sign in. OTPs are verified server-side and never stored in the browser.</small></div></main>
}
