'use client';

import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Activity,CheckCircle2,KeyRound,RefreshCw,Sparkles,Save,ShieldCheck} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Badge,Button,Card,ErrorState,Loading,PageHeader} from '@/components/ui';

type Provider={id:number;key:string;name:string;driver:string;model:string|null;enabled:boolean;configured:boolean;priority:number;base_url:string|null;timeout_seconds:number;max_retries:number};
type Health={enabled:number;configured:number;providers:Array<{key:string;enabled:boolean;configured:boolean;model:string|null}>};
type SectionResult={generation_id:number;content:Record<string,unknown>;provider?:string;model?:string};
const FIELDS=['title','short_description','description','meta_title','meta_description','slug','tags','image_alt_text'];

export default function AIPage(){
 const params=useSearchParams();
 const productId=params.get('product')||'';
 const [providers,setProviders]=useState<Provider[]>([]),[health,setHealth]=useState<Health|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [draft,setDraft]=useState<Record<number,Partial<Provider>>>({});
 const [saving,setSaving]=useState<number|null>(null),[instructions,setInstructions]=useState(''),[sections,setSections]=useState<string[]>(['content','seo']);
 const [generating,setGenerating]=useState(false),[results,setResults]=useState<Record<string,SectionResult>>({}),[selected,setSelected]=useState<Record<number,string[]>>({}),[applying,setApplying]=useState<number|null>(null),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [p,h]=await Promise.all([api<{providers:Provider[]}>('/admin/ai/providers'),api<Health>('/admin/ai/health')]);const rows=p.data?.providers||[];setProviders(rows);setHealth(h.data||null);setDraft(Object.fromEntries(rows.map(x=>[x.id,{}])))}catch(e){setError(apiMessage(e,'Unable to load AI configuration'))}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const configured=useMemo(()=>providers.filter(p=>p.enabled&&p.configured).length,[providers]);
 async function saveProvider(p:Provider){setSaving(p.id);setMessage('');setError('');try{const d=draft[p.id]||{};await api(`/admin/ai/providers/${p.id}`,{method:'PATCH',body:JSON.stringify(d)});setMessage(`${p.name} configuration saved.`);await load()}catch(e){setError(apiMessage(e,'Unable to save provider'))}finally{setSaving(null)}}
 async function generate(){if(!productId){setError('Open AI Studio from a product edit page, or add ?product=<product-id> to this URL.');return}setGenerating(true);setError('');setMessage('');try{const r=await api<{product_id:number;sections:Record<string,SectionResult>}>(`/admin/ai/products/${productId}/generate`,{method:'POST',body:JSON.stringify({sections,instructions:instructions.trim()||undefined})});setResults(r.data?.sections||{});setMessage('AI draft generated. Review fields before applying.')}catch(e){setError(apiMessage(e,'AI product generation failed'))}finally{setGenerating(false)}}
 async function apply(section:string){const result=results[section];if(!result)return;const fields=selected[result.generation_id]||[];if(!fields.length){setError('Select at least one generated field to apply.');return}setApplying(result.generation_id);setError('');try{await api(`/admin/ai/products/${productId}/apply`,{method:'POST',body:JSON.stringify({generation_id:result.generation_id,fields})});setMessage(`Applied ${fields.length} field${fields.length===1?'':'s'} from ${section} draft.`);setResults(v=>({...v,[section]:{...v[section]}}))}catch(e){setError(apiMessage(e,'Unable to apply AI draft'))}finally{setApplying(null)}}
 function toggle(id:number,field:string){setSelected(v=>{const current=v[id]||[];return {...v,[id]:current.includes(field)?current.filter(x=>x!==field):[...current,field]}})}
 return <main className="space-y-6">
  <PageHeader title="AI Studio" description="Configure AI providers and generate human-reviewed product content. AI never publishes a product automatically." action={<Button onClick={load}><RefreshCw size={14}/> Refresh</Button>}/>
  {error&&<ErrorState error={error} onRetry={load}/>} {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}
  {loading?<Loading/>:<>
   <div className="grid gap-4 md:grid-cols-3"><Card><span className="text-sm text-zinc-500">Enabled providers</span><strong className="mt-2 block text-2xl">{health?.enabled??0}</strong></Card><Card><span className="text-sm text-zinc-500">Configured & enabled</span><strong className="mt-2 block text-2xl">{configured}</strong></Card><Card><span className="text-sm text-zinc-500">Fallback chain</span><strong className="mt-2 block text-2xl">{providers.length>1?'Ready':'Needs providers'}</strong></Card></div>
   <Card><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Provider health</h2><p className="mt-1 text-sm text-zinc-500">Secrets are never returned by the API.</p></div><Activity size={20}/></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{providers.map(p=><div key={p.id} className="rounded-xl border p-4"><div className="flex items-center justify-between"><b>{p.name}</b><Badge>{p.enabled?'Enabled':'Disabled'}</Badge></div><div className="mt-3 space-y-1 text-sm text-zinc-500"><div>Model: {p.model||'—'}</div><div>Priority: {p.priority}</div><div className="flex items-center gap-1">{p.configured?<CheckCircle2 size={14}/>:'⚠'} {p.configured?'API key configured':'API key missing'}</div></div></div>)}</div></Card>
   <Card><div className="mb-5"><h2 className="font-semibold">Provider settings</h2><p className="mt-1 text-sm text-zinc-500">Gemini, OpenRouter, Groq and OpenAI can participate in the ordered fallback chain.</p></div><div className="space-y-4">{providers.map(p=><div key={p.id} className="rounded-xl border p-4"><div className="mb-4 flex items-center justify-between"><div><b>{p.name}</b><div className="text-xs text-zinc-500">{p.driver} · priority {p.priority}</div></div><KeyRound size={17}/></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-5"><label>API key<input className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" type="password" placeholder={p.configured?'Configured — enter to replace':'Enter API key'} onChange={e=>setDraft(v=>({...v,[p.id]:{...v[p.id],api_key:e.target.value}}))}/></label><label>Model<input className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" value={draft[p.id]?.model??p.model??''} onChange={e=>setDraft(v=>({...v,[p.id]:{...v[p.id],model:e.target.value}}))}/></label><label>Priority<input className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" type="number" min="1" value={draft[p.id]?.priority??p.priority} onChange={e=>setDraft(v=>({...v,[p.id]:{...v[p.id],priority:Number(e.target.value)}}))}/></label><label>Timeout (sec)<input className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" type="number" min="5" max="180" value={draft[p.id]?.timeout_seconds??p.timeout_seconds} onChange={e=>setDraft(v=>({...v,[p.id]:{...v[p.id],timeout_seconds:Number(e.target.value)}}))}/></label><label>Retries<input className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" type="number" min="0" max="3" value={draft[p.id]?.max_retries??p.max_retries} onChange={e=>setDraft(v=>({...v,[p.id]:{...v[p.id],max_retries:Number(e.target.value)}}))}/></label></div><div className="mt-3 flex items-center justify-between"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(draft[p.id]?.enabled??p.enabled)} onChange={e=>setDraft(v=>({...v,[p.id]:{...v[p.id],enabled:e.target.checked}}))}/><ShieldCheck size={15}/> Enabled</label><Button className="primary" disabled={saving===p.id} onClick={()=>saveProvider(p)}><Save size={14}/>{saving===p.id?'Saving…':'Save provider'}</Button></div></div>)}</div></Card>
   <Card><div className="mb-5"><h2 className="font-semibold">Product AI Studio</h2><p className="mt-1 text-sm text-zinc-500">Generate a draft, inspect it, select fields, then explicitly apply them.</p></div><div className="grid gap-4 md:grid-cols-[220px_1fr]"><label>Product ID<input className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" value={productId} readOnly placeholder="From product editor"/></label><div><div className="flex flex-wrap gap-3">{[['content','Content: description'],['seo','SEO: title/meta/slug/tags']] .map(([id,label])=><label key={id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sections.includes(id)} onChange={()=>setSections(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>{label}</label>)}</div><textarea className="mt-3 min-h-24 w-full rounded-lg border p-3 text-sm" placeholder="Optional instructions, e.g. premium festive ethnic-wear tone; do not invent fabric claims." value={instructions} onChange={e=>setInstructions(e.target.value)}/><Button className="primary mt-3" disabled={generating||!sections.length} onClick={generate}><Sparkles size={15}/>{generating?'Generating…':'Generate AI draft'}</Button></div></div></Card>
   {Object.entries(results).map(([section,result])=><Card key={section}><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">{section==='content'?'Content draft':'SEO draft'}</h2><p className="text-xs text-zinc-500">Generation #{result.generation_id} · {result.provider||'provider'} · {result.model||'model'}</p></div><Badge>Human approval required</Badge></div><div className="grid gap-3 md:grid-cols-2">{FIELDS.filter(f=>Object.prototype.hasOwnProperty.call(result.content,f)).map(field=><label key={field} className="rounded-xl border p-3"><span className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={(selected[result.generation_id]||[]).includes(field)} onChange={()=>toggle(result.generation_id,field)}/>{field}</span><textarea className="mt-2 min-h-24 w-full rounded-lg border p-2 text-sm" value={Array.isArray(result.content[field])?result.content[field].join(', '):String(result.content[field]??'')} readOnly/></label>)}</div><div className="mt-4 flex justify-end"><Button className="primary" disabled={applying===result.generation_id} onClick={()=>apply(section)}>{applying===result.generation_id?'Applying…':'Apply selected fields'}</Button></div></Card>)}
  </>}
 </main>
}
