'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Edit3,Plus,Power,Trash2} from 'lucide-react';
import {api} from '@/lib/api';
import {money,dateTime,titleCase,apiMessage} from '@/lib/format';
import {Badge,Button,Card,DataToolbar,ErrorState,Loading,Modal,PageHeader,Pagination} from '@/components/ui';

type Coupon={id:number|string;code:string;type:'percentage'|'fixed';value:number|string;minimum_cart_value?:number|string;maximum_discount?:number|string|null;usage_limit?:number|null;usage_count:number;per_customer_limit?:number|null;starts_at?:string|null;ends_at?:string|null;is_active:boolean;redemptions_count?:number};
type Page={data:Coupon[];current_page:number;last_page:number;total:number;per_page:number};
const blank={code:'',type:'percentage',value:'',minimum_cart_value:'0',maximum_discount:'',usage_limit:'',per_customer_limit:'1',starts_at:'',ends_at:'',is_active:true};
export default function Promotions(){const [list,setList]=useState<Page|null>(null);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [edit,setEdit]=useState<Coupon|null>(null);const [form,setForm]=useState<any>(blank);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
async function load(){setError('');try{const p=new URLSearchParams({page:String(page),per_page:'50'});if(q)p.set('search',q);if(status)p.set('status',status);const r=await api<Page>(`/admin/promotions?${p}`);setList(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load promotions'))}}
useEffect(()=>{load()},[page,status]);useEffect(()=>{const t=setTimeout(()=>{setPage(1);load()},350);return()=>clearTimeout(t)},[q]);
function start(c?:Coupon){setEdit(c||null);setForm(c?{code:c.code,type:c.type,value:c.value,minimum_cart_value:c.minimum_cart_value??0,maximum_discount:c.maximum_discount??'',usage_limit:c.usage_limit??'',per_customer_limit:c.per_customer_limit??'',starts_at:c.starts_at?c.starts_at.slice(0,16):'',ends_at:c.ends_at?c.ends_at.slice(0,16):'',is_active:c.is_active}:blank)}
async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');const body={code:String(form.code).trim().toUpperCase(),type:form.type,value:Number(form.value),minimum_cart_value:Number(form.minimum_cart_value||0),maximum_discount:form.maximum_discount===''?null:Number(form.maximum_discount),usage_limit:form.usage_limit===''?null:Number(form.usage_limit),per_customer_limit:form.per_customer_limit===''?null:Number(form.per_customer_limit),starts_at:form.starts_at||null,ends_at:form.ends_at||null,is_active:Boolean(form.is_active)};try{await api(`/admin/promotions${edit?`/${edit.id}`:''}`,{method:edit?'PUT':'POST',body:JSON.stringify(body)});setEdit(null);await load()}catch(e){setError(apiMessage(e,'Unable to save promotion'))}finally{setBusy(false)}}
async function toggle(c:Coupon){try{await api(`/admin/promotions/${c.id}/toggle`,{method:'POST',body:JSON.stringify({is_active:!c.is_active})});await load()}catch(e){setError(apiMessage(e,'Unable to change promotion status'))}}
async function remove(c:Coupon){if(!confirm(`Delete/deactivate ${c.code}?`))return;try{await api(`/admin/promotions/${c.id}`,{method:'DELETE'});await load()}catch(e){setError(apiMessage(e,'Unable to remove promotion'))}}
return <section className="content"><PageHeader title="Promotions" description="Manage discount codes, usage limits and campaign validity." action={<Button className="primary" onClick={()=>start()}><Plus size={15}/> New coupon</Button>}/><Card><DataToolbar value={q} onChange={v=>{setPage(1);setQ(v)}} placeholder="Search coupon code…"><select className="filter-select" value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></DataToolbar>{error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:list?.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Discount</th><th>Cart minimum</th><th>Usage</th><th>Validity</th><th>Status</th><th/></tr></thead><tbody>{list.data.map(c=><tr key={String(c.id)}><td><b>{c.code}</b></td><td>{c.type==='percentage'?`${c.value}%`:`${money(c.value)}`}{c.maximum_discount!=null&&<div className="muted">Cap {money(c.maximum_discount)}</div>}</td><td>{money(c.minimum_cart_value)}</td><td>{c.usage_count}{c.usage_limit!=null?` / ${c.usage_limit}`:' / ∞'}<div className="muted">{c.per_customer_limit?`${c.per_customer_limit}/customer`:''}</div></td><td>{c.starts_at||c.ends_at?<>{dateTime(c.starts_at||undefined)}<br/>{c.ends_at?`to ${dateTime(c.ends_at)}`:''}</>:'Always'}</td><td><Badge>{c.is_active?'Active':'Inactive'}</Badge></td><td><Button onClick={()=>start(c)}><Edit3 size={14}/></Button><Button onClick={()=>toggle(c)}><Power size={14}/></Button><Button onClick={()=>remove(c)}><Trash2 size={14}/></Button></td></tr>)}</tbody></table></div>:<div className="empty"><strong>No promotions</strong><span>Create your first coupon to offer discounts at checkout.</span></div>}<Pagination page={list?.current_page||1} lastPage={list?.last_page||1} onChange={setPage}/></Card>{edit!==undefined&&edit!==null&&<Modal title="Edit coupon" onClose={()=>setEdit(null)}><CouponForm form={form} setForm={setForm} busy={busy} save={save} cancel={()=>setEdit(null)}/></Modal>}{edit===null&&<Modal title="New coupon" onClose={()=>setEdit(undefined as any)}><CouponForm form={form} setForm={setForm} busy={busy} save={save} cancel={()=>setEdit(undefined as any)}/></Modal>}</section>}
function CouponForm({form,setForm,busy,save,cancel}:{form:any;setForm:(v:any)=>void;busy:boolean;save:(e:FormEvent)=>void;cancel:()=>void}){const fields=[['code','Coupon code','text'],['value','Discount value','number'],['minimum_cart_value','Minimum cart value','number'],['maximum_discount','Maximum discount (optional)','number'],['usage_limit','Total usage limit (optional)','number'],['per_customer_limit','Per-customer limit (optional)','number']];return <form className="form" onSubmit={save}><div className="form-grid">{fields.map(([k,l,t])=><label key={k}>{l}<input required={['code','value'].includes(k)} type={t} min="0" step={k==='code'?undefined:'0.01'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Discount type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Starts at<input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Ends at<input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label></div><label className="check"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active at checkout</label><div className="form-actions"><Button type="button" onClick={cancel}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Saving…':'Save coupon'}</Button></div></form>}
