'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {apiMessage,dateTime,titleCase} from '@/lib/format';
import {PageHeader,Card,DataToolbar,Button,Badge,Loading,ErrorState,Empty} from '@/components/ui';
type Audit={id:number|string;action:string;actor_type?:string|null;actor_id?:number|string|null;entity_type?:string|null;entity_id?:number|string|null;created_at?:string;data?:Record<string,unknown>|null};
type Page={data:Audit[];current_page:number;last_page:number;total:number};
const risky=(a:Audit)=>/delete|remove|deactivate|block|refund|cancel|password|role|permission|credential|disconnect|failed|forbidden/i.test(`${a.action} ${a.entity_type||''} ${JSON.stringify(a.data||{})}`);
export default function Security(){const[items,setItems]=useState<Audit[]>([]),[q,setQ]=useState(''),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState('');
async function load(){setLoading(true);setError('');try{const r=await api<{audit_logs:Page}>(`/admin/audit-logs?page=${page}&per_page=100&search=${encodeURIComponent(q)}`);setItems(r.data?.audit_logs?.data||[])}catch(e){setError(apiMessage(e,'Unable to load security audit events'))}finally{setLoading(false)}}
useEffect(()=>{load()},[page]);useEffect(()=>{const t=setTimeout(()=>{setPage(1);load()},400);return()=>clearTimeout(t)},[q]);
const riskyEvents=useMemo(()=>items.filter(risky),[items]);
return <section className="content"><PageHeader title="Security & Audit" description="Security-sensitive administrative activity from the PriyasaCore audit stream." action={<Button onClick={load} disabled={loading}>Refresh</Button>}/>{error&&<ErrorState error={error} onRetry={load}/>}<div className="stats-grid"><Card><div className="metric-label">Audit events</div><div className="metric">{items.length}</div><div className="muted">Current event window</div></Card><Card><div className="metric-label">Sensitive events</div><div className="metric">{riskyEvents.length}</div><div className="muted">Access / account / commerce controls</div></Card><Card><div className="metric-label">Actors</div><div className="metric">{new Set(items.map(a=>`${a.actor_type||'unknown'}:${a.actor_id??'system'}`)).size}</div><div className="muted">Unique actor references</div></Card></div><Card><DataToolbar value={q} onChange={setQ} placeholder="Search action, actor, entity or payload…"/>{loading?<Loading/>:items.length?<div className="table-wrap"><table className="table"><thead><tr><th>Risk</th><th>Action</th><th>Actor</th><th>Entity</th><th>Payload</th><th>Time</th></tr></thead><tbody>{items.map(a=><tr key={String(a.id)}><td><Badge>{risky(a)?'Sensitive':'Normal'}</Badge></td><td><b>{titleCase(a.action)}</b></td><td>{titleCase(a.actor_type||'System')} {a.actor_id?`#${a.actor_id}`:''}</td><td>{a.entity_type?`${titleCase(a.entity_type)} #${a.entity_id??'—'}`:'—'}</td><td><code>{JSON.stringify(a.data||{}).slice(0,260)}</code></td><td>{dateTime(a.created_at)}</td></tr>)}</tbody></table></div>:<Empty title="No audit events" text="No security events were returned by PriyasaCore for the current filter."/>}</Card><Card><h2>Security boundary</h2><p className="muted">This workspace is intentionally read-only. Administrator roles, provider secrets and authorization policy remain server-controlled; the UI does not expose credentials or bypass access checks.</p></Card></section>}
