'use client';
import {useEffect,useMemo,useState} from 'react';
import {Plus,Edit3,Power} from 'lucide-react';
import {api} from '@/lib/api';
import {PageHeader,Button,Card,DataToolbar,Modal,ErrorState,Loading,Badge,Empty} from '@/components/ui';
import {Paginated} from '@/lib/types';
type Category={id:number|string;parent_id?:number|string|null;name:string;slug:string;description?:string;image_url?:string|null;sort_order?:number;is_active:boolean;products_count?:number};
const blank={name:'',slug:'',description:'',image_url:'',sort_order:'0',parent_id:'',is_active:true};
export default function Categories(){const [list,setList]=useState<Paginated<Category>|null>(null);const [q,setQ]=useState('');const [page,setPage]=useState(1);const [open,setOpen]=useState(false);const [edit,setEdit]=useState<Category|null>(null);const [form,setForm]=useState<any>(blank);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
async function load(){setError('');try{const r=await api<Paginated<Category>>(`/admin/catalog/categories?page=${page}&per_page=50&search=${encodeURIComponent(q)}`);setList(r.data||null)}catch(e){setError(e instanceof Error?e.message:'Request failed')}}useEffect(()=>{load()},[page,q]);
const parents=useMemo(()=>list?.data?.filter(c=>c.is_active&&(!edit||String(c.id)!==String(edit.id)))||[],[list,edit]);
function start(c?:Category){setEdit(c||null);setForm(c?{name:c.name,slug:c.slug,description:c.description||'',image_url:c.image_url||'',sort_order:String(c.sort_order??0),parent_id:c.parent_id??'',is_active:c.is_active}:blank);setOpen(true)}
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={...form,sort_order:Number(form.sort_order||0),parent_id:form.parent_id||null};await api(edit?`/admin/catalog/categories/${edit.id}`:'/admin/catalog/categories',{method:edit?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
async function deactivate(c:Category){if(!confirm(`Deactivate “${c.name}”?`))return;setError('');try{await api(`/admin/catalog/categories/${c.id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to deactivate category')}}
return <section className="content"><PageHeader title="Categories" description="Manage the catalog hierarchy and merchandising order." action={<Button className="primary" onClick={()=>start()}><Plus size={15}/> Add category</Button>}/>{error&&<ErrorState error={error} onRetry={load}/>}<Card><DataToolbar value={q} onChange={v=>{setPage(1);setQ(v)}} placeholder="Search categories…"/>{!list&&!error?<Loading/>:list?.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Category</th><th>Parent</th><th>Products</th><th>Order</th><th>Status</th><th/></tr></thead><tbody>{list.data.map(c=><tr key={String(c.id)}><td><b>{c.name}</b><div style={{color:'#999',marginTop:3}}>{c.slug}</div></td><td>{c.parent_id?list.data.find(p=>String(p.id)===String(c.parent_id))?.name||`#${c.parent_id}`:'Root'}</td><td>{c.products_count??0}</td><td>{c.sort_order??0}</td><td><Badge>{c.is_active?'Active':'Inactive'}</Badge></td><td><Button onClick={()=>start(c)} aria-label={`Edit ${c.name}`}><Edit3 size={14}/></Button>{c.is_active&&<Button onClick={()=>deactivate(c)} aria-label={`Deactivate ${c.name}`}><Power size={14}/></Button>}</td></tr>)}</tbody></table></div>:<Empty title="No categories" text="Create your first catalog category."/>}<div style={{paddingTop:16}}><small style={{color:'#777'}}>Showing {list?.data?.length||0} categories · {list?.total||0} total</small></div></Card>{open&&<Modal title={edit?'Edit category':'Add category'} onClose={()=>setOpen(false)}><form className="form" onSubmit={save}><div className="form-grid"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug<input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/\s+/g,'-')})}/></label><label>Parent<select value={form.parent_id} onChange={e=>setForm({...form,parent_id:e.target.value})}><option value="">Root category</option>{parents.map(p=><option key={String(p.id)} value={String(p.id)}>{p.name}</option>)}</select></label><label>Sort order<input type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label></div><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Image URL<input type="url" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="https://…"/></label>{edit&&<label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label>}<div className="form-actions"><Button type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Saving…':edit?'Save changes':'Create category'}</Button></div></form></Modal>}</section>}
