'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,RefreshCw,Truck,PackageCheck,XCircle} from 'lucide-react';
import {useRouter,useParams} from 'next/navigation';
import {api} from '@/lib/api';
import {Order} from '@/lib/types';
import {money,dateTime,titleCase,apiMessage} from '@/lib/format';
import {PageHeader,Card,Button,Badge,Loading,ErrorState} from '@/components/ui';

const statuses=['pending_payment','payment_failed','confirmed','processing','packed','shipped','in_transit','out_for_delivery','delivered','return_requested','returned','refunded','cancelled'];
const terminal=new Set(['refunded','cancelled']);
const shipmentBlocked=new Set(['pending_payment','payment_failed','return_requested','returned','refunded','cancelled']);
function Address({a}:{a:Order['shipping_address']}){return a?<div className="muted">{a.recipient_name} · {a.phone}<br/>{a.line1}{a.line2?`, ${a.line2}`:''}{a.area?`, ${a.area}`:''}<br/>{a.city}, {a.state} {a.postal_code}</div>:<div className="muted">No address returned.</div>}
export default function OrderDetail(){
 const router=useRouter();const params=useParams<{id:string}>();const id=params.id;
 const [order,setOrder]=useState<Order|null>(null),[next,setNext]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setError('');try{const r=await api<Order>(`/admin/orders/${encodeURIComponent(id)}`);setOrder(r.data||null);setNext(r.data?.status||'')}catch(e){setError(apiMessage(e,'Unable to load order'))}}
 useEffect(()=>{if(id)load()},[id]);
 async function statusUpdate(){if(!order||!next||next===order.status||terminal.has(order.status))return;if(next==='cancelled'&&!confirm('Cancel this order? Core will enforce cancellation eligibility.'))return;if(next==='refunded'&&!confirm('Confirm the payment-provider refund is complete before marking the order refunded.'))return;setBusy(true);setError('');try{const r=await api<Order>(`/admin/orders/${order.id}/status`,{method:'POST',body:JSON.stringify({status:next,note:note||undefined})});setOrder(r.data||{...order,status:next});setNote('');await load()}catch(e){setError(apiMessage(e,'Status update failed'))}finally{setBusy(false)}}
 async function shipment(action:'create'|'refresh'|'cancel'){if(!order)return;if(action==='create'&&shipmentBlocked.has(order.status))return;if(action==='cancel'&&!confirm('Cancel this shipment?'))return;setBusy(true);setError('');try{if(action==='create')await api(`/admin/orders/${order.id}/shipment`,{method:'POST',body:JSON.stringify({provider:'shiprocket'})});else if(order.shipment)await api(`/admin/shipments/${order.shipment.id}${action==='cancel'?'/cancel':''}`,{method:'POST'});await load()}catch(e){setError(apiMessage(e,'Shipping operation failed'))}finally{setBusy(false)}}
 if(error&&!order)return <section className="content"><PageHeader title="Order" action={<Button onClick={()=>router.push('/orders')}><ArrowLeft size={14}/> Orders</Button>}/><ErrorState error={error} onRetry={load}/></section>;
 if(!order)return <section className="content"><Loading/></section>;
 const locked=terminal.has(order.status);
 return <section className="content"><PageHeader title={`Order #${order.order_number||order.id}`} description="Full operational workspace for payment, fulfillment, delivery and post-order state." action={<div className="form-actions"><Button onClick={()=>router.push('/orders')}><ArrowLeft size={14}/> Orders</Button><Button onClick={load} disabled={busy}><RefreshCw size={14}/> Refresh</Button></div>}/>
 {error&&<ErrorState error={error} onRetry={load}/>}<div className="stats-grid"><Card><span>Status</span><strong>{titleCase(order.status)}</strong><small>{dateTime(order.created_at)}</small></Card><Card><span>Order value</span><strong>{money(order.grand_total??order.total,order.currency||'INR')}</strong><small>{order.items?.length||0} line items</small></Card><Card><span>Payment</span><strong>{titleCase(order.payment?.status||'unknown')}</strong><small>{titleCase(order.payment?.method||'—')}</small></Card><Card><span>Shipment</span><strong>{titleCase(order.shipment?.status||'not created')}</strong><small>{order.shipment?.awb||'No AWB'}</small></Card></div>
 <div className="form-grid"><Card><div className="card-title">Customer</div><b>{order.customer?.name||'Guest/customer'}</b><div className="muted">{order.customer?.phone||'—'}<br/>{order.customer?.email||'—'}</div></Card><Card><div className="card-title">Delivery address</div><Address a={order.shipping_address}/></Card><Card><div className="card-title">Billing address</div><Address a={order.billing_address||order.shipping_address}/></Card></div>
 <Card><div className="card-title">Order status</div><div className="form-grid"><label>Next state<select value={next} disabled={locked||busy} onChange={e=>setNext(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Internal note<textarea value={note} disabled={locked||busy} onChange={e=>setNote(e.target.value)} placeholder="Operational note…"/></label></div><div className="form-actions"><Button className="primary" disabled={locked||busy||next===order.status} onClick={statusUpdate}>{busy?'Saving…':'Update status'}</Button>{locked&&<span className="muted">Terminal order state.</span>}</div></Card>
 <Card><div className="card-title">Items</div>{order.items?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>SKU</th><th>Qty</th><th>Unit</th><th>Subtotal</th></tr></thead><tbody>{order.items.map((i,n)=><tr key={String(i.id??n)}><td>{i.name||'—'}</td><td>{i.sku||'—'}</td><td>{i.quantity}</td><td>{money(i.unit_price??0,order.currency||'INR')}</td><td>{money(i.subtotal??0,order.currency||'INR')}</td></tr>)}</tbody></table></div>:<div className="muted">No item detail returned.</div>}</Card>
 <div className="form-grid"><Card><div className="card-title">Payment</div><Badge>{titleCase(order.payment?.status||'unknown')}</Badge><p className="muted">{titleCase(order.payment?.provider||'—')} · {order.payment?.provider_order_id||'No provider order'}</p><p className="muted">{order.payment?.provider_payment_id||'No provider payment'}{order.payment?.paid_at?` · Paid ${dateTime(order.payment.paid_at)}`:''}</p></Card><Card><div className="card-title">Fulfillment</div><Badge>{titleCase(order.shipment?.status||'not created')}</Badge><p className="muted">{order.shipment?.courier||order.shipment?.provider||'—'} · AWB {order.shipment?.awb||'—'}<br/>Tracking {order.shipment?.tracking_number||'—'}</p><div className="form-actions">{!order.shipment?<Button disabled={busy||shipmentBlocked.has(order.status)} onClick={()=>shipment('create')}><Truck size={14}/> Create shipment</Button>:<><Button disabled={busy} onClick={()=>shipment('refresh')}><PackageCheck size={14}/> Refresh tracking</Button><Button disabled={busy||locked} onClick={()=>shipment('cancel')}><XCircle size={14}/> Cancel</Button></>}</div></Card></div>
 <Card><div className="card-title">Status timeline</div>{(order.statusHistory||order.status_history)?.length?<div className="quick">{(order.statusHistory||order.status_history)!.map((h,n)=><div key={String(h.id??n)}><b>{titleCase(h.to_status||'—')}</b><span>{h.from_status?`${titleCase(h.from_status)} → `:''}{dateTime(h.created_at)}{h.note?` · ${h.note}`:''}{h.actor?.name?` · ${h.actor.name}`:''}</span></div>)}</div>:<div className="muted">No status history returned.</div>}</Card>
 </section>
}
