'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {Card,PageHeader,DataToolbar,Button,Modal,Loading,ErrorState,Badge,Empty} from '@/components/ui';
import {dateTime,titleCase,apiMessage} from '@/lib/format';

type Exception={id?:string|number;type?:string;status?:string;reason?:string|null;message?:string|null;order_id?:string|number;order_number?:string;shipment_id?:string|number;awb?:string|null;tracking_number?:string|null;courier?:string|null;created_at?:string;updated_at?:string;attempts?:number;metadata?:Record<string,unknown>};
function normalize(v:any):Exception[]{const d=v?.data??v?.exceptions??v?.ndr;return Array.isArray(d)?d:(Array.isArray(d?.data)?d.data:[])}
const states=['','open','pending','resolved','closed'];
export default function ShippingExceptions(){
 const [rows,setRows]=useState<Exception[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Exception|null>(null);
 async function load(){setLoading(true);setError('');try{const p=new URLSearchParams({per_page:'100'});if(q)p.set('search',q);if(status)p.set('status',status);let r:any;try{r=await api<any>(`/admin/ndr?${p}`)}catch{r=await api<any>(`/admin/shipping/exceptions?${p}`)}setRows(normalize(r))}catch(e){setError(apiMessage(e,'Unable to load shipping exceptions'))}finally{setLoading(false)}}
 useEffect(()=>{load()},[status]);useEffect(()=>{const t=setTimeout(load,350);return()=>clearTimeout(t)},[q]);
 const openCount=useMemo(()=>rows.filter(x=>!['resolved','closed'].includes(x.status||'')).length,[rows]);
 return <section className="content"><PageHeader title="Shipping exceptions & NDR" description="Centralize delivery failures, NDR cases and courier exceptions without bypassing PriyasaCore."/><div className="grid" style={{marginBottom:16}}><Card><div className="metric-label">Cases loaded</div><div className="metric">{rows.length}</div></Card><Card><div className="metric-label">Open attention</div><div className="metric">{openCount}</div></Card><Card><div className="metric-label">Source</div><div className="metric">Core</div><div className="metric-label">Live API</div></Card></div><Card><DataToolbar value={q} onChange={setQ} placeholder="Search order, AWB, tracking, reason…"><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}>{states.map(s=><option key={s} value={s}>{s?titleCase(s):'All states'}</option>)}</select><Button onClick={load} disabled={loading}>Refresh</Button></DataToolbar>{error&&<ErrorState error={error} onRetry={load}/>} {loading?<Loading/>:rows.length?<div className="table-wrap"><table className="table"><thead><tr><th>Case</th><th>Order</th><th>Shipment</th><th>Courier</th><th>Reason</th><th>Attempts</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{rows.map((x,i)=><tr key={String(x.id||i)}><td><b>#{x.id||'—'}</b><div className="muted">{titleCase(x.type||'exception')}</div></td><td>#{x.order_number||x.order_id||'—'}</td><td>{x.awb||x.tracking_number||x.shipment_id||'—'}</td><td>{x.courier||'—'}</td><td>{x.reason||x.message||'—'}</td><td>{x.attempts??'—'}</td><td><Badge>{titleCase(x.status||'open')}</Badge></td><td>{dateTime(x.updated_at||x.created_at)}</td><td><Button onClick={()=>setSelected(x)}>Details</Button></td></tr>)}</tbody></table></div>:<Empty title="No shipping exceptions" text="No NDR/exception records are currently exposed by the Core API."/>}</Card>{selected&&<Modal title={`Shipping case #${selected.id||'—'}`} onClose={()=>setSelected(null)}><div className="detail-stack"><div className="form-grid"><Card><div className="metric-label">Order</div><b>#{selected.order_number||selected.order_id||'—'}</b><div className="muted">Shipment: {selected.shipment_id||'—'}</div></Card><Card><div className="metric-label">Status</div><Badge>{titleCase(selected.status||'open')}</Badge><div className="muted">Attempts: {selected.attempts??'—'}</div></Card></div><Card><div className="card-title">Exception</div><p>{selected.reason||selected.message||'No reason supplied.'}</p><div className="muted">AWB {selected.awb||'—'} · Tracking {selected.tracking_number||'—'} · Courier {selected.courier||'—'}</div></Card>{selected.metadata&&<pre style={{whiteSpace:'pre-wrap',maxHeight:320,overflow:'auto',fontSize:11}}>{JSON.stringify(selected.metadata,null,2)}</pre>}</div></Modal>}</section>
}