'use client';

import { useEffect, useMemo, useState } from 'react';
import { RefreshCw, CheckCircle2, AlertTriangle, PlugZap, Unplug, ShoppingBag, MessageCircle, Flame, Megaphone, ShieldCheck, LockKeyhole, ExternalLink } from 'lucide-react';
import { api } from '@/lib/api';
import { PageHeader, Card, Button, Loading, ErrorState, Modal } from '@/components/ui';

type Integration = { key:string; name:string; description:string; enabled?:boolean; status?:string; configured?:boolean; last_error?:string|null; error?:string|null; connected_at?:string|null; last_tested_at?:string|null };
type Definition = { key:string; name:string; icon:any; description:string; capabilities:string[]; authorization:string; external?:boolean };

const definitions:Definition[] = [
  {key:'meta',name:'Meta / Facebook & Instagram',icon:Megaphone,description:'Authorize Meta Business assets for Facebook, Instagram, catalog and marketing automation.',capabilities:['Facebook','Instagram','Ads','Catalog'],authorization:'Meta OAuth — no access token is entered here'},
  {key:'whatsapp',name:'WhatsApp Business',icon:MessageCircle,description:'Customer messaging and transactional order notifications through PriyasaCore.',capabilities:['Messages','Templates','Order updates','Webhooks'],authorization:'Server-managed Meta/WhatsApp credentials'},
  {key:'fcm',name:'Firebase Cloud Messaging',icon:Flame,description:'Push delivery for web, Android and future native Priyasa Store clients.',capabilities:['Web push','Android push','Order alerts'],authorization:'Server-managed Firebase service account'},
  {key:'woocommerce',name:'WooCommerce (External)',icon:ShoppingBag,external:true,description:'Optional external commerce adapter for migration, legacy synchronization or third-party catalog/order imports.',capabilities:['Import products','Import categories','Import orders'],authorization:'Server-managed WooCommerce REST credentials'},
];
const idempotency=()=>crypto.randomUUID();

export default function Integrations(){
 const[rows,setRows]=useState<Integration[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[selected,setSelected]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[confirmOpen,setConfirmOpen]=useState(false);const[syncing,setSyncing]=useState<string|null>(null);
 async function load(){setLoading(true);setError('');try{const[integrationResult,metaResult,wooResult]=await Promise.all([api<any>('/admin/integrations'),api<any>('/admin/integrations/meta/status').catch(()=>({data:null})),api<any>('/admin/integrations/woocommerce/status').catch(()=>({data:null}))]);const value=integrationResult.data;const base:Integration[]=(Array.isArray(value)?value:Array.isArray(value?.data)?value.data:[]).map((r:any)=>({key:String(r?.key||''),name:String(r?.name||r?.key||'Integration'),description:String(r?.description||''),enabled:r?.enabled,status:r?.status,configured:r?.configured,last_error:r?.last_error??null,error:r?.error??null,connected_at:r?.connected_at??null,last_tested_at:r?.last_tested_at??null}));const meta=metaResult.data;const woo=wooResult.data;const metaRow:Integration={key:'meta',name:'Meta / Facebook & Instagram',description:'Authorize Meta Business assets through OAuth.',enabled:Boolean(meta?.connected),status:meta?.connected?'connected':'disconnected',connected_at:meta?.connected_at||null};const existingWoo=base.find(r=>r.key==='woocommerce');const wooRow:Integration={key:'woocommerce',name:'WooCommerce (External)',description:existingWoo?.description||'Optional external commerce adapter.',enabled:Boolean(woo?.connected),status:woo?.connected?'connected':'disconnected',configured:Boolean(woo?.configured),last_error:woo?.error||existingWoo?.last_error||null,error:existingWoo?.error||null,connected_at:existingWoo?.connected_at||null,last_tested_at:existingWoo?.last_tested_at||null};setRows([...base.filter(r=>!['meta','meta_ads','woocommerce'].includes(r.key)),wooRow,metaRow]);}catch(e){setError(e instanceof Error?e.message:'Unable to load integrations.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 const items=useMemo(()=>definitions.map(d=>({...d,...(rows.find(r=>r.key===d.key)||{})})),[rows]);
 function beginConnect(key:string){setSelected(key);setConfirmOpen(true);setMessage('');setError('')}
 async function authorize(){if(!selected)return;setBusy(true);setError('');setMessage('');try{if(selected==='woocommerce'){const result=await api<any>('/admin/integrations/woocommerce/status');if(result.data?.connected){setMessage('External WooCommerce adapter is reachable.');setConfirmOpen(false);setSelected(null);await load();return}throw new Error(result.data?.error||'WooCommerce is not configured on PriyasaCore.')}if(selected==='meta'){const result=await api<any>('/admin/integrations/meta/connect');const url=result.data?.authorization_url;if(!url)throw new Error(result.message||'Meta OAuth is not available from the current PriyasaCore connector.');window.location.assign(url);return}const result=await api(`/admin/integrations/${encodeURIComponent(selected)}/connect`,{method:'POST',headers:{'Idempotency-Key':idempotency(),'Content-Type':'application/json','X-Integration-Credential-Source':'server'},body:JSON.stringify({credential_source:'server'})});setMessage(result.message||`${selected} connected using secure server-side credentials.`);setConfirmOpen(false);setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Connection failed. Configure the provider on PriyasaCore, then retry.')}finally{setBusy(false)}}
 async function disconnect(key:string){if(!window.confirm(`Disconnect ${key}?`))return;setBusy(true);setError('');try{await api(`/admin/integrations/${encodeURIComponent(key)}/disconnect`,{method:'POST',headers:{'Idempotency-Key':idempotency()}});setMessage(`${key} disconnected.`);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to disconnect integration.')}finally{setBusy(false)}}
 async function testWoo(){setBusy(true);setError('');try{const result=await api<any>('/admin/integrations/woocommerce/status');if(result.data?.connected)setMessage('External WooCommerce adapter verified.');else throw new Error(result.data?.error||'WooCommerce adapter is unavailable.');await load()}catch(e){setError(e instanceof Error?e.message:'WooCommerce test failed.')}finally{setBusy(false)}}
 async function sync(kind:'products'|'categories'|'orders'){setSyncing(kind);setError('');try{const result=await api(`/admin/integrations/woocommerce/sync/${kind}`,{method:'POST',headers:{'Idempotency-Key':idempotency(),'Content-Type':'application/json'},body:'{}'});setMessage(result.message||`External WooCommerce ${kind} import completed.`);await load()}catch(e){setError(e instanceof Error?e.message:`WooCommerce ${kind} import failed.`)}finally{setSyncing(null)}}
 if(loading)return <><PageHeader title="Integrations" description="Priyasa Store controls providers through PriyasaCore."/><Loading/></>;
 const native=items.filter(x=>!x.external), external=items.filter(x=>x.external);
 const renderCard=(item:any)=><Card key={item.key}><div className="integration-card-head"><div className="module-icon"><item.icon size={22}/></div><span className={`status ${(item.enabled||item.status==='connected'||item.status==='healthy')?'connected':'disconnected'}`}>{(item.enabled||item.status==='connected'||item.status==='healthy')?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>} {(item.enabled||item.status==='connected'||item.status==='healthy')?'Connected':item.key==='woocommerce'&&item.configured===false?'Server not configured':'Not connected'}</span></div><h2>{item.name}</h2><p>{item.description}</p><div className="integration-capabilities">{item.capabilities.map((c:string)=><span key={c}>{c}</span>)}</div><small className="integration-auth"><LockKeyhole size={12}/> {item.authorization}</small>{item.last_error&&<small className="form-error">{item.last_error}</small>}<div className="form-actions integration-actions">{item.key==='woocommerce'?<><Button onClick={testWoo} disabled={busy||Boolean(syncing)}><RefreshCw size={14}/> Test adapter</Button>{item.enabled&&<div className="integration-sync-actions"><Button onClick={()=>sync('products')} disabled={Boolean(syncing)}>Products</Button><Button onClick={()=>sync('categories')} disabled={Boolean(syncing)}>Categories</Button><Button onClick={()=>sync('orders')} disabled={Boolean(syncing)}>Orders</Button></div>}</>:<>{(item.enabled||item.status==='connected')&&item.key!=='meta'&&<Button onClick={()=>disconnect(item.key)} disabled={busy}><Unplug size={14}/> Disconnect</Button>}{!(item.enabled||item.status==='connected')&&<Button className="primary" onClick={()=>beginConnect(item.key)} disabled={busy}><PlugZap size={14}/> {item.key==='meta'?'Start OAuth':'Connect securely'}</Button>}{item.key==='meta'&&(item.enabled||item.status==='connected')&&<span className="status connected"><CheckCircle2 size={14}/> OAuth active</span>}</>}</div></Card>;
 return <section className="content integrations-v2"><PageHeader title="Integrations" description="Priyasa Store owns the commerce experience. External providers are adapters, not the Admin control plane." action={<Button onClick={load} disabled={busy||Boolean(syncing)}><RefreshCw size={15}/> Refresh</Button>}/>{error&&<ErrorState error={error} onRetry={load}/>} {message&&<div className="form-success" role="status">{message}</div>}<div className="integration-security-banner"><ShieldCheck size={21}/><div><strong>PriyasaCore is the integration boundary</strong><span>Provider secrets remain server-side. Admin receives status and capabilities only.</span></div><LockKeyhole size={18}/></div><h2 style={{margin:'24px 0 10px'}}>Priyasa Store services</h2><p className="muted">These services support the native Store directly.</p><div className="grid-cards">{native.map(renderCard)}</div><h2 style={{margin:'30px 0 10px'}}>External adapters</h2><p className="muted">Optional connectors for migration or interoperability. Store products, orders, promotions and customer operations do not require WooCommerce.</p><div className="grid-cards">{external.map(renderCard)}</div>{selected&&confirmOpen&&<Modal title={`Connect ${definitions.find(d=>d.key===selected)?.name||selected}`} onClose={()=>!busy&&(setConfirmOpen(false),setSelected(null))}><div className="integration-consent"><div className="integration-consent-icon"><ShieldCheck size={28}/></div><h3>Allow PRIYASA to connect?</h3><p>This authorizes PriyasaCore to use credentials configured securely on the backend. No secret is entered, stored or returned by this browser.</p><div className="integration-consent-list"><div><CheckCircle2 size={15}/> Credentials remain server-side</div><div><CheckCircle2 size={15}/> Provider calls run through PriyasaCore</div><div><CheckCircle2 size={15}/> Connection can be revoked</div><div><CheckCircle2 size={15}/> Actions use idempotency protection</div></div>{error&&<div className="form-error">{error}</div>}<div className="form-actions"><Button onClick={authorize} disabled={busy}>{busy?'Checking securely…':'Allow & Connect'}</Button><Button onClick={()=>{setConfirmOpen(false);setSelected(null)}} disabled={busy}>Cancel</Button></div><p className="helper"><ExternalLink size={13}/> Provider credentials are configured in PriyasaCore/server secrets.</p></div></Modal>}</section>;
}
