'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {apiMessage,dateTime} from '@/lib/format';
import {PageHeader,Card,DataToolbar,Modal,Button,Badge,Loading,ErrorState,Empty} from '@/components/ui';

type Section={id:number|string;key:string;type:string;title?:string|null;subtitle?:string|null;image_url?:string|null;cta_label?:string|null;cta_href?:string|null;payload?:Record<string,unknown>|null;sort_order:number;is_active:boolean;starts_at?:string|null;ends_at?:string|null;updated_at?:string};
type List={data:Section[];current_page:number;last_page:number};
type Form={key:string;type:string;title:string;subtitle:string;image_url:string;cta_label:string;cta_href:string;payload:string;sort_order:number;is_active:boolean;starts_at:string;ends_at:string};
const blank:Form={key:'home',type:'banner',title:'',subtitle:'',image_url:'',cta_label:'Shop Now',cta_href:'/',payload:'{}',sort_order:0,is_active:true,starts_at:'',ends_at:''};
export default function Cms(){const [list,setList]=useState<List|null>(null),[q,setQ]=useState(''),[editing,setEditing]=useState<Section|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState<Form>({...blank}),[busy,setBusy]=useState(false),[error,setError]=useState('');
async function load(){setError('');try{const p=new URLSearchParams({per_page:'100'});if(q)p.set('key',q);const r=await api<List>(`/admin/cms?${p}`);setList(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load CMS'))}}
useEffect(()=>{load()},[]);useEffect(()=>{const t=setTimeout(load,300);return()=>clearTimeout(t)},[q]);
function openEditor(s?:Section){setEditing(s||null);setForm(s?{key:s.key,type:s.type,title:s.title||'',subtitle:s.subtitle||'',image_url:s.image_url||'',cta_label:s.cta_label||'',cta_href:s.cta_href||'',payload:JSON.stringify(s.payload||{},null,2),sort_order:s.sort_order||0,is_active:s.is_active,starts_at:'',ends_at:''}:{...blank});setOpen(true)}
async function save(){setBusy(true);setError('');try{let payload:Record<string,unknown>;try{payload=JSON.parse(form.payload||'{}')}catch{throw new Error('Payload must be valid JSON.')}const body={...form,payload,starts_at:form.starts_at||null,ends_at:form.ends_at||null};const r=editing?await api(`/admin/cms/${editing.id}`,{method:'PUT',body:JSON.stringify(body)}):await api('/admin/cms',{method:'POST',body:JSON.stringify(body)});if(!r.success)throw new Error(r.message||'Save failed');setOpen(false);setEditing(null);await load()}catch(e){setError(apiMessage(e,'Unable to save CMS section'))}finally{setBusy(false)}}
async function remove(id:Section['id']){if(!confirm('Delete this CMS section?'))return;setBusy(true);try{await api(`/admin/cms/${id}`,{method:'DELETE'});await load()}catch(e){setError(apiMessage(e,'Unable to delete CMS section'))}finally{setBusy(false)}}
return <section className="content"><PageHeader title="CMS" description="Control storefront banners and dynamic content without changing code." action={<Button className="primary" onClick={()=>openEditor()}>+ New section</Button>}/><Card><DataToolbar value={q} onChange={setQ} placeholder="Filter by key, e.g. home or shop.hero"/></Card>{error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:list?.data?.length?<Card><div className="table-wrap"><table className="table"><thead><tr><th>Key</th><th>Type</th><th>Title</th><th>Order</th><th>Status</th><th>Updated</th><th/></tr></thead><tbody>{list.data.map(s=><tr key={String(s.id)}><td><b>{s.key}</b></td><td>{s.type}</td><td>{s.title||'—'}</td><td>{s.sort_order}</td><td><Badge>{s.is_active?'Active':'Draft'}</Badge></td><td>{dateTime(s.updated_at)}</td><td><div className="form-actions"><Button onClick={()=>openEditor(s)}>Edit</Button><Button onClick={()=>remove(s.id)}>Delete</Button></div></td></tr>)}</tbody></table></div></Card>:<Card><Empty title="No CMS sections" text="Create the first storefront section."/></Card>}{open&&<Modal title={editing?'Edit section':'New section'} onClose={()=>setOpen(false)}><div className="form-grid">{[['key','Key'],['type','Type'],['title','Title'],['subtitle','Subtitle'],['image_url','Image URL'],['cta_label','CTA label'],['cta_href','CTA link']].map(([k,l])=><label key={k}>{l}<input className="wide-control" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Sort order<input className="wide-control" type="number" min="0" value={form.sort_order} onChange={e=>setForm({...form,sort_order:Number(e.target.value)})}/></label><label className="address-default"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active</label><label className="full-span">Payload JSON<textarea className="wide-control note" rows={8} value={form.payload} onChange={e=>setForm({...form,payload:e.target.value})}/></label><div className="form-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save section'}</Button></div></div></Modal>}</section>}
