'use client';

import {useEffect,useMemo,useState} from 'react';
import {GripVertical,Plus,Eye,EyeOff,Pencil,Trash2,Copy,ArrowUp,ArrowDown,Save,RefreshCw,Image as ImageIcon,ChevronDown,ChevronUp} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {PageHeader,Card,Button,Badge,Loading,ErrorState,Empty,Modal} from '@/components/ui';
import styles from './home-builder.module.css';

type Item={id?:string;title:string;subtitle?:string;image_url:string;mobile_image_url?:string;href:string;cta_label?:string;product_id?:string;category_id?:string};
type Section={id:number;key:string;type:string;title?:string|null;subtitle?:string|null;image_url?:string|null;mobile_image_url?:string|null;cta_label?:string|null;cta_href?:string|null;content?:Record<string,any>|null;sort_order:number;is_active:boolean;starts_at?:string|null;ends_at?:string|null};
type Form={key:string;type:string;title:string;subtitle:string;image_url:string;mobile_image_url:string;cta_label:string;cta_href:string;content:Record<string,any>;is_active:boolean;starts_at:string;ends_at:string};
const TYPES=[['hero_slider','Hero Slider'],['banner','Promotional Banner'],['image_carousel','Image Carousel'],['category_grid','Category Grid'],['product_carousel','Product Carousel'],['product_grid','Product Grid'],['collection_showcase','Collection Showcase'],['brand_grid','Brand Showcase'],['offer','Offer Banner'],['flash_sale','Flash Sale'],['trending','Trending Products'],['new_arrivals','New Arrivals'],['best_sellers','Best Sellers'],['video','Video Banner'],['text','Content / Text']];
const PRODUCT_TYPES=new Set(['product_carousel','product_grid','flash_sale','trending','new_arrivals','best_sellers']);
const ITEM_TYPES=new Set(['hero_slider','image_carousel','collection_showcase','brand_grid','category_grid']);
const emptyForm:Form={key:'home-section',type:'banner',title:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Shop Now',cta_href:'/shop',content:{items:[]},is_active:true,starts_at:'',ends_at:''};
const normalizeDate=(v?:string|null)=>v?(v.length>16?v.slice(0,16):v):'';
const item=(partial:Partial<Item>={})=>({title:'',subtitle:'',image_url:'',mobile_image_url:'',href:'/shop',cta_label:'Shop Now',...partial});
export default function Cms(){
 const[sections,setSections]=useState<Section[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Section|null>(null),[form,setForm]=useState<Form>(emptyForm),[open,setOpen]=useState(false),[dragId,setDragId]=useState<number|null>(null),[expanded,setExpanded]=useState<number|null>(null),[catalog,setCatalog]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]);
 const sorted=useMemo(()=>[...sections].sort((a,b)=>a.sort_order-b.sort_order||a.id-b.id),[sections]);
 async function load(){setLoading(true);setError('');try{const r=await api<any>('/admin/cms');const rows=Array.isArray(r.data)?r.data:Array.isArray(r.data?.data)?r.data.data:[];setSections(rows)}catch(e){setError(apiMessage(e,'Unable to load homepage sections'))}finally{setLoading(false)}}
 async function loadPickers(){try{const[p,c]=await Promise.all([api<any>('/admin/catalog/products?per_page=100'),api<any>('/admin/catalog/categories?per_page=100')]);const pv=p.data;setCatalog(Array.isArray(pv)?pv:Array.isArray(pv?.data)?pv.data:[]);const cv=c.data;setCategories(Array.isArray(cv)?cv:Array.isArray(cv?.data)?cv.data:[])}catch{}}
 useEffect(()=>{void load();void loadPickers()},[]);
 function edit(s?:Section){setEditing(s||null);setForm(s?{key:s.key,type:s.type||'banner',title:s.title||'',subtitle:s.subtitle||'',image_url:s.image_url||'',mobile_image_url:s.mobile_image_url||'',cta_label:s.cta_label||'',cta_href:s.cta_href||'',content:s.content&&typeof s.content==='object'?s.content:{items:[]},is_active:s.is_active,starts_at:normalizeDate(s.starts_at),ends_at:normalizeDate(s.ends_at)}:{...emptyForm,key:`home-${Date.now()}`,content:{items:[]}});setOpen(true);setError('')}
 function setContent(patch:Record<string,any>){setForm(f=>({...f,content:{...f.content,...patch}}))}
 function items(){return Array.isArray(form.content.items)?form.content.items as Item[]:[]}
 function setItems(next:Item[]){setContent({items:next})}
 function addItem(){setItems([...items(),item()])}
 function updateItem(i:number,patch:Partial<Item>){setItems(items().map((x,n)=>n===i?{...x,...patch}:x))}
 function removeItem(i:number){setItems(items().filter((_,n)=>n!==i))}
 async function save(){setBusy(true);setError('');setMessage('');try{const body={key:form.key,type:form.type,title:form.title,subtitle:form.subtitle,image_url:form.image_url||null,mobile_image_url:form.mobile_image_url||null,cta_label:form.cta_label||null,cta_href:form.cta_href||null,content:form.content,starts_at:form.starts_at||null,ends_at:form.ends_at||null,is_active:form.is_active};const r=editing?await api(`/admin/cms/${editing.id}`,{method:'PUT',body:JSON.stringify(body)}):await api('/admin/cms',{method:'POST',body:JSON.stringify({...body,sort_order:sorted.length})});if(!r.success)throw new Error(r.message||'Save failed');setOpen(false);setEditing(null);setMessage(editing?'Homepage section updated.':'Homepage section created.');await load()}catch(e){setError(apiMessage(e,'Unable to save homepage section'))}finally{setBusy(false)}}
 async function toggle(s:Section){setBusy(true);try{await api(`/admin/cms/${s.id}`,{method:'PUT',body:JSON.stringify({...s,content:s.content||{},is_active:!s.is_active})});await load()}catch(e){setError(apiMessage(e,'Unable to update section status'))}finally{setBusy(false)}}
 async function remove(s:Section){if(!confirm(`Remove “${s.title||s.key}” from the homepage?`))return;setBusy(true);try{await api(`/admin/cms/${s.id}`,{method:'DELETE'});await load()}catch(e){setError(apiMessage(e,'Unable to remove section'))}finally{setBusy(false)}}
 async function reorder(next:Section[]){const normalized=next.map((s,i)=>({...s,sort_order:i}));setSections(normalized);setBusy(true);try{const r=await api('/admin/cms/reorder',{method:'POST',body:JSON.stringify({sections:normalized.map(s=>({id:s.id,sort_order:s.sort_order}))})});if(!r.success)throw new Error(r.message||'Reorder failed');setMessage('Homepage order saved.')}catch(e){setError(apiMessage(e,'Unable to save homepage order'));await load()}finally{setBusy(false)}}
 function move(i:number,d:number){const n=[...sorted],t=i+d;if(t<0||t>=n.length)return;[n[i],n[t]]=[n[t],n[i]];void reorder(n)}
 function drop(t:number){if(dragId==null)return;const f=sorted.findIndex(s=>s.id===dragId);if(f<0||f===t)return;const n=[...sorted];const[x]=n.splice(f,1);n.splice(t,0,x);setDragId(null);void reorder(n)}
 async function duplicate(s:Section){setBusy(true);try{await api('/admin/cms',{method:'POST',body:JSON.stringify({key:`${s.key}-copy-${Date.now()}`,type:s.type,title:s.title?`${s.title} Copy`:'Copy',subtitle:s.subtitle,image_url:s.image_url,mobile_image_url:s.mobile_image_url,cta_label:s.cta_label,cta_href:s.cta_href,content:s.content||{items:[]},sort_order:sorted.length,is_active:false})});await load()}catch(e){setError(apiMessage(e,'Unable to duplicate section'))}finally{setBusy(false)}}
 if(loading)return <><PageHeader title="Homepage Builder" description="Manage every storefront section from one place."/><Loading/></>;
 const selectedType=form.type;
 return <section className={`content ${styles.page}`}><PageHeader title="Homepage Builder" description="Visually build the storefront homepage. Changes are rendered by Store in the saved order." action={<div className={styles.headerActions}><Button onClick={load} disabled={busy}><RefreshCw size={15}/> Refresh</Button><Button className="primary" onClick={()=>edit()} disabled={busy}><Plus size={15}/> Add section</Button></div>}/><div className={styles.hero}><div><span className={styles.kicker}>LIVE STOREFRONT</span><h2>Visual merchandising control</h2><p>Create hero slides, banners, category/product grids, collections, offers and campaigns without editing JSON. Images and catalog records can be selected directly.</p></div><div className={styles.stats}><strong>{sorted.length}</strong><span>sections</span></div></div>{error&&<ErrorState error={error} onRetry={load}/>} {message&&<div className="form-success" role="status">{message}</div>}{!sorted.length?<Card><Empty title="Homepage is empty" text="Add your first hero, banner, category or product section."/></Card>:<div className={styles.list}>{sorted.map((s,i)=><Card key={s.id}><div className={styles.row} draggable onDragStart={()=>setDragId(s.id)} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(i)}><div className={styles.order}><GripVertical size={18}/><span>{String(i+1).padStart(2,'0')}</span></div><div className={styles.preview}>{s.image_url?<img src={s.image_url} alt=""/>:<div className={styles.previewFallback}>{s.type.replaceAll('_',' ')}</div>}</div><div className={styles.info}><div className={styles.titleLine}><h3>{s.title||s.key}</h3><Badge>{s.is_active?'Live':'Draft'}</Badge></div><p>{s.subtitle||'No subtitle'}</p><div className={styles.meta}><span>{s.type.replaceAll('_',' ')}</span><span>Order {i+1}</span>{s.starts_at&&<span>Starts {new Date(s.starts_at).toLocaleString()}</span>}{s.ends_at&&<span>Ends {new Date(s.ends_at).toLocaleString()}</span>}</div></div><div className={styles.actions}><Button onClick={()=>move(i,-1)} disabled={busy||i===0}><ArrowUp size={15}/></Button><Button onClick={()=>move(i,1)} disabled={busy||i===sorted.length-1}><ArrowDown size={15}/></Button><Button onClick={()=>edit(s)} disabled={busy}><Pencil size={15}/> Edit</Button><Button onClick={()=>duplicate(s)} disabled={busy}><Copy size={15}/></Button><Button onClick={()=>toggle(s)} disabled={busy}>{s.is_active?<EyeOff size={15}/>:<Eye size={15}/>}</Button><Button onClick={()=>remove(s)} disabled={busy}><Trash2 size={15}/></Button></div></div></Card>)}</div>}
 {open&&<Modal title={editing?'Edit homepage section':'Add homepage section'} onClose={()=>!busy&&setOpen(false)}><div className={styles.form}><div className={styles.grid}><label>Section type<select className="wide-control" value={selectedType} onChange={e=>{const type=e.target.value;setForm(f=>({...f,type,content:PRODUCT_TYPES.has(type)?{query:type,limit:12,items:[]}:f.content}))}}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Section key<input className="wide-control" value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/></label><label>Title<input className="wide-control" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Subtitle<input className="wide-control" value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><label>CTA label<input className="wide-control" value={form.cta_label} onChange={e=>setForm({...form,cta_label:e.target.value})}/></label><label>CTA link<input className="wide-control" value={form.cta_href} onChange={e=>setForm({...form,cta_href:e.target.value})}/></label><label className={styles.full}>Desktop image URL<input className="wide-control" type="url" placeholder="https://…" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label className={styles.full}>Mobile image URL <span className={styles.muted}>(optional)</span><input className="wide-control" type="url" placeholder="https://…" value={form.mobile_image_url} onChange={e=>setForm({...form,mobile_image_url:e.target.value})}/></label><label>Start date/time<input className="wide-control" type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>End date/time<input className="wide-control" type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label></div>
 {ITEM_TYPES.has(selectedType)&&<div className={styles.itemsPanel}><div className={styles.panelHead}><div><strong>Visual items</strong><span>Add slides/cards without editing JSON.</span></div><Button onClick={addItem}><Plus size={14}/> Add item</Button></div>{items().map((it,i)=><div className={styles.item} key={i}><div className={styles.itemHead}><b>Item {i+1}</b><div><Button onClick={()=>i>0&&setItems(items().map((x,n)=>n===i-1?it:n===i?items()[i-1]:x))} disabled={i===0}>↑</Button><Button onClick={()=>i<items().length-1&&setItems(items().map((x,n)=>n===i?items()[i+1]:n===i+1?it:x))} disabled={i===items().length-1}>↓</Button><Button onClick={()=>removeItem(i)}>Remove</Button></div></div><div className={styles.itemGrid}><label>Title<input className="wide-control" value={it.title} onChange={e=>updateItem(i,{title:e.target.value})}/></label><label>Link<input className="wide-control" value={it.href} onChange={e=>updateItem(i,{href:e.target.value})}/></label><label>CTA<input className="wide-control" value={it.cta_label||''} onChange={e=>updateItem(i,{cta_label:e.target.value})}/></label><label className={styles.full}>Desktop image<input className="wide-control" value={it.image_url} onChange={e=>updateItem(i,{image_url:e.target.value})}/></label><label className={styles.full}>Mobile image<input className="wide-control" value={it.mobile_image_url||''} onChange={e=>updateItem(i,{mobile_image_url:e.target.value})}/></label><div className={styles.imagePreview}>{it.image_url?<img src={it.image_url} alt=""/>:<><ImageIcon size={18}/><span>Paste an image URL</span></>}</div></div></div>)}</div>}
 {PRODUCT_TYPES.has(selectedType)&&<div className={styles.productPanel}><div className={styles.panelHead}><div><strong>Product merchandising</strong><span>Select products or use a live catalog query.</span></div></div><div className={styles.grid}><label>Catalog query<select className="wide-control" value={String(form.content.query||selectedType)} onChange={e=>setContent({query:e.target.value})}><option value="products-sale">Sale</option><option value="products-latest">New Arrivals</option><option value="products-best">Best Sellers</option><option value="trending">Trending</option></select></label><label>Visible products<input className="wide-control" type="number" min="4" max="30" value={Number(form.content.limit||12)} onChange={e=>setContent({limit:Number(e.target.value)})}/></label></div><div className={styles.pickerList}>{catalog.slice(0,100).map((p:any)=><label key={String(p.id)} className={styles.picker}><input type="checkbox" checked={Array.isArray(form.content.product_ids)&&form.content.product_ids.map(String).includes(String(p.id))} onChange={e=>{const ids=Array.isArray(form.content.product_ids)?form.content.product_ids.map(String):[];setContent({product_ids:e.target.checked?[...ids,String(p.id)]:ids.filter(x=>x!==String(p.id))})}}/><span>{p.name||p.slug}</span><small>{p.sku||''}</small></label>)}</div></div>}
 {selectedType==='category_grid'&&<div className={styles.productPanel}><div className={styles.panelHead}><div><strong>Category selection</strong><span>Choose categories to display. Leave empty to use all active categories.</span></div></div><div className={styles.pickerList}>{categories.map((c:any)=><label key={String(c.id)} className={styles.picker}><input type="checkbox" checked={Array.isArray(form.content.category_ids)&&form.content.category_ids.map(String).includes(String(c.id))} onChange={e=>{const ids=Array.isArray(form.content.category_ids)?form.content.category_ids.map(String):[];setContent({category_ids:e.target.checked?[...ids,String(c.id)]:ids.filter(x=>x!==String(c.id))})}}/><span>{c.name||c.slug}</span></label>)}</div></div>}
 {selectedType==='video'&&<label>Video URL<input className="wide-control" value={String(form.content.video_url||'')} onChange={e=>setContent({video_url:e.target.value})}/></label>}
 {selectedType==='text'&&<label>Content<textarea className={`wide-control note ${styles.json}`} rows={8} value={String(form.content.text||'')} onChange={e=>setContent({text:e.target.value})}/></label>}
 <label className={styles.checkbox}><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Publish this section</label><div className={styles.formActions}><Button onClick={()=>setOpen(false)} disabled={busy}>Cancel</Button><Button className="primary" onClick={save} disabled={busy}><Save size={15}/>{busy?'Saving…':'Save section'}</Button></div></div></Modal>}</section>;
}
