'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {ADMIN_CAPABILITIES,capabilityForRoute} from '@/lib/admin-capabilities';
import {Badge,Button,Card,ErrorState,Loading,PageHeader} from '@/components/ui';

type Route={method:string;uri:string;name?:string;action?:string};
function normalize(value:any):Route[]{const raw=value?.data??value?.routes??value;const list=Array.isArray(raw)?raw:(raw&&typeof raw==='object'?Object.entries(raw).map(([uri,v]:any)=>({uri,...(typeof v==='object'?v:{})})):[]);return list.flatMap((r:any)=>String(r.method||r.methods||'GET').replace(/[\[\]]/g,'').split('|').map(method=>({method:method.trim().toUpperCase(),uri:String(r.uri||r.path||r.route||''),name:r.name,action:r.action||r.controller}))).filter(r=>r.uri.includes('/admin/'))}

export default function AdminWorkspace({capabilityKey}:{capabilityKey:string}){
 const capability=ADMIN_CAPABILITIES.find(c=>c.key===capabilityKey)||ADMIN_CAPABILITIES[0];
 const [routes,setRoutes]=useState<Route[]>([]),[q,setQ]=useState(''),[method,setMethod]=useState('ALL'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Route|null>(null),[params,setParams]=useState<Record<string,string>>({}),[body,setBody]=useState('{}'),[result,setResult]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await api<any>('/docs/openapi.routes.json');setRoutes(normalize(r))}catch(e){setError(e instanceof Error?e.message:'Unable to load PriyasaCore admin routes')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const scoped=useMemo(()=>routes.filter(r=>capability.prefixes.some(p=>r.uri===p||r.uri.startsWith(`${p}/`))),[routes,capability]);
 const methods=useMemo(()=>['ALL',...Array.from(new Set(scoped.map(r=>r.method)))],[scoped]);
 const filtered=useMemo(()=>scoped.filter(r=>(method==='ALL'||r.method===method)&&(!q||`${r.method} ${r.uri} ${r.name||''} ${r.action||''}`.toLowerCase().includes(q.toLowerCase()))),[scoped,q,method]);
 function open(r:Route){const p:Record<string,string>={};(r.uri.match(/\{[^}]+\}/g)||[]).forEach(x=>p[x.slice(1,-1)]='');setParams(p);setBody('{}');setResult('');setSelected(r)}
 async function execute(){if(!selected)return;setBusy(true);setResult('');try{let uri=selected.uri;Object.entries(params).forEach(([k,v])=>uri=uri.replace(`{${k}}`,encodeURIComponent(v)));const init:RequestInit={method:selected.method};if(!['GET','HEAD','DELETE'].includes(selected.method))init.body=body;const response=await api<any>(uri.replace(/^api\/v1/,''),init);setResult(JSON.stringify(response,null,2))}catch(e){setResult(JSON.stringify({error:e instanceof Error?e.message:String(e)},null,2))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title={capability.label} description={capability.description} action={<Button onClick={load} disabled={loading}>Refresh API map</Button>}/><div className="grid" style={{marginBottom:16}}><Card><div className="metric-label">Backend routes</div><div className="metric">{scoped.length}</div><div className="metric-label">Live from PriyasaCore</div></Card><Card><div className="metric-label">Visible after filter</div><div className="metric">{filtered.length}</div><div className="metric-label">Searchable operations</div></Card><Card><div className="metric-label">Write operations</div><div className="metric">{scoped.filter(r=>['POST','PUT','PATCH','DELETE'].includes(r.method)).length}</div><div className="metric-label">Protected by API auth</div></Card></div><Card><div className="toolbar"><div className="searchbox"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search endpoint, controller or action…"/></div><select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select><Badge>{filtered.length} operations</Badge></div>{error&&<ErrorState error={error} onRetry={load}/>} {loading?<Loading/>:<div className="table-wrap"><table className="table"><thead><tr><th>Method</th><th>Endpoint</th><th>Controller</th><th>Action</th><th/></tr></thead><tbody>{filtered.map((r,i)=><tr key={`${r.method}-${r.uri}-${i}`}><td><Badge>{r.method}</Badge></td><td><code>{r.uri}</code></td><td>{r.action?.split('@')[0]||'—'}</td><td>{r.action?.split('@')[1]||r.name||'—'}</td><td><Button onClick={()=>open(r)}>Open</Button></td></tr>)}</tbody></table></div>}</Card>{selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="modal"><div className="modal-head"><h2>{selected.method} {selected.uri}</h2><button onClick={()=>setSelected(null)}>×</button></div><p className="muted">{selected.action||selected.name||'PriyasaCore admin operation'}</p>{Object.keys(params).map(k=><label className="form" key={k}>Path parameter: {k}<input value={params[k]} onChange={e=>setParams({...params,[k]:e.target.value})}/></label>)}{!['GET','HEAD','DELETE'].includes(selected.method)&&<label className="form">JSON request body<textarea value={body} onChange={e=>setBody(e.target.value)} spellCheck={false}/></label>}<div className="form-actions"><Button onClick={()=>setSelected(null)}>Close</Button><Button className="primary" disabled={busy} onClick={execute}>{busy?'Executing…':'Execute API'}</Button></div>{result&&<pre style={{maxHeight:360,overflow:'auto',background:'#111',color:'#eee',padding:14,borderRadius:10,fontSize:11,marginTop:14}}>{result}</pre>}</div></div>}</section>
}
