'use client';

import { useState } from 'react';
import { Sparkles, Check, Wand2 } from 'lucide-react';
import { api } from '@/lib/api';
import { Button, Modal, Badge } from '@/components/ui';

type Section = { generation_id:number; content:Record<string,unknown>; provider?:string; model?:string };
const CONTENT_FIELDS = [['title','Title'],['short_description','Short description'],['description','Description'],['highlights','Highlights'],['fabric_details','Fabric details'],['fit_information','Fit information'],['styling_suggestions','Styling suggestions'],['care_instructions','Care instructions'],['faqs','FAQs']] as const;
const SEO_FIELDS = [['meta_title','SEO title'],['meta_description','Meta description'],['focus_keyword','Focus keyword'],['secondary_keywords','Secondary keywords'],['tags','Tags'],['slug','URL slug'],['image_alt_text','Image ALT text']] as const;
function display(v:unknown){if(Array.isArray(v))return v.map(x=>typeof x==='object'?JSON.stringify(x):String(x)).join('\n');if(v&&typeof v==='object')return JSON.stringify(v,null,2);return v==null?'':String(v)}

export default function AIProductAssistant({productId,onApplied}:{productId:number;onApplied?:()=>void}) {
 const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [applying,setApplying]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [content,setContent]=useState<Section|null>(null); const [seo,setSeo]=useState<Section|null>(null); const [instructions,setInstructions]=useState('');
 async function generate(){setBusy(true);setError('');setNotice('');try{const r=await api<{sections:Record<string,Section>}>(`/admin/ai/products/${productId}/generate`,{method:'POST',body:JSON.stringify({sections:['content','seo'],instructions:instructions.trim()||undefined})});setContent(r.data?.sections?.content||null);setSeo(r.data?.sections?.seo||null);setNotice('AI draft ready. Review before applying.')}catch(e){setError(e instanceof Error?e.message:'AI generation failed')}finally{setBusy(false)}}
 async function apply(section:Section,fields:string[]){if(!fields.length)return;setApplying(true);setError('');try{await api(`/admin/ai/products/${productId}/apply`,{method:'POST',body:JSON.stringify({generation_id:section.generation_id,fields})});setNotice('Selected AI content applied successfully.');onApplied?.()}catch(e){setError(e instanceof Error?e.message:'Unable to apply AI content')}finally{setApplying(false)}}
 return <><Button onClick={()=>{setOpen(true);setError('');setNotice('')}}><Sparkles size={14}/> AI Assistant</Button>{open&&<Modal title="PRIYASA AI Assistant" onClose={()=>setOpen(false)}><div style={{display:'grid',gap:14}}>
  <div style={{padding:12,border:'1px solid #f1d7e1',borderRadius:12,background:'#fff8fb'}}><strong>AI-generated drafts require review</strong><div style={{fontSize:13,color:'#666',marginTop:4}}>Product facts remain authoritative; nothing is published automatically.</div></div>
  <label>Instructions (optional)<textarea value={instructions} onChange={e=>setInstructions(e.target.value)} rows={3} placeholder="Example: Keep the copy premium, concise and suitable for Indian ethnic wear." style={{width:'100%',marginTop:6}}/></label>
  <div style={{display:'flex',justifyContent:'flex-end'}}><Button className="primary" disabled={busy} onClick={()=>void generate()}><Wand2 size={14}/>{busy?'Generating…':'Generate content + SEO'}</Button></div>
  {error&&<div role="alert" style={{padding:10,borderRadius:10,background:'#fff1f1'}}>{error}</div>}{notice&&<div style={{padding:10,borderRadius:10,background:'#f7fff9'}}><Check size={14} style={{verticalAlign:'middle'}}/> {notice}</div>}
  {content&&<Draft title="Content" section={content} fields={CONTENT_FIELDS} applying={applying} onApply={f=>void apply(content,f)}/>} {seo&&<Draft title="SEO" section={seo} fields={SEO_FIELDS} applying={applying} onApply={f=>void apply(seo,f)}/>} 
 </div></Modal>}</>
}
function Draft({title,section,fields,applying,onApply}:{title:string;section:Section;fields:readonly (readonly [string,string])[];applying:boolean;onApply:(f:string[])=>void}){const [selected,setSelected]=useState<string[]>(fields.map(([k])=>k));return <div style={{border:'1px solid #eee',borderRadius:12,padding:12}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginBottom:10}}><div><strong>{title}</strong><div style={{fontSize:12,color:'#777'}}>{section.provider||'—'} · {section.model||'—'} · Draft #{section.generation_id}</div></div><Badge>review</Badge></div><div style={{display:'grid',gap:8}}>{fields.map(([key,label])=>{const value=section.content[key];if(value===undefined)return null;const checked=selected.includes(key);return <div key={key} style={{border:'1px solid #eee',borderRadius:9,padding:9}}><label style={{display:'flex',gap:8,fontWeight:600}}><input type="checkbox" checked={checked} onChange={()=>setSelected(v=>checked?v.filter(x=>x!==key):[...v,key])}/>{label}</label><pre style={{whiteSpace:'pre-wrap',fontFamily:'inherit',fontSize:13,maxHeight:160,overflow:'auto',margin:'8px 0 0'}}>{display(value)}</pre></div>})}</div><div style={{display:'flex',justifyContent:'flex-end',marginTop:10}}><Button className="primary" disabled={applying||!selected.length} onClick={()=>onApply(selected)}>{applying?'Applying…':'Apply selected'}</Button></div></div>}
