'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {ArrowLeft,Edit3,Plus,Power,Save,Trash2,Star,Package,Boxes,Image as ImageIcon,Settings2} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Product,ProductMedia,Variant} from '@/lib/types';
import {Badge,Button,Card,ErrorState,Loading,Modal,PageHeader} from '@/components/ui';

const blankVariant={sku:'',barcode:'',size:'',color:'',price:'',mrp:'',weight_grams:'',image_url:'',quantity:'0',low_stock_threshold:'3',is_active:true,attributes:'{}'};
const blankProduct={name:'',slug:'',sku:'',price:'',mrp:'',status:'draft',description:'',short_description:'',image_url:''};
function money(v?:number){return v==null?'—':`₹ ${Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v))}

export default function ProductStudio(){
 const params=useParams<{id:string}>();const router=useRouter();
 const [product,setProduct]=useState<Product|null>(null),[media,setMedia]=useState<ProductMedia[]>([]),[tab,setTab]=useState<'overview'|'variants'|'media'|'inventory'>('overview');
 const [open,setOpen]=useState(false),[productOpen,setProductOpen]=useState(false),[mediaOpen,setMediaOpen]=useState(false),[bulkOpen,setBulkOpen]=useState(false);
 const [variant,setVariant]=useState<Variant|null>(null),[variantForm,setVariantForm]=useState<any>(blankVariant),[productForm,setProductForm]=useState<any>(blankProduct),[mediaForm,setMediaForm]=useState({url:'',alt_text:'',type:'image' as 'image'|'video',variant_id:''});
 const [bulkDelta,setBulkDelta]=useState(''),[bulkReason,setBulkReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setError('');try{const r=await api<Product>(`/admin/catalog/products/${params.id}`);const p=r.data||null;setProduct(p);if(p)setProductForm({name:p.name,slug:p.slug,sku:p.sku||'',price:p.price??'',mrp:p.mrp??'',status:p.status,description:(p as any).description||'',short_description:(p as any).short_description||'',image_url:(p as any).image_url||''});const m=await api<ProductMedia[]>(`/admin/catalog/products/${params.id}/media`);setMedia(m.data||[])}catch(e){setError(apiMessage(e,'Unable to load product'))}}
 useEffect(()=>{if(params.id)load()},[params.id]);
 const activeVariants=useMemo(()=>product?.variants?.filter(v=>v.is_active!==false)||[],[product]);
 const stock=useMemo(()=>{const vs=product?.variants||[];let on=0,reserved=0;for(const v of vs){on+=Number(v.inventory?.quantity||0);reserved+=Number((v.inventory?.reserved_quantity ?? v.inventory?.reserved) || 0)}return{on,reserved,available:on-reserved}},[product]);
 function startVariant(v?:Variant){setVariant(v||null);setVariantForm(v?{sku:v.sku||'',barcode:v.barcode||'',size:v.size||'',color:v.color||'',price:v.price??'',mrp:v.mrp??'',weight_grams:v.weight_grams??'',image_url:v.image_url||'',quantity:v.inventory?.quantity??0,low_stock_threshold:v.inventory?.low_stock_threshold??3,is_active:v.is_active!==false,attributes:JSON.stringify(v.attributes||{},null,2)}:clone(blankVariant));setOpen(true)}
 async function saveVariant(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{let attributes={};try{attributes=JSON.parse(variantForm.attributes||'{}')}catch{throw new Error('Variant attributes must be valid JSON.')}const body={sku:variantForm.sku,barcode:variantForm.barcode||null,size:variantForm.size||null,color:variantForm.color||null,price:variantForm.price===''?null:Number(variantForm.price),mrp:variantForm.mrp===''?null:Number(variantForm.mrp),weight_grams:variantForm.weight_grams===''?null:Number(variantForm.weight_grams),image_url:variantForm.image_url||null,quantity:Number(variantForm.quantity),low_stock_threshold:Number(variantForm.low_stock_threshold),is_active:Boolean(variantForm.is_active),attributes};await api(`/admin/catalog/products/${params.id}/variants${variant?`/${variant.id}`:''}`,{method:variant?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);await load()}catch(e){setError(apiMessage(e,'Unable to save variant'))}finally{setBusy(false)}}
 async function saveProduct(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(`/admin/catalog/products/${params.id}`,{method:'PUT',body:JSON.stringify({name:productForm.name,slug:productForm.slug,sku:productForm.sku||null,price:Number(productForm.price),mrp:productForm.mrp===''?null:Number(productForm.mrp),status:productForm.status,description:productForm.description,short_description:productForm.short_description,image_url:productForm.image_url||null})});setProductOpen(false);await load()}catch(e){setError(apiMessage(e,'Unable to update product'))}finally{setBusy(false)}}
 async function deactivate(v:Variant){if(!confirm(`Deactivate ${v.sku||'this variant'}?`))return;try{await api(`/admin/catalog/products/${params.id}/variants/${v.id}`,{method:'DELETE'});await load()}catch(e){setError(apiMessage(e,'Unable to deactivate variant'))}}
 async function saveMedia(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api(`/admin/catalog/products/${params.id}/media`,{method:'POST',body:JSON.stringify({url:mediaForm.url.trim(),alt_text:mediaForm.alt_text.trim()||null,type:mediaForm.type,variant_id:mediaForm.variant_id?Number(mediaForm.variant_id):null,is_primary:media.length===0})});setMediaOpen(false);setMediaForm({url:'',alt_text:'',type:'image',variant_id:''});await load()}catch(e){setError(apiMessage(e,'Unable to add media'))}finally{setBusy(false)}}
 async function makePrimary(m:ProductMedia){try{await api(`/admin/catalog/products/${params.id}/media/${m.id}`,{method:'PUT',body:JSON.stringify({is_primary:true})});await load()}catch(e){setError(apiMessage(e,'Unable to set primary media'))}}
 async function deleteMedia(m:ProductMedia){if(!confirm('Remove this media from the product?'))return;try{await api(`/admin/catalog/products/${params.id}/media/${m.id}`,{method:'DELETE'});await load()}catch(e){setError(apiMessage(e,'Unable to remove media'))}}
 async function bulkAdjust(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const delta=Number(bulkDelta);if(!Number.isInteger(delta)||delta===0)throw new Error('Enter a non-zero whole-number adjustment.');for(const v of activeVariants||[]){await api(`/admin/inventory/${v.id}/adjust`,{method:'POST',body:JSON.stringify({delta,reason:bulkReason.trim()||'Bulk product inventory adjustment'})})}setBulkOpen(false);setBulkDelta('');setBulkReason('');await load()}catch(e){setError(apiMessage(e,'Bulk inventory adjustment failed'))}finally{setBusy(false)}}
 async function togglePublish(){if(!product)return;const next=product.status==='published'?'draft':'published';if(next==='published'&&(!activeVariants?.length||!media.length)){setError('A product needs at least one active variant and one media item before publishing.');return}if(!confirm(next==='published'?'Publish this product to the storefront?':'Unpublish this product?'))return;setBusy(true);try{await api(`/admin/catalog/products/${params.id}`,{method:'PUT',body:JSON.stringify({status:next})});await load()}catch(e){setError(apiMessage(e,'Unable to change publish status'))}finally{setBusy(false)}}
 if(!product&&!error)return <section className="content"><Loading/></section>;
 return <section className="content product-studio"><Button onClick={()=>router.push('/products')}><ArrowLeft size={15}/> Products</Button>{error&&<ErrorState error={error} onRetry={load}/>} {product&&<>
  <PageHeader title={product.name} description={`${product.slug} · ${product.status}`} action={<div className="form-actions"><Button onClick={()=>setProductOpen(true)}><Edit3 size={14}/> Edit product</Button><Button onClick={togglePublish}><Power size={14}/>{product.status==='published'?'Unpublish':'Publish'}</Button><Button className="primary" onClick={()=>startVariant()}><Plus size={15}/> Add variant</Button></div>}/>
  <div className="stats-grid"><Card><span>Base price</span><strong>{money(product.price)}</strong></Card><Card><span>Variants</span><strong>{product.variants?.length||0}</strong></Card><Card><span>Units on hand</span><strong>{stock.on}</strong></Card><Card><span>Available</span><strong>{stock.available}</strong></Card></div>
  <div className="studio-tabs">{([['overview','Overview',Settings2],['variants','Variants',Package],['media','Media',ImageIcon],['inventory','Inventory',Boxes]] as const).map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={15}/>{label}</button>)}</div>
  {tab==='overview'&&<div className="section-grid"><Card><div className="section-head"><div><h2>Product information</h2><p>Catalog, pricing and storefront metadata.</p></div><Button onClick={()=>setProductOpen(true)}>Edit</Button></div><div className="detail-list"><div><span>Name</span><b>{product.name}</b></div><div><span>Slug</span><b>{product.slug}</b></div><div><span>SKU</span><b>{product.sku||'—'}</b></div><div><span>Category</span><b>{product.category?.name||'Not assigned'}</b></div><div><span>Price / MRP</span><b>{money(product.price)} / {money(product.mrp)}</b></div><div><span>Status</span><Badge>{product.status}</Badge></div></div></Card><Card><div className="section-head"><div><h2>Management shortcuts</h2><p>Move directly into the operational modules.</p></div></div><div className="shortcut-grid"><a href="/inventory"><Boxes size={17}/><span><b>Inventory</b><small>SKU stock and adjustments</small></span></a><a href="/categories"><Package size={17}/><span><b>Categories</b><small>Catalog taxonomy</small></span></a><a href="/collections"><Package size={17}/><span><b>Collections</b><small>Merchandising groups</small></span></a><a href="/merchandising"><Star size={17}/><span><b>Home Studio</b><small>Storefront placement</small></span></a></div></Card></div>}
  {tab==='variants'&&<Card><div className="section-head"><div><h2>Variant matrix</h2><p>Control SKU, barcode, size, colour, pricing, custom attributes and stock per sellable variant.</p></div><Button className="primary" onClick={()=>startVariant()}><Plus size={14}/> Add variant</Button></div>{product.variants?.length?<div className="table-wrap"><table className="table"><thead><tr><th>SKU</th><th>Size</th><th>Colour</th><th>Price</th><th>MRP</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{product.variants.map(v=><tr key={String(v.id)}><td><b>{v.sku||'—'}</b><div className="muted">{v.barcode||''}</div></td><td>{v.size||'—'}</td><td>{v.color||'—'}</td><td>{money(v.price??product.price)}</td><td>{money(v.mrp??product.mrp)}</td><td><b>{v.inventory?.quantity??0}</b><div className="muted">{v.inventory?.reserved_quantity??v.inventory?.reserved??0} reserved</div></td><td><Badge>{v.is_active===false?'inactive':'active'}</Badge></td><td><div className="form-actions"><Button onClick={()=>startVariant(v)}><Edit3 size={13}/></Button>{v.is_active!==false&&<Button onClick={()=>deactivate(v)}><Power size={13}/></Button>}</div></td></tr>)}</tbody></table></div>:<div className="empty"><strong>No variants</strong><span>Add your first sellable SKU.</span></div>}</Card>}
  {tab==='media'&&<Card><div className="section-head"><div><h2>Media library</h2><p>Product-level and variant-linked images/videos with primary-media control.</p></div><Button className="primary" onClick={()=>setMediaOpen(true)}><Plus size={14}/> Add media</Button></div>{media.length?<div className="media-grid">{media.map(m=><div className="media-card" key={String(m.id)}><div className="media-preview">{m.type==='image'?<img src={m.url} alt={m.alt_text||product.name}/>:<video src={m.url} controls/>}</div><div className="media-meta"><Badge>{m.is_primary?'primary':m.type}</Badge><span>#{m.sort_order}</span></div><div className="form-actions">{!m.is_primary&&<Button onClick={()=>makePrimary(m)}><Star size={13}/> Primary</Button>}<Button onClick={()=>deleteMedia(m)}><Trash2 size={13}/></Button></div></div>)}</div>:<div className="empty"><strong>No media</strong><span>Add at least one image before publishing.</span></div>}</Card>}
  {tab==='inventory'&&<Card><div className="section-head"><div><h2>Inventory control</h2><p>Live SKU stock view plus controlled bulk adjustments.</p></div><Button className="primary" onClick={()=>setBulkOpen(true)}>Bulk adjustment</Button></div><div className="stats-grid"><Card><span>On hand</span><strong>{stock.on}</strong></Card><Card><span>Reserved</span><strong>{stock.reserved}</strong></Card><Card><span>Available</span><strong>{stock.available}</strong></Card></div><div className="table-wrap"><table className="table"><thead><tr><th>SKU</th><th>Variant</th><th>On hand</th><th>Reserved</th><th>Available</th><th>Threshold</th></tr></thead><tbody>{product.variants?.map(v=>{const on=Number(v.inventory?.quantity||0),res=Number((v.inventory?.reserved_quantity ?? v.inventory?.reserved) || 0);return <tr key={String(v.id)}><td><b>{v.sku||'—'}</b></td><td>{[v.color,v.size].filter(Boolean).join(' / ')||'Default'}</td><td>{on}</td><td>{res}</td><td><b>{on-res}</b></td><td>{v.inventory?.low_stock_threshold??3}</td></tr>})}</tbody></table></div></Card>}
  {productOpen&&<Modal title="Edit product" onClose={()=>setProductOpen(false)}><form className="form" onSubmit={saveProduct}><div className="form-grid"><label>Product name<input required value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/></label><label>SEO slug<input required value={productForm.slug} onChange={e=>setProductForm({...productForm,slug:e.target.value})}/></label><label>Base SKU<input value={productForm.sku} onChange={e=>setProductForm({...productForm,sku:e.target.value})}/></label><label>Status<select value={productForm.status} onChange={e=>setProductForm({...productForm,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Selling price<input required type="number" step="0.01" value={productForm.price} onChange={e=>setProductForm({...productForm,price:e.target.value})}/></label><label>MRP<input type="number" step="0.01" value={productForm.mrp} onChange={e=>setProductForm({...productForm,mrp:e.target.value})}/></label></div><label>Short description<textarea rows={3} value={productForm.short_description} onChange={e=>setProductForm({...productForm,short_description:e.target.value})}/></label><label>Description<textarea rows={7} value={productForm.description} onChange={e=>setProductForm({...productForm,description:e.target.value})}/></label><label>Primary image URL<input type="url" value={productForm.image_url} onChange={e=>setProductForm({...productForm,image_url:e.target.value})}/></label><div className="form-actions"><Button type="button" onClick={()=>setProductOpen(false)}>Cancel</Button><Button className="primary" disabled={busy}><Save size={14}/>{busy?'Saving…':'Save product'}</Button></div></form></Modal>}
  {open&&<Modal title={variant?'Edit variant':'Add variant'} onClose={()=>setOpen(false)}><form className="form" onSubmit={saveVariant}><div className="form-grid">{[['sku','SKU'],['barcode','Barcode'],['size','Size'],['color','Colour'],['price','Selling price'],['mrp','MRP'],['weight_grams','Weight (g)'],['quantity','Opening stock'],['low_stock_threshold','Low-stock threshold']].map(([k,l])=><label key={k}>{l}<input required={k==='sku'} type={['price','mrp','weight_grams','quantity','low_stock_threshold'].includes(k)?'number':'text'} step={['price','mrp','weight_grams'].includes(k)?'0.01':undefined} value={variantForm[k]} onChange={e=>setVariantForm({...variantForm,[k]:e.target.value})}/></label>)}</div><label>Variant image URL<input type="url" value={variantForm.image_url} onChange={e=>setVariantForm({...variantForm,image_url:e.target.value})}/></label><label>Custom attributes / GST / HSN JSON<textarea rows={5} value={variantForm.attributes} onChange={e=>setVariantForm({...variantForm,attributes:e.target.value})} placeholder={'{\n  "gst_rate": 5,\n  "hsn": "6104",\n  "fabric": "Cotton"\n}'}/><span className="muted">Stored in the variant attributes object so the Core API remains the source of truth.</span></label><label className="check"><input type="checkbox" checked={variantForm.is_active} onChange={e=>setVariantForm({...variantForm,is_active:e.target.checked})}/> Active / sellable</label><div className="form-actions"><Button type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Saving…':variant?'Save variant':'Create variant'}</Button></div></form></Modal>}
  {mediaOpen&&<Modal title="Add product media" onClose={()=>setMediaOpen(false)}><form className="form" onSubmit={saveMedia}><label>Media URL<input required type="url" value={mediaForm.url} onChange={e=>setMediaForm({...mediaForm,url:e.target.value})}/></label><div className="form-grid"><label>Type<select value={mediaForm.type} onChange={e=>setMediaForm({...mediaForm,type:e.target.value as 'image'|'video'})}><option value="image">Image</option><option value="video">Video</option></select></label><label>Attach to variant<select value={mediaForm.variant_id} onChange={e=>setMediaForm({...mediaForm,variant_id:e.target.value})}><option value="">Product-level</option>{product.variants?.map(v=><option key={String(v.id)} value={String(v.id)}>{v.sku||`Variant ${v.id}`}</option>)}</select></label></div><label>Alt text<input value={mediaForm.alt_text} onChange={e=>setMediaForm({...mediaForm,alt_text:e.target.value})}/></label><div className="form-actions"><Button type="button" onClick={()=>setMediaOpen(false)}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Adding…':'Add media'}</Button></div></form></Modal>}
  {bulkOpen&&<Modal title="Bulk inventory adjustment" onClose={()=>setBulkOpen(false)}><form className="form" onSubmit={bulkAdjust}><p className="muted">This applies the same stock delta to all {activeVariants?.length||0} active variants of this product.</p><label>Quantity change<input required type="number" step="1" value={bulkDelta} onChange={e=>setBulkDelta(e.target.value)} placeholder="+10 or -2"/></label><label>Reason<input required value={bulkReason} onChange={e=>setBulkReason(e.target.value)} placeholder="Stock receipt, cycle count, damage…"/></label><div className="form-actions"><Button type="button" onClick={()=>setBulkOpen(false)}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Applying…':'Apply to all variants'}</Button></div></form></Modal>}
 </>}</section>
}
