'use client';
import Link from 'next/link';
import {ReactNode,useEffect,useMemo,useState} from 'react';
import {Search,ChevronLeft,ChevronRight,LogOut,Menu,X,RefreshCw,Command,ChevronDown,LayoutDashboard,ShoppingBag,Package,Layers3,Boxes,Users,Star,Tag,RotateCcw,Truck,MessageCircle,Workflow,Bell,BarChart3,Plug,ShieldCheck,Settings,ScrollText,PanelLeftClose,PanelLeftOpen} from 'lucide-react';
import {usePathname,useRouter} from 'next/navigation';
import {api} from '@/lib/api';
export function Badge({children}:{children:ReactNode}){return <span className="badge">{children}</span>}
export function Button({children,className='',...p}:{children:ReactNode;className?:string}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`btn ${className}`} {...p}>{children}</button>}
export function Card({children,className='' }:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function Empty({title='No records found',text='There is nothing to display yet.'}:{title?:string;text?:string}){return <div className="empty"><strong>{title}</strong><span>{text}</span></div>}
export function ErrorState({error,onRetry}:{error:string;onRetry:()=>void}){return <div className="error-state"><strong>Unable to load data</strong><span>{error}</span><Button onClick={onRetry}><RefreshCw size={15}/> Retry</Button></div>}
export function Loading(){return <div className="loading"><span/> <span/> <span/></div>}
export function Pagination({page,lastPage,onChange}:{page:number;lastPage:number;onChange:(p:number)=>void}){if(lastPage<=1)return null;return <div className="pagination"><Button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={16}/></Button><span>Page {page} of {lastPage}</span><Button disabled={page>=lastPage} onClick={()=>onChange(page+1)}><ChevronRight size={16}/></Button></div>}
export function PageHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="page-head"><div><div className="eyebrow">PRIYASA COMMERCE</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function DataToolbar({value,onChange,placeholder='Search…',children}:{value:string;onChange:(v:string)=>void;placeholder?:string;children?:ReactNode}){return <div className="toolbar"><div className="searchbox"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>{children}</div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose} aria-label="Close"><X size={19}/></button></div>{children}</div></div>}
export function AdminGate({children}:{children:ReactNode}){const router=useRouter();const [ready,setReady]=useState(false);useEffect(()=>{const token=localStorage.getItem('priyasa_admin_token');if(!token){router.replace('/login');return}setReady(true)},[router]);if(!ready)return null;return <>{children}</>}
export function LogoutButton(){const router=useRouter();const [busy,setBusy]=useState(false);async function logout(){if(busy)return;setBusy(true);try{await api('/auth/logout',{method:'POST'})}catch{}finally{localStorage.removeItem('priyasa_admin_token');localStorage.removeItem('priyasa_admin_user');router.replace('/login')}}return <button className="logout" disabled={busy} onClick={logout}><LogOut size={16}/> {busy?'Signing out…':'Sign out'}</button>}
const iconMap:Record<string,any>={Dashboard:LayoutDashboard,Orders:ShoppingBag,Products:Package,Collections:Layers3,Categories:Boxes,Inventory:Boxes,Customers:Users,Reviews:Star,Promotions:Tag,Returns:RotateCcw,Shipping:Truck,WhatsApp:MessageCircle,Automation:Workflow,Notifications:Bell,Analytics:BarChart3,Integrations:Plug,'Admins & Roles':ShieldCheck,Settings, 'Audit Logs':ScrollText,Merchandising:Layers3,CMS:Layers3};
function GlobalSearch(){const router=useRouter();const [q,setQ]=useState('');const [open,setOpen]=useState(false);const targets=[['Dashboard','/'],['Orders','/orders'],['Products','/products'],['Customers','/customers'],['Categories','/categories'],['Collections','/collections'],['Reviews','/reviews'],['Inventory','/inventory'],['Promotions','/promotions'],['Merchandising','/merchandising'],['CMS','/cms'],['Analytics','/analytics']];const matches=targets.filter(([n])=>!q||n.toLowerCase().includes(q.toLowerCase()));return <div className="global-search-wrap"><div className="global-search"><Search size={17}/><input value={q} onFocus={()=>setOpen(true)} onChange={e=>{setQ(e.target.value);setOpen(true)}} onKeyDown={e=>{if(e.key==='Escape')setOpen(false);if(e.key==='Enter'&&matches[0]){router.push(matches[0][1]);setOpen(false)}}} placeholder="Search orders, products, customers…"/><kbd><Command size={11}/>K</kbd></div>{open&&<div className="search-popover">{matches.slice(0,8).map(([n,h])=><button key={h} onMouseDown={()=>{router.push(h);setOpen(false)}}><Search size={14}/><span>{n}</span><ChevronRight size={13}/></button>)}{!matches.length&&<span className="muted">No matching workspace</span>}</div>}</div>}
function NavItem({name,path,collapsed,onClick}:{name:string;path:string;collapsed:boolean;onClick:()=>void}){const pathname=usePathname();const Icon=iconMap[name]||Boxes;const active=pathname===path||(path!=='/'&&pathname.startsWith(path+'/'));return <Link title={collapsed?name:undefined} onClick={onClick} className={`nav-item ${active?'active':''}`} href={path}><Icon size={16}/>{!collapsed&&<span>{name}</span>}{active&&!collapsed&&<span className="nav-dot"/>}</Link>}
export function Shell({children}:{children:ReactNode}){const path=usePathname();const [open,setOpen]=useState(false);const [collapsed,setCollapsed]=useState(false);const [profile,setProfile]=useState<{name?:string;email?:string;role?:string}>({});const isLogin=path==='/login';useEffect(()=>{if(!isLogin){try{const raw=localStorage.getItem('priyasa_admin_user');if(raw)setProfile(JSON.parse(raw))}catch{}}},[isLogin]);const title=useMemo(()=>path==='/'?'Dashboard':path.split('/')[1]?.replace(/-/g,' ')||'Dashboard',[path]);if(isLogin)return <>{children}</>;const groups=[{label:'Commerce',items:[['Dashboard','/'],['Orders','/orders'],['Products','/products'],['Collections','/collections'],['Categories','/categories'],['Inventory','/inventory'],['Customers','/customers'],['Reviews','/reviews'],['Promotions','/promotions'],['Returns','/returns'],['CMS','/cms'],['Merchandising','/merchandising']]},{label:'Operations',items:[['Shipping','/shipping'],['WhatsApp','/whatsapp'],['Automation','/automation'],['Notifications','/notifications'],['Analytics','/analytics']]},{label:'Integrations',items:[['Integrations','/integrations']]},{label:'System',items:[['Admins & Roles','/admins'],['Settings','/settings'],['Audit Logs','/audit']]}];return <div className={`admin-shell ${collapsed?'nav-collapsed':''}`}><aside className={`sidebar ${open?'open':''}`}><div className="brand"><span className="brand-mark">P</span>{!collapsed&&<span>PRIYASA <b>ADMIN</b></span>}<button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div><div className="workspace-pill">{!collapsed&&<><span className="live-dot"/> Production API</>}</div>{groups.map(g=><div key={g.label}><div className="nav-title">{!collapsed?g.label:'•'}</div><nav className="nav">{g.items.map(([n,h])=><NavItem key={h} name={n} path={h} collapsed={collapsed} onClick={()=>setOpen(false)}/>)}</nav></div>)}<div className="sidebar-bottom"><button className="collapse-btn" onClick={()=>setCollapsed(v=>!v)}>{collapsed?<PanelLeftOpen size={16}/>:<PanelLeftClose size={16}/>} {!collapsed&&'Collapse menu'}</button><LogoutButton/></div></aside>{open&&<div className="mobile-overlay" onClick={()=>setOpen(false)}/>}<main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button><div className="topbar-left"><span className="breadcrumb">Admin <ChevronRight size={13}/> {title}</span><GlobalSearch/></div><div className="profile"><div className="profile-copy"><span>{profile.name||profile.email||'Administrator'}</span><small>{profile.role||'Commerce Admin'}</small></div><div className="avatar">{(profile.name||profile.email||'AD').slice(0,2).toUpperCase()}</div><ChevronDown size={14} className="profile-chevron"/></div></header><AdminGate>{children}</AdminGate></main></div>}
