'use client';
import Link from 'next/link';
import {ReactNode,useEffect,useState} from 'react';
import {Search,ChevronLeft,ChevronRight,LogOut,Menu,X,RefreshCw} from 'lucide-react';
import {usePathname,useRouter} from 'next/navigation';
import {api} from '@/lib/api';
export function Badge({children}:{children:ReactNode}){return <span className="badge">{children}</span>}
export function Button({children,className='',...p}:{children:ReactNode;className?:string}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button className={`btn ${className}`} {...p}>{children}</button>}
export function Card({children,className='' }:{children:ReactNode;className?:string}){return <section className={`card ${className}`}>{children}</section>}
export function Empty({title='No records found',text='There is nothing to display yet.'}:{title?:string;text?:string}){return <div className="empty"><strong>{title}</strong><span>{text}</span></div>}
export function ErrorState({error,onRetry}:{error:string;onRetry:()=>void}){return <div className="error-state"><strong>Unable to load data</strong><span>{error}</span><Button onClick={onRetry}><RefreshCw size={15}/> Retry</Button></div>}
export function Loading(){return <div className="loading"><span/> <span/> <span/></div>}
export function Pagination({page,lastPage,onChange}:{page:number;lastPage:number;onChange:(p:number)=>void}){if(lastPage<=1)return null;return <div className="pagination"><Button disabled={page<=1} onClick={()=>onChange(page-1)}><ChevronLeft size={16}/></Button><span>Page {page} of {lastPage}</span><Button disabled={page>=lastPage} onClick={()=>onChange(page+1)}><ChevronRight size={16}/></Button></div>}
export function PageHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <div className="page-head"><div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>}
export function DataToolbar({value,onChange,placeholder='Search…',children}:{value:string;onChange:(v:string)=>void;placeholder?:string;children?:ReactNode}){return <div className="toolbar"><div className="searchbox"><Search size={17}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>{children}</div>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose} aria-label="Close"><X size={19}/></button></div>{children}</div></div>}
export function AdminGate({children}:{children:ReactNode}){const router=useRouter();const [ready,setReady]=useState(false);useEffect(()=>{const token=localStorage.getItem('priyasa_admin_token');if(!token){router.replace('/login');return}setReady(true)},[router]);if(!ready)return null;return <>{children}</>}
export function LogoutButton(){const router=useRouter();const [busy,setBusy]=useState(false);async function logout(){if(busy)return;setBusy(true);try{await api('/auth/logout',{method:'POST'})}catch{}finally{localStorage.removeItem('priyasa_admin_token');localStorage.removeItem('priyasa_admin_user');router.replace('/login')}}return <button className="logout" disabled={busy} onClick={logout}><LogOut size={16}/> {busy?'Signing out…':'Sign out'}</button>}
export function Shell({children}:{children:ReactNode}){const path=usePathname();const [open,setOpen]=useState(false);const [profile,setProfile]=useState<{name?:string;email?:string;role?:string}>({});if(path==='/login')return <>{children}</>;useEffect(()=>{try{const raw=localStorage.getItem('priyasa_admin_user');if(raw)setProfile(JSON.parse(raw))}catch{}},[]);const groups=[{label:'Commerce',items:[['Dashboard','/'],['Orders','/orders'],['Products','/products'],['Categories','/categories'],['Inventory','/inventory'],['Customers','/customers'],['Promotions','/promotions'],['Returns','/returns']]},{label:'Operations',items:[['Shipping','/shipping'],['WhatsApp','/whatsapp'],['Automation','/automation'],['Analytics','/analytics']]},{label:'Integrations',items:[['Integrations','/integrations']]},{label:'System',items:[['Admins & Roles','/admins'],['Settings','/settings'],['Audit Logs','/audit']]}];return <div className="admin-shell"><aside className={`sidebar ${open?'open':''}`}><div className="brand">PRIYASA <span>✦</span><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div>{groups.map(g=><div key={g.label}><div className="nav-title">{g.label}</div><nav className="nav">{g.items.map(([n,h])=><Link onClick={()=>setOpen(false)} className={path===h?'active':''} key={h} href={h}>{n}</Link>)}</nav></div>)}<LogoutButton/></aside>{open&&<div className="mobile-overlay" onClick={()=>setOpen(false)}/>}<main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Open menu"><Menu/></button><div className="global-search"><Search size={17}/><input placeholder="Search orders, products, customers…"/></div><div className="profile"><span>{profile.name||profile.email||'Administrator'}{profile.role?<small style={{display:'block',fontSize:11,opacity:.6}}>{profile.role}</small>:null}</span><div className="avatar">{(profile.name||profile.email||'AD').slice(0,2).toUpperCase()}</div></div></header><AdminGate>{children}</AdminGate></main></div>}
