'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowLeft,RefreshCw,Download} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Badge,Button,Card,DataToolbar,ErrorState,Loading,PageHeader} from '@/components/ui';

type Row=any;
const n=(v:any)=>Number(v ?? 0);
const first=(...values:any[])=>values.find(v=>v!==null&&v!==undefined&&v!=='');
function download(text:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv'}));a.download=`priyasa-inventory-ledger-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export default function InventoryLedger(){
 const [rows,setRows]=useState<Row[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const candidates=['/admin/inventory/ledger','/admin/inventory/history'];let data:any=null;let last:any=null;for(const url of candidates){try{const r=await api<any>(url);data=r.data;break}catch(e){last=e}}if(data===null&&last)throw last;setRows(Array.isArray(data)?data:(data?.data||data?.items||data?.entries||[]))}catch(e){setError(apiMessage(e,'Unable to load inventory ledger'))}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(r=>!q.trim()||JSON.stringify(r).toLowerCase().includes(q.trim().toLowerCase())),[rows,q]);
 function exportCsv(){const headers=['date','variant','sku','change','quantity_after','reason','reference','actor'];const cell=(v:any)=>{const s=String(v ?? '');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};const value=(r:Row,h:string)=>{switch(h){case 'sku':return first(r.sku,r.variant?.sku);case 'variant':return first(r.variant?.name,r.variant_name,r.name);case 'date':return first(r.created_at,r.date);case 'change':return first(r.delta,r.change,r.quantity_change);case 'quantity_after':return first(r.quantity_after,r.balance,r.stock_after);case 'reason':return first(r.reason,r.note);case 'reference':return first(r.reference,r.reference_id);case 'actor':return first(r.actor?.name,r.actor_name,r.user?.name);default:return r[h]}};download([headers.join(','),...filtered.map(r=>headers.map(h=>cell(value(r,h))).join(','))].join('\n'))}
 return <section className="content"><div className="form-actions" style={{justifyContent:'flex-start',marginBottom:10}}><Link href="/inventory"><Button><ArrowLeft size={14}/> Inventory</Button></Link></div><PageHeader title="Inventory Ledger" description="Audit every stock movement without replacing PriyasaCore's inventory source of truth." action={<div className="form-actions"><Button onClick={exportCsv} disabled={!filtered.length}><Download size={14}/> Export</Button><Button onClick={load}><RefreshCw size={14}/> Refresh</Button></div>}/>{error&&<ErrorState error={error} onRetry={load}/>}<Card><DataToolbar value={q} onChange={setQ} placeholder="Search SKU, reason, reference…"/><div style={{marginTop:12}}>{loading?<Loading/>:filtered.length?<div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Variant / SKU</th><th>Change</th><th>After</th><th>Reason</th><th>Reference</th><th>Actor</th></tr></thead><tbody>{filtered.map((r,i)=>{const change=n(first(r.delta,r.change,r.quantity_change));return <tr key={String(r.id ?? i)}><td>{first(r.created_at,r.date)||'—'}</td><td><b>{first(r.variant?.name,r.variant_name,r.name)||'—'}</b><div className="muted">{first(r.variant?.sku,r.sku)||'—'}</div></td><td><Badge>{change>0?`+${change}`:change}</Badge></td><td>{first(r.quantity_after,r.balance,r.stock_after)||'—'}</td><td>{first(r.reason,r.note)||'—'}</td><td>{first(r.reference,r.reference_id)||'—'}</td><td>{first(r.actor?.name,r.actor_name,r.user?.name)||'—'}</td></tr>})}</tbody></table></div>:<div className="empty"><strong>No ledger entries</strong><span>Stock movements will appear here when the Core API exposes inventory history.</span></div>}</div></Card><div style={{marginTop:15}}><Card className="notice"><b>Operational rule</b><span>Use Inventory → Adjust for controlled stock changes. This ledger is read-only and is designed for reconciliation, audits and warehouse review.</span></Card></div></section>
}
