'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';import {money,dateTime,apiMessage} from '@/lib/format';
import {PageHeader,Card,Button,ErrorState,Loading} from '@/components/ui';

type Metrics={revenue:number;orders:number;aov:number;customers:number;new_customers?:number;returning_customers?:number;cancelled_orders?:number;discounts?:number;shipping?:number};
type Point={date:string;revenue:number;orders:number};
type Report={metrics:Metrics;series:Point[];top_products?:{name:string;units:number;revenue:number}[];channels?:{channel:string;orders:number;revenue:number}[];generated_at?:string};
function iso(d:Date){return d.toISOString().slice(0,10)}
export default function Analytics(){const [from,setFrom]=useState(()=>{const d=new Date();d.setDate(d.getDate()-29);return iso(d)});const [to,setTo]=useState(()=>iso(new Date()));const [r,setR]=useState<Report|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
async function load(){setLoading(true);setError('');try{const x=await api<Report>(`/admin/analytics?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`);setR(x.data||null)}catch(e){setError(apiMessage(e,'Unable to load analytics'))}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
return <section className="content"><PageHeader title="Analytics" description="Revenue, orders, customers and channel performance from the commerce source of truth." action={<div className="form-actions"><input className="input" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="input" type="date" value={to} onChange={e=>setTo(e.target.value)}/><Button className="primary" onClick={load} disabled={loading}>Apply</Button></div>}/>{error&&<ErrorState error={error} onRetry={load}/>} {loading?<Loading/>:r?<><div className="metrics-grid">{[['Revenue',money(r.metrics.revenue)],['Orders',r.metrics.orders],['AOV',money(r.metrics.aov)],['Customers',r.metrics.customers],['New customers',r.metrics.new_customers??0],['Returning',r.metrics.returning_customers??0],['Cancelled',r.metrics.cancelled_orders??0],['Discounts',money(r.metrics.discounts??0)]].map(([k,v])=><Card key={String(k)}><div className="metric-label">{k}</div><div className="metric-value">{v}</div></Card>)}</div><div className="two-col"><Card><div className="card-title">Daily performance</div><div className="table-wrap"><table className="table"><thead><tr><th>Date</th><th>Orders</th><th>Revenue</th></tr></thead><tbody>{(r.series||[]).map(p=><tr key={p.date}><td>{p.date}</td><td>{p.orders}</td><td>{money(p.revenue)}</td></tr>)}</tbody></table></div></Card><Card><div className="card-title">Top products</div>{r.top_products?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Product</th><th>Units</th><th>Revenue</th></tr></thead><tbody>{r.top_products.map((p,i)=><tr key={`${p.name}-${i}`}><td>{p.name}</td><td>{p.units}</td><td>{money(p.revenue)}</td></tr>)}</tbody></table></div>:<div className="empty">No product sales for this period.</div>}</Card></div><Card><div className="card-title">Channel performance</div>{r.channels?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Channel</th><th>Orders</th><th>Revenue</th></tr></thead><tbody>{r.channels.map(c=><tr key={c.channel}><td>{c.channel}</td><td>{c.orders}</td><td>{money(c.revenue)}</td></tr>)}</tbody></table></div>:<div className="empty">No channel attribution data available.</div>}<p className="muted">Generated {dateTime(r.generated_at)}</p></Card></>:null}</section>}
