'use client';
import {useEffect,useRef,useState} from 'react';
import {api} from '@/lib/api';
import {dateTime} from '@/lib/format';
import {PageHeader,Card,DataToolbar,Button,Badge,Modal,Loading,ErrorState,Empty} from '@/components/ui';

type Admin={id:number|string;name:string;email:string;role?:string;status:'active'|'inactive';last_login_at?:string|null;created_at?:string};
type Role={id:number|string;name:string;description?:string|null;permissions?:string[]};
type List={data:Admin[];current_page:number;last_page:number;total:number};
type Form={name:string;email:string;role:string;status:'active'|'inactive'};
const emptyForm:Form={name:'',email:'',role:'',status:'active'};

export default function Admins(){
 const [list,setList]=useState<List|null>(null);const [roles,setRoles]=useState<Role[]>([]);const [q,setQ]=useState('');const [status,setStatus]=useState('');
 const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Admin|null>(null);const [form,setForm]=useState<Form>(emptyForm);
 const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [modalError,setModalError]=useState('');
 const searchTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 async function load(){setLoading(true);setError('');try{const p=new URLSearchParams({page:'1',per_page:'50'});if(q.trim())p.set('search',q.trim());if(status)p.set('status',status);const [a,r]=await Promise.all([api<List>(`/admin/admins?${p}`),api<Role[]|{data:Role[]}>('/admin/roles')]);setList(a.data||null);const rolePayload=r.data;setRoles(Array.isArray(rolePayload)?rolePayload:(rolePayload?.data??[]))}catch(e){setError(e instanceof Error?e.message:'Unable to load administrators')}finally{setLoading(false)}}
 useEffect(()=>{load();return()=>{if(searchTimer.current)clearTimeout(searchTimer.current)}},[status]);
 function onSearch(value:string){setQ(value);if(searchTimer.current)clearTimeout(searchTimer.current);searchTimer.current=setTimeout(load,350)}
 function open(a?:Admin){setEditing(a||null);setModalError('');setForm(a?{name:a.name,email:a.email,role:a.role||'',status:a.status}:{...emptyForm});setModal(true)}
 async function save(){if(!form.name.trim()||!form.email.trim()||!form.role){setModalError('Name, email and role are required.');return}setBusy(true);setModalError('');try{const body=JSON.stringify({...form,name:form.name.trim(),email:form.email.trim()});if(editing)await api(`/admin/admins/${editing.id}`,{method:'PUT',body});else await api('/admin/admins',{method:'POST',body});setModal(false);await load()}catch(e){setModalError(e instanceof Error?e.message:'Unable to save administrator')}finally{setBusy(false)}}
 async function toggle(a:Admin){const next=a.status==='active'?'inactive':'active';if(next==='inactive'&&!window.confirm(`Deactivate ${a.name}? They will no longer be able to access the admin panel.`))return;setBusy(true);setError('');try{await api(`/admin/admins/${a.id}/status`,{method:'POST',body:JSON.stringify({status:next})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update administrator')}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Admins & Roles" description="Control administrator access, roles and account status." action={<Button className="primary" disabled={loading||busy||roles.length===0} onClick={()=>open()}>Add administrator</Button>}/><Card><DataToolbar value={q} onChange={onSearch} placeholder="Search administrators…"><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)} disabled={loading}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></DataToolbar>{error&&<ErrorState error={error} onRetry={load}/>} {loading&&!list?<Loading/>:list?.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Administrator</th><th>Email</th><th>Role</th><th>Status</th><th>Last login</th><th/></tr></thead><tbody>{list.data.map(a=><tr key={String(a.id)}><td><b>{a.name}</b></td><td>{a.email}</td><td>{a.role||'—'}</td><td><Badge>{a.status}</Badge></td><td>{dateTime(a.last_login_at)}</td><td><div className="form-actions"><Button disabled={busy} onClick={()=>open(a)}>Edit</Button><Button disabled={busy} onClick={()=>toggle(a)}>{a.status==='active'?'Deactivate':'Activate'}</Button></div></td></tr>)}</tbody></table></div>:!loading&&!error?<Empty title="No administrators" text="Add your first administrator to start managing access."/>:null}</Card>{modal&&<Modal title={editing?'Edit administrator':'Add administrator'} onClose={()=>!busy&&setModal(false)}><div className="form-grid"><label>Name<input className="input" autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="">Select role</option>{roles.map(r=><option key={String(r.id)} value={r.name}>{r.name}</option>)}</select></label><label>Status<select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value as Form['status']})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div>{roles.length===0&&<p className="muted">No roles are available from the Core API, so a role must be configured before an administrator can be created.</p>}{modalError&&<ErrorState error={modalError}/>}<div className="form-actions"><Button disabled={busy} onClick={()=>setModal(false)}>Cancel</Button><Button className="primary" disabled={busy||roles.length===0||!form.name.trim()||!form.email.trim()||!form.role} onClick={save}>{busy?'Saving…':'Save administrator'}</Button></div></Modal>}</section>}
