'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';
import {PageHeader,Card,DataToolbar,Button,Badge,Modal,Loading,ErrorState,Empty} from '@/components/ui';

type Admin={id:number|string;name:string;email:string;role?:string;status:'active'|'inactive';last_login_at?:string|null;created_at?:string};
type Role={id:number|string;name:string;description?:string|null;permissions?:string[]};
type List={data:Admin[];current_page:number;last_page:number;total:number};
type Form={name:string;email:string;role:string;status:'active'|'inactive'};
const emptyForm:Form={name:'',email:'',role:'',status:'active'};
export default function Admins(){const [list,setList]=useState<List|null>(null);const [roles,setRoles]=useState<Role[]>([]);const [q,setQ]=useState('');const [status,setStatus]=useState('');const [modal,setModal]=useState(false);const [editing,setEditing]=useState<Admin|null>(null);const [form,setForm]=useState<Form>(emptyForm);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
async function load(){setError('');try{const p=new URLSearchParams({page:'1',per_page:'50'});if(q)p.set('search',q);if(status)p.set('status',status);const [a,r]=await Promise.all([api<List>(`/admin/admins?${p}`),api<Role[]|{data:Role[]}>('/admin/roles')]);setList(a.data||null);const rolePayload=r.data;setRoles(Array.isArray(rolePayload)?rolePayload:(rolePayload?.data??[]))}catch(e){setError(e instanceof Error?e.message:'Unable to load administrators')}}
useEffect(()=>{load()},[status]);
function open(a?:Admin){setEditing(a||null);setForm(a?{name:a.name,email:a.email,role:a.role||'',status:a.status}:{...emptyForm});setModal(true)}
async function save(){setBusy(true);setError('');try{const body=JSON.stringify(form);if(editing)await api(`/admin/admins/${editing.id}`,{method:'PUT',body});else await api('/admin/admins',{method:'POST',body});setModal(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save administrator')}finally{setBusy(false)}}
async function toggle(a:Admin){setBusy(true);try{await api(`/admin/admins/${a.id}/status`,{method:'POST',body:JSON.stringify({status:a.status==='active'?'inactive':'active'})});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update administrator')}finally{setBusy(false)}}
return <section className="content"><PageHeader title="Admins & Roles" description="Control administrator access, roles and account status." action={<Button className="primary" onClick={()=>open()}>Add administrator</Button>}/><Card><DataToolbar value={q} onChange={v=>{setQ(v);setTimeout(load,0)}} placeholder="Search administrators…"><select className="filter-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></DataToolbar>{error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:list?.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Administrator</th><th>Email</th><th>Role</th><th>Status</th><th>Last login</th><th/></tr></thead><tbody>{list.data.map(a=><tr key={String(a.id)}><td><b>{a.name}</b></td><td>{a.email}</td><td>{a.role||'—'}</td><td><Badge>{a.status}</Badge></td><td>{a.last_login_at?new Date(a.last_login_at).toLocaleString():'Never'}</td><td><div className="form-actions"><Button onClick={()=>open(a)}>Edit</Button><Button disabled={busy} onClick={()=>toggle(a)}>{a.status==='active'?'Deactivate':'Activate'}</Button></div></td></tr>)}</tbody></table></div>:<Empty title="No administrators" text="Add your first administrator to start managing access."/>}</Card>{modal&&<Modal title={editing?'Edit administrator':'Add administrator'} onClose={()=>setModal(false)}><div className="form-grid"><label>Name<input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="">Select role</option>{roles.map(r=><option key={String(r.id)} value={r.name}>{r.name}</option>)}</select></label><label>Status<select className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value as Form['status']})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label></div><div className="form-actions"><Button onClick={()=>setModal(false)}>Cancel</Button><Button className="primary" disabled={busy||!form.name||!form.email||!form.role} onClick={save}>{busy?'Saving…':'Save administrator'}</Button></div></Modal>}</section>}
