'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/api';import {apiMessage,dateTime,titleCase} from '@/lib/format';
import {PageHeader,Card,DataToolbar,Button,Badge,Loading,ErrorState,Empty,Pagination,Modal} from '@/components/ui';
type Review={id:number|string;rating:number;title?:string|null;body?:string|null;status:string;verified_purchase?:boolean;created_at?:string;product?:{id:number|string;name:string};customer?:{first_name?:string|null;last_name?:string|null;phone?:string}};type Page={data:Review[];current_page:number;last_page:number;total:number};
const statuses=['','pending','approved','rejected','hidden'];
export default function Reviews(){const [list,setList]=useState<Page|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<Review|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
async function load(){setError('');try{const p=new URLSearchParams({page:String(page),per_page:'25'});if(q)p.set('search',q);if(status)p.set('status',status);const r=await api<Page>(`/admin/reviews?${p}`);setList(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load reviews'))}}useEffect(()=>{load()},[page,status]);useEffect(()=>{const t=setTimeout(()=>{setPage(1);load()},350);return()=>clearTimeout(t)},[q]);
async function change(s:string){if(!selected)return;setBusy(true);try{const r=await api<Review>(`/admin/reviews/${selected.id}/status`,{method:'POST',body:JSON.stringify({status:s})});setSelected(r.data||null);await load()}catch(e){setError(apiMessage(e,'Unable to update review'))}finally{setBusy(false)}}
return <section className="content"><PageHeader title="Reviews" description="Moderate customer reviews before they appear on the storefront."/><Card><DataToolbar value={q} onChange={setQ} placeholder="Search review, product or customer…"><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}>{statuses.map(s=><option key={s} value={s}>{s?titleCase(s):'All statuses'}</option>)}</select><Button onClick={load}>Refresh</Button></DataToolbar>{error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:list?.data?.length?<><div className="table-wrap"><table className="table"><thead><tr><th>Review</th><th>Product</th><th>Customer</th><th>Rating</th><th>Status</th><th>Date</th><th/></tr></thead><tbody>{list.data.map(r=><tr key={String(r.id)}><td><b>{r.title||'Untitled'}</b><div className="muted">{(r.body||'').slice(0,80)}</div></td><td>{r.product?.name||'—'}</td><td>{[r.customer?.first_name,r.customer?.last_name].filter(Boolean).join(' ')||r.customer?.phone||'—'}</td><td>{'★'.repeat(Math.max(0,Math.min(5,r.rating)))} <span className="muted">{r.rating}/5</span></td><td><Badge>{titleCase(r.status)}</Badge></td><td>{dateTime(r.created_at)}</td><td><Button onClick={()=>setSelected(r)}>Moderate</Button></td></tr>)}</tbody></table></div><Pagination page={page} lastPage={list.last_page} onChange={setPage}/></>:<Empty title="No reviews" text="No reviews match the current filters."/>}</Card>{selected&&<Modal title="Review moderation" onClose={()=>setSelected(null)}><div className="card"><b>{selected.title||'Untitled review'}</b><p>{selected.body||'No written review.'}</p><div className="muted">{selected.product?.name||'Unknown product'} · {selected.rating}/5 · {selected.verified_purchase?'Verified purchase':''}</div></div><div className="form-actions" style={{marginTop:16}}>{statuses.filter(Boolean).map(s=><Button key={s} disabled={busy} className={selected.status===s?'primary':''} onClick={()=>change(s)}>{titleCase(s)}</Button>)}</div></Modal>}</section>}
