'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {ArrowLeft,Edit3,Plus,Power,Trash2} from 'lucide-react';
import {api} from '@/lib/api';import {Product,Variant} from '@/lib/types';
import {Badge,Button,Card,ErrorState,Loading,Modal,PageHeader} from '@/components/ui';

const blank={sku:'',barcode:'',size:'',color:'',price:'',mrp:'',weight_grams:'',image_url:'',quantity:'0',low_stock_threshold:'3',is_active:true};
function money(v?:number){return v==null?'—':`₹ ${Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
export default function ProductDetail(){const params=useParams<{id:string}>();const router=useRouter();const [product,setProduct]=useState<Product|null>(null);const [variant,setVariant]=useState<Variant|null>(null);const [form,setForm]=useState<any>(blank);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
async function load(){setError('');try{const r=await api<Product>(`/admin/catalog/products/${params.id}`);setProduct(r.data||null)}catch(e){setError(e instanceof Error?e.message:'Unable to load product')}}
useEffect(()=>{if(params.id)load()},[params.id]);
function start(v?:Variant){setVariant(v||null);setForm(v?{sku:v.sku||'',barcode:v.barcode||'',size:v.size||'',color:v.color||'',price:v.price??'',mrp:v.mrp??'',weight_grams:v.weight_grams??'',image_url:v.image_url||'',quantity:v.inventory?.quantity??0,low_stock_threshold:v.inventory?.low_stock_threshold??3,is_active:v.is_active!==false}:blank);setOpen(true)}
async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');const body={...form,price:form.price===''?null:Number(form.price),mrp:form.mrp===''?null:Number(form.mrp),weight_grams:form.weight_grams===''?null:Number(form.weight_grams),quantity:Number(form.quantity),low_stock_threshold:Number(form.low_stock_threshold),is_active:Boolean(form.is_active),barcode:form.barcode||null,size:form.size||null,color:form.color||null,image_url:form.image_url||null};try{await api(`/admin/catalog/products/${params.id}/variants${variant?`/${variant.id}`:''}`,{method:variant?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save variant')}finally{setBusy(false)}}
async function deactivate(v:Variant){if(!confirm(`Deactivate ${v.sku||'this variant'}?`))return;try{await api(`/admin/catalog/products/${params.id}/variants/${v.id}`,{method:'DELETE'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to deactivate variant')}}
return <section className="content"><Button onClick={()=>router.push('/products')}><ArrowLeft size={15}/> Products</Button>{error&&<ErrorState error={error} onRetry={load}/>} {!product&&!error?<Loading/>:product&&<><PageHeader title={product.name} description={`${product.slug} · ${product.status}`} action={<Button className="primary" onClick={()=>start()}><Plus size={15}/> Add variant</Button>}/><div className="stats-grid"><Card><span>Base price</span><strong>{money(product.price)}</strong></Card><Card><span>MRP</span><strong>{money(product.mrp)}</strong></Card><Card><span>Variants</span><strong>{product.variants?.length||0}</strong></Card></div><Card><div className="section-head"><div><h2>Variants</h2><p>Manage SKU, size, colour, pricing and opening stock.</p></div></div>{product.variants?.length?<div className="table-wrap"><table className="table"><thead><tr><th>SKU</th><th>Size</th><th>Colour</th><th>Price</th><th>Stock</th><th>Status</th><th/></tr></thead><tbody>{product.variants.map(v=><tr key={String(v.id)}><td><b>{v.sku||'—'}</b><div style={{color:'#999',marginTop:3}}>{v.barcode||''}</div></td><td>{v.size||'—'}</td><td>{v.color||'—'}</td><td>{money(v.price??product.price)}</td><td>{v.inventory?.quantity??0} <span style={{color:'#999'}}>({v.inventory?.reserved_quantity??v.inventory?.reserved??0} reserved)</span></td><td><Badge>{v.is_active===false?'inactive':'active'}</Badge></td><td><Button onClick={()=>start(v)}><Edit3 size={14}/></Button>{v.is_active!==false&&<Button onClick={()=>deactivate(v)}><Power size={14}/></Button>}</td></tr>)}</tbody></table></div>:<div className="empty"><strong>No variants</strong><span>Create at least one sellable SKU before publishing the product.</span></div>}</Card>{open&&<Modal title={variant?'Edit variant':'Add variant'} onClose={()=>setOpen(false)}><form className="form" onSubmit={save}><div className="form-grid">{[['sku','SKU'],['barcode','Barcode'],['size','Size'],['color','Colour'],['price','Price'],['mrp','MRP'],['weight_grams','Weight (g)'],['quantity','Opening stock'],['low_stock_threshold','Low-stock threshold']].map(([k,l])=><label key={k}>{l}<input required={k==='sku'} type={['price','mrp','weight_grams','quantity','low_stock_threshold'].includes(k)?'number':'text'} step={['price','mrp','weight_grams'].includes(k)?'0.01':undefined} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><label>Image URL<input type="url" value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active / sellable</label><div className="form-actions"><Button type="button" onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy}>{busy?'Saving…':variant?'Save variant':'Create variant'}</Button></div></form></Modal>}</>}</section>}
