'use client';
import {useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {Badge,Button,Card,PageHeader} from '@/components/ui';

type Endpoint={method:'GET'|'POST'|'PUT'|'PATCH'|'DELETE';path:string;area:string;description:string;body?:string};
const endpoints:Endpoint[]=[
['GET','/admin/control-center','Control Center','Unified commerce control-center overview.'],
['GET','/admin/control-center/dashboard','Control Center','Operational dashboard.'],
['GET','/admin/control-center/products','Control Center','Product operations view.'],
['GET','/admin/control-center/orders','Control Center','Order operations view.'],
['GET','/admin/control-center/inventory','Control Center','Inventory operations view.'],
['GET','/admin/control-center/customers','Control Center','Customer operations view.'],
['GET','/admin/control-center/operations','Control Center','Operational reliability view.'],
['GET','/admin/analytics','Analytics','Commerce analytics.'],
['GET','/admin/analytics/daily','Analytics','Daily analytics.'],
['GET','/admin/analytics/overview','Analytics','Analytics overview.'],
['GET','/admin/analytics/products','Analytics','Product analytics.'],
['POST','/admin/analytics/rebuild-daily','Analytics','Rebuild daily analytics.'],
['GET','/admin/finance/reports/closing','Finance','Closing report.'],
['GET','/admin/finance/reports/invoices','Finance','Invoice report.'],
['GET','/admin/finance/reports/loyalty','Finance','Loyalty report.'],
['GET','/admin/finance/reports/refunds','Finance','Refund report.'],
['GET','/admin/finance/reports/tax','Finance','Tax report.'],
['GET','/admin/finance/reports/wallet','Finance','Wallet report.'],
['GET','/admin/ops/metrics','Operations','Reliability metrics.'],
['GET','/admin/ops/audit','Operations','Operations audit stream.'],
['GET','/admin/ops/inventory-reservations','Operations','Inventory reservations.'],
['POST','/admin/ops/inventory-reservations/expire','Operations','Expire stale reservations.'],
['GET','/admin/security/me','Security','Current operator security profile.'],
['GET','/admin/security/permissions','Security','Available permissions.'],
['GET','/admin/security/roles','Security','RBAC roles.'],
['GET','/admin/security/users','Security','Security users.'],
['GET','/admin/security/audit','Security','Security audit events.'],
['GET','/admin/settings','Settings','Commerce settings.'],
['PUT','/admin/settings','Settings','Update commerce settings.','{}'],
['GET','/admin/notifications/outbox','Notifications','Notification delivery outbox.'],
['GET','/admin/notifications/templates','Notifications','Notification templates.'],
['POST','/admin/notifications/templates','Notifications','Create notification template','{}'],
['POST','/admin/notifications/test','Notifications','Queue a notification test','{}'],
['GET','/admin/automations','Automation','Automation rules.'],
['PUT','/admin/automations/{automation}','Automation','Update an automation','{}'],
['POST','/admin/automations/{automation}/toggle','Automation','Toggle an automation','{}'],
['GET','/admin/commerce-agent/conversations','Commerce AI','Agent conversations.'],
['GET','/admin/commerce-agent/conversations/{conversation}/messages','Commerce AI','Conversation messages.'],
['POST','/admin/commerce-agent/conversations/{conversation}/handoff','Commerce AI','Hand off agent conversation','{}'],
['POST','/admin/ai/intent','Commerce AI','Run commerce AI intent','{}'],
['POST','/admin/ai/product-content','Commerce AI','Generate product content','{}'],
['GET','/admin/customer-360','CRM','Customer 360 dashboard.'],
['GET','/admin/customer-360/{customer}','CRM','Customer 360 profile.'],
['POST','/admin/customer-360/merge/preview','CRM','Preview customer merge','{}'],
['POST','/admin/customer-360/merge','CRM','Merge customer records','{}'],
['POST','/admin/customer-360/{customer}/notes','CRM','Add customer note','{}'],
['POST','/admin/customer-360/{customer}/segments','CRM','Assign customer segment','{}'],
['POST','/admin/customer-360/{customer}/tags','CRM','Add customer tag','{}'],
['DELETE','/admin/customer-360/{customer}/tags/{tag}','CRM','Remove customer tag'],
['GET','/admin/inventory/warehouses','Inventory','Warehouses.'],
['GET','/admin/inventory/warehouse-stock','Inventory','Warehouse stock.'],
['POST','/admin/inventory/warehouse-adjust','Inventory','Adjust warehouse stock','{}'],
['POST','/admin/inventory/bulk-stock','Inventory','Bulk stock update','{}'],
['POST','/admin/actions/inventory/adjust','Inventory','Controlled inventory adjustment','{}'],
['POST','/admin/actions/warehouses/transfer','Inventory','Transfer inventory between warehouses','{}'],
['GET','/admin/fulfillment/transfers','Fulfillment','Fulfillment transfers.'],
['POST','/admin/fulfillment/transfers','Fulfillment','Create fulfillment transfer','{}'],
['POST','/admin/fulfillment/transfers/{transfer}/receive','Fulfillment','Receive transfer','{}'],
['POST','/admin/fulfillment/allocations/{allocation}/pick','Fulfillment','Pick allocation','{}'],
['POST','/admin/fulfillment/allocations/{allocation}/pack','Fulfillment','Pack allocation','{}'],
['POST','/admin/fulfillment/allocations/{allocation}/cancel','Fulfillment','Cancel allocation','{}'],
['GET','/admin/integrations/woocommerce/status','Integrations','WooCommerce status.'],
['POST','/admin/integrations/woocommerce/sync','Integrations','Run WooCommerce sync','{}'],
['POST','/admin/integrations/woocommerce/sync/categories','Integrations','Sync WooCommerce categories','{}'],
['POST','/admin/integrations/woocommerce/sync/products','Integrations','Sync WooCommerce products','{}'],
['POST','/admin/integrations/woocommerce/sync/orders','Integrations','Sync WooCommerce orders','{}'],
['GET','/admin/whatsapp/status','WhatsApp','WhatsApp status.'],
['GET','/admin/whatsapp/templates','WhatsApp','WhatsApp templates.'],
['POST','/admin/whatsapp/templates/sync','WhatsApp','Sync WhatsApp templates','{}'],
['GET','/admin/whatsapp/conversations','WhatsApp','WhatsApp inbox.'],
['GET','/admin/support/command-center','Support','Support command center.'],
['GET','/admin/support/tickets','Support','Customer support tickets.'],
['GET','/admin/support/tickets/{ticket}','Support','Support ticket detail.'],
['PATCH','/admin/support/tickets/{ticket}','Support','Update support ticket','{}'],
['POST','/admin/support/tickets/{ticket}/messages','Support','Reply to support ticket','{}'],
['POST','/admin/support/tickets/{ticket}/notify-customer','Support','Notify ticket customer','{}'],
['POST','/admin/support/tickets/{ticket}/reopen','Support','Reopen ticket','{}'],
['POST','/admin/support/tickets/{ticket}/resolve','Support','Resolve ticket','{}'],
['POST','/admin/actions/orders/{order}/transition','Orders','Controlled order transition','{}'],
['POST','/admin/orders/{order}/confirm-cod','Orders','Confirm COD order','{}'],
['POST','/admin/orders/{order}/fulfillment/allocate','Orders','Allocate order fulfillment','{}'],
['POST','/admin/orders/{order}/invoice','Orders','Issue invoice','{}'],
['POST','/admin/orders/{order}/refund','Orders','Create order refund','{}'],
['POST','/admin/orders/{order}/shipping/create','Shipping','Create order shipment','{}'],
['POST','/admin/shipping/{shipment}/pickup','Shipping','Request pickup','{}'],
['POST','/admin/shipping/{shipment}/label','Shipping','Generate shipping label','{}'],
['POST','/admin/shipping/{shipment}/sync','Shipping','Sync shipment','{}'],
['POST','/admin/shipping/{shipment}/cancel','Shipping','Cancel shipment','{}'],
['POST','/admin/shipping/shipments/{shipment}/awb','Shipping','Generate AWB','{}'],
['POST','/admin/shipping/shipments/{shipment}/track','Shipping','Refresh tracking','{}'],
['POST','/admin/returns/{return}/qc','Returns','Record return QC','{}'],
['POST','/admin/returns/{return}/exchange','Returns','Create exchange','{}'],
['POST','/admin/returns/{return}/reverse-shipment','Returns','Create reverse shipment','{}'],
['POST','/admin/returns/{return}/status','Returns','Update return status','{}'],
['POST','/admin/reverse-shipments/{shipment}/status','Returns','Update reverse shipment status','{}'],
['POST','/admin/ndr/{case}/resolve','Returns','Resolve NDR case','{}'],
['POST','/admin/admins/{admin}/status','Admins','Update admin status','{}'],
['GET','/admin/roles','Admins','Available admin roles.'],
['GET','/admin/audit-logs','Audit','Admin audit logs.'],
['POST','/admin/search/rebuild-relations','Search','Rebuild search relations','{}'],
];
const [method,path,area,description,body]=[] as never;
const rows=endpoints.map(([method,path,area,description,body])=>({method,path,area,description,body}));

export default function ApiOps(){
 const [q,setQ]=useState('');const [area,setArea]=useState('All');const [selected,setSelected]=useState<Endpoint|null>(null);const [params,setParams]=useState<Record<string,string>>({});const [payload,setPayload]=useState('{}');const [result,setResult]=useState('');const [busy,setBusy]=useState(false);
 const areas=useMemo(()=>['All',...Array.from(new Set(endpoints.map(e=>e[2])))],[ ]);
 const filtered=useMemo(()=>rows.filter(e=>(area==='All'||e.area===area)&&(!q||`${e.method} ${e.path} ${e.description}`.toLowerCase().includes(q.toLowerCase()))),[q,area]);
 function select(e:Endpoint){setSelected(e);setPayload(e[4]||'{}');const found=e[1].match(/\{([^}]+)\}/g)||[];const next:Record<string,string>={};found.forEach(x=>next[x.slice(1,-1)]='');setParams(next);setResult('')}
 async function execute(){if(!selected)return;setBusy(true);setResult('');try{let p=selected[1];Object.entries(params).forEach(([k,v])=>{p=p.replace(`{${k}}`,encodeURIComponent(v))});const opts:RequestInit={method:selected[0]};if(!['GET','DELETE'].includes(selected[0]))opts.body=payload;const r=await api<any>(p,opts);setResult(JSON.stringify(r,null,2))}catch(e){setResult(JSON.stringify({error:e instanceof Error?e.message:String(e)},null,2))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="API Operations" description="Complete PriyasaCore admin route coverage for advanced operational workflows."/><Card><div className="toolbar"><div className="searchbox"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search endpoint, area or action…"/></div><select value={area} onChange={e=>setArea(e.target.value)}>{areas.map(a=><option key={a}>{a}</option>)}</select></div><div className="table-wrap"><table className="table"><thead><tr><th>Method</th><th>Endpoint</th><th>Area</th><th>Purpose</th><th/></tr></thead><tbody>{filtered.map((e,i)=><tr key={`${e[0]}-${e[1]}-${i}`}><td><Badge>{e[0]}</Badge></td><td><code>{e[1]}</code></td><td>{e[2]}</td><td>{e[3]}</td><td><Button onClick={()=>select(e)}>Open</Button></td></tr>)}</tbody></table></div></Card>{selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="modal"><div className="modal-head"><h2>{selected[0]} {selected[1]}</h2><button onClick={()=>setSelected(null)}>×</button></div><p className="muted">{selected[3]}</p>{Object.keys(params).map(k=><label className="form" key={k}>Path parameter: {k}<input value={params[k]} onChange={e=>setParams({...params,[k]:e.target.value})}/></label>)}{!['GET','DELETE'].includes(selected[0])&&<label className="form">JSON request body<textarea className="note" value={payload} onChange={e=>setPayload(e.target.value)}/></label>}<div className="form-actions"><Button onClick={()=>setSelected(null)}>Close</Button><Button className="primary" disabled={busy} onClick={execute}>{busy?'Calling…':'Execute API'}</Button></div>{result&&<pre style={{maxHeight:320,overflow:'auto',background:'#111',color:'#eee',padding:14,borderRadius:10,fontSize:11,marginTop:14}}>{result}</pre>}</div></div>}</section>;
}
