'use client';
import {useEffect,useMemo,useState} from 'react';
import {api} from '@/lib/api';
import {Badge,Button,Card,ErrorState,Loading,PageHeader} from '@/components/ui';

type Route={method:string;uri:string;name?:string;action?:string;middleware?:string[]};
function normalize(value:any):Route[]{const raw=value?.data??value?.routes??value;const list=Array.isArray(raw)?raw:(raw&&typeof raw==='object'?Object.entries(raw).map(([uri,v]:any)=>({uri,...(typeof v==='object'?v:{})})):[]);return list.map((r:any)=>({method:String(r.method||r.methods||'GET').toUpperCase().replace(/\[|\]/g,''),uri:String(r.uri||r.path||r.route||''),name:r.name,action:r.action||r.controller,middleware:Array.isArray(r.middleware)?r.middleware:[]})).filter(r=>r.uri.includes('/admin/'));}
export default function ApiOps(){const [routes,setRoutes]=useState<Route[]>([]);const [q,setQ]=useState('');const [method,setMethod]=useState('ALL');const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<Route|null>(null);const [pathValues,setPathValues]=useState<Record<string,string>>({});const [body,setBody]=useState('{}');const [result,setResult]=useState('');const [busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await api<any>('/docs/openapi.routes.json');setRoutes(normalize(r));}catch(e){setError(e instanceof Error?e.message:'Unable to load API route inventory')}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const methods=useMemo(()=>['ALL',...Array.from(new Set(routes.map(r=>r.method)))],[routes]);const filtered=useMemo(()=>routes.filter(r=>(method==='ALL'||r.method===method)&&(!q||`${r.method} ${r.uri} ${r.name||''} ${r.action||''}`.toLowerCase().includes(q.toLowerCase()))),[routes,q,method]);
 function open(r:Route){const next:Record<string,string>={};(r.uri.match(/\{[^}]+\}/g)||[]).forEach(x=>next[x.slice(1,-1)]='');setPathValues(next);setBody('{}');setResult('');setSelected(r)}
 async function execute(){if(!selected)return;setBusy(true);setResult('');try{let uri=selected.uri;Object.entries(pathValues).forEach(([k,v])=>uri=uri.replace(`{${k}}`,encodeURIComponent(v)));const opts:RequestInit={method:selected.method};if(!['GET','HEAD','DELETE'].includes(selected.method))opts.body=body;const r=await api<any>(uri.replace(/^api\/v1/,''),opts);setResult(JSON.stringify(r,null,2));}catch(e){setResult(JSON.stringify({error:e instanceof Error?e.message:String(e)},null,2))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="API Operations" description="Live PriyasaCore admin route inventory. Every /admin API route exposed by the backend can be inspected and executed here." action={<Button onClick={load}>Refresh routes</Button>}/><Card><div className="toolbar"><div className="searchbox"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search route, controller or capability…"/></div><select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m}>{m}</option>)}</select><Badge>{filtered.length} routes</Badge></div>{error&&<ErrorState error={error} onRetry={load}/>} {loading?<Loading/>:<div className="table-wrap"><table className="table"><thead><tr><th>Method</th><th>Route</th><th>Name</th><th>Controller</th><th/></tr></thead><tbody>{filtered.map((r,i)=><tr key={`${r.method}-${r.uri}-${i}`}><td><Badge>{r.method}</Badge></td><td><code>{r.uri}</code></td><td>{r.name||'—'}</td><td>{r.action||'—'}</td><td><Button onClick={()=>open(r)}>Open</Button></td></tr>)}</tbody></table></div>}</Card>{selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="modal"><div className="modal-head"><h2>{selected.method} {selected.uri}</h2><button onClick={()=>setSelected(null)}>×</button></div><p className="muted">{selected.action||selected.name||'PriyasaCore admin endpoint'}</p>{Object.keys(pathValues).map(k=><label className="form" key={k}>Path parameter: {k}<input value={pathValues[k]} onChange={e=>setPathValues({...pathValues,[k]:e.target.value})}/></label>)}{!['GET','HEAD','DELETE'].includes(selected.method)&&<label className="form">JSON request body<textarea className="note" value={body} onChange={e=>setBody(e.target.value)} spellCheck={false}/></label>}<div className="form-actions"><Button onClick={()=>setSelected(null)}>Close</Button><Button className="primary" disabled={busy} onClick={execute}>{busy?'Calling…':'Execute API'}</Button></div>{result&&<pre style={{maxHeight:360,overflow:'auto',background:'#111',color:'#eee',padding:14,borderRadius:10,fontSize:11,marginTop:14}}>{result}</pre>}</div></div>}</section>}
