'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowUp,Copy,Eye,GripVertical,Image as ImageIcon,LayoutTemplate,Plus,RefreshCw,Save,Settings2,Trash2} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Badge,Button,Card,ErrorState,Loading,Modal,PageHeader} from '@/components/ui';

type Section={id:number|string;key:string;type:string;title?:string|null;subtitle?:string|null;image_url?:string|null;mobile_image_url?:string|null;cta_label?:string|null;cta_href?:string|null;payload?:Record<string,any>|null;content?:Record<string,any>|null;sort_order:number;is_active:boolean;starts_at?:string|null;ends_at?:string|null;updated_at?:string};
type List={data:Section[];current_page:number;last_page:number};
type Form={key:string;type:string;title:string;subtitle:string;image_url:string;mobile_image_url:string;cta_label:string;cta_href:string;sort_order:number;is_active:boolean;starts_at:string;ends_at:string;payload:string};
const types=[
 ['hero_slider','Hero carousel','Large mobile/desktop hero with multiple slides'],
 ['trust_strip','Trust strip','Returns, COD, quality and delivery promises'],
 ['products-latest','New arrivals','Live Core catalog product rail'],
 ['products-best','Best sellers','Live Core catalog product rail'],
 ['products-sale','Flash sale','Discounted Core catalog products'],
 ['editorial_rail','Editorial image rail','Six-card fashion/editorial discovery rail'],
 ['offer','Offer banner','Campaign or promotional banner'],
 ['reviews','Reviews carousel','Customer review/social-proof carousel'],
 ['banner','Image banner','Full-width campaign/collection banner'],
 ['text','Rich text','SEO/content block'],
];
const templates:Record<string,any>={
 hero_slider:{items:[{title:'New Season',subtitle:'Style it your way',image_url:'',cta_label:'Shop Now',cta_href:'/shop'},{title:'Festive Collection',subtitle:'Designed for every occasion',image_url:'',cta_label:'Explore',cta_href:'/shop'}]},
 trust_strip:{items:[{icon:'return',title:'7 Days Easy Return',subtitle:'Simple & hassle-free'},{icon:'shield',title:'Premium Quality',subtitle:'Made with care'},{icon:'cod',title:'COD Available',subtitle:'Pay when it arrives'},{icon:'truck',title:'Pan India Delivery',subtitle:'Across India'}]},
 'products-latest':{query:{sort:'newest',limit:12,view_all_href:'/shop?sort=newest'}},
 'products-best':{query:{sort:'popular',limit:30,view_all_href:'/shop?sort=popular'}},
 'products-sale':{query:{sort:'sale',limit:12,view_all_href:'/shop?sort=sale',flash_sale:true,end_at:null}},
 editorial_rail:{items:[{title:'Latest Arrivals',subtitle:'Shop new styles',image_url:'',cta_href:'/shop?sort=newest'},{title:'Festive Collection',subtitle:'Made for moments',image_url:'',cta_href:'/shop'},{title:'Top Picks',subtitle:'Trending now',image_url:'',cta_href:'/shop?sort=popular'},{title:'Everyday Edit',subtitle:'Easy wardrobe staples',image_url:'',cta_href:'/shop'},{title:'Workwear Edit',subtitle:'Polished essentials',image_url:'',cta_href:'/shop'},{title:'Weekend Styles',subtitle:'Relaxed fashion',image_url:'',cta_href:'/shop'}]},
 offer:{items:[{title:'FLAT 30% OFF',subtitle:'Limited time offer',image_url:'',cta_label:'Shop Sale',cta_href:'/shop?sort=sale'}]},
 reviews:{items:[{rating:5,name:'Verified customer',text:'Beautiful quality and fit.',product:'Priyasa bestseller'},{rating:5,name:'Verified customer',text:'Fast delivery and lovely packaging.',product:'Priyasa collection'},{rating:4,name:'Verified customer',text:'Exactly as shown. Very happy.',product:'New arrival'}]},
};
const blank:Form={key:'home-new-section',type:'products-latest',title:'New Arrivals',subtitle:'Fresh styles just landed',image_url:'',mobile_image_url:'',cta_label:'View All',cta_href:'/shop',sort_order:10,is_active:true,starts_at:'',ends_at:'',payload:JSON.stringify(templates['products-latest'],null,2)};
function labelFor(type:string){return types.find(x=>x[0]===type)?.[1]||type}
function makeForm(s?:Section):Form{const payload=s?.payload||s?.content||templates[s?.type||'']||{};return s?{key:s.key,type:s.type,title:s.title||'',subtitle:s.subtitle||'',image_url:s.image_url||'',mobile_image_url:s.mobile_image_url||'',cta_label:s.cta_label||'View All',cta_href:s.cta_href||'/shop',sort_order:Number(s.sort_order||0),is_active:s.is_active!==false,starts_at:s.starts_at||'',ends_at:s.ends_at||'',payload:JSON.stringify(payload,null,2)}:{...blank}}
export default function HomeBuilder(){
 const [list,setList]=useState<List|null>(null);const [editing,setEditing]=useState<Section|null>(null);const [form,setForm]=useState<Form>(blank);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [preview,setPreview]=useState(true);
 async function load(){setError('');try{const r=await api<List>('/admin/cms?per_page=100');setList(r.data||null)}catch(e){setError(apiMessage(e,'Unable to load storefront sections'))}}
 useEffect(()=>{load()},[]);
 const sections=useMemo(()=>[...(list?.data||[])].sort((a,b)=>a.sort_order-b.sort_order),[list]);
 function start(s?:Section){setEditing(s||null);setForm(makeForm(s));setOpen(true)}
 function changeType(type:string){setForm(f=>({...f,type,payload:JSON.stringify(templates[type]||{},null,2),title:f.title||labelFor(type)}))}
 async function save(){setBusy(true);setError('');try{let payload:any;try{payload=JSON.parse(form.payload||'{}')}catch{throw new Error('Payload JSON is invalid.')}const body={key:form.key,type:form.type,title:form.title||null,subtitle:form.subtitle||null,image_url:form.image_url||null,mobile_image_url:form.mobile_image_url||null,cta_label:form.cta_label||null,cta_href:form.cta_href||null,payload,sort_order:Number(form.sort_order||0),is_active:form.is_active,starts_at:form.starts_at||null,ends_at:form.ends_at||null};await api(editing?`/admin/cms/${editing.id}`:'/admin/cms',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);await load()}catch(e){setError(apiMessage(e,'Unable to save section'))}finally{setBusy(false)}}
 async function remove(s:Section){if(!confirm(`Delete ${s.title||s.key}?`))return;setBusy(true);try{await api(`/admin/cms/${s.id}`,{method:'DELETE'});await load()}catch(e){setError(apiMessage(e,'Unable to delete section'))}finally{setBusy(false)}}
 async function patch(s:Section,patch:Record<string,any>){try{await api(`/admin/cms/${s.id}`,{method:'PUT',body:JSON.stringify({...makeForm(s),...patch,payload:s.payload||s.content||{}})});await load()}catch(e){setError(apiMessage(e,'Unable to update section'))}}
 async function move(index:number,dir:-1|1){const a=sections[index],b=sections[index+dir];if(!a||!b)return;setBusy(true);setError('');try{await api(`/admin/cms/${a.id}`,{method:'PUT',body:JSON.stringify({...makeForm(a),sort_order:b.sort_order,payload:a.payload||a.content||{}})});await api(`/admin/cms/${b.id}`,{method:'PUT',body:JSON.stringify({...makeForm(b),sort_order:a.sort_order,payload:b.payload||b.content||{}})});await load()}catch(e){setError(apiMessage(e,'Unable to reorder sections'))}finally{setBusy(false)}}
 async function duplicate(s:Section){setBusy(true);setError('');try{const next={...makeForm(s),key:`${s.key}-copy-${Date.now()}`,title:`${s.title||s.key} Copy`,sort_order:s.sort_order+1,payload:JSON.stringify(s.payload||s.content||{},null,2)};const payload=JSON.parse(next.payload);await api('/admin/cms',{method:'POST',body:JSON.stringify({...next,payload})});await load()}catch(e){setError(apiMessage(e,'Unable to duplicate section'))}finally{setBusy(false)}}
 return <section className="content home-builder"><PageHeader title="Storefront Home" description="Build the live PRIYASA home page from Core catalog data and managed CMS sections." action={<div className="form-actions"><Link className="btn" href="https://priyasa.com" target="_blank" rel="noreferrer"><Eye size={14}/> Preview store</Link><Button onClick={load} disabled={busy}><RefreshCw size={14}/> Refresh</Button><Button className="primary" onClick={()=>start()}><Plus size={15}/> Add section</Button></div>}/>{error&&<ErrorState error={error} onRetry={load}/>} {!list&&!error?<Loading/>:<>
 <div className="home-builder-summary"><Card><div className="home-summary-icon"><LayoutTemplate size={18}/></div><div><b>{sections.length} sections</b><span>Managed storefront blocks</span></div></Card><Card><div className="home-summary-icon"><ImageIcon size={18}/></div><div><b>{sections.filter(s=>s.type==='hero_slider'||s.type==='banner'||s.type==='offer').length} visual campaigns</b><span>Hero, banners and offers</span></div></Card><Card><div className="home-summary-icon"><Settings2 size={18}/></div><div><b>{sections.filter(s=>s.type.startsWith('products-')).length} product rails</b><span>Live PriyasaCore catalog</span></div></Card><Card><div className="home-summary-icon"><GripVertical size={18}/></div><div><b>Drag-free ordering</b><span>Use arrows for deterministic order</span></div></Card></div>
 <div className="home-builder-layout"><Card className="home-section-list"><div className="section-head"><div><h2>Home sections</h2><p>Order here is the order delivered by the storefront Home API.</p></div><label className="home-preview-toggle"><input type="checkbox" checked={preview} onChange={e=>setPreview(e.target.checked)}/> Live structure</label></div>{sections.length?sections.map((s,i)=><article className={`home-section-row ${s.is_active?'':'is-disabled'}`} key={String(s.id)}><div className="home-row-grip"><GripVertical size={16}/></div><div className="home-row-order"><button disabled={i===0||busy} onClick={()=>move(i,-1)} aria-label="Move up"><ArrowUp size={14}/></button><span>{i+1}</span><button disabled={i===sections.length-1||busy} onClick={()=>move(i,1)} aria-label="Move down"><ArrowDown size={14}/></button></div><div className="home-row-main"><div className="home-row-title"><b>{s.title||s.key}</b><Badge>{labelFor(s.type)}</Badge><Badge>{s.is_active?'Live':'Draft'}</Badge></div><span>{s.subtitle||s.key}</span><small>{s.key} · sort {s.sort_order}</small></div><div className="home-row-actions"><button onClick={()=>patch(s,{is_active:!s.is_active})} disabled={busy}>{s.is_active?'Disable':'Publish'}</button><button onClick={()=>duplicate(s)} disabled={busy}><Copy size={13}/></button><button onClick={()=>start(s)} disabled={busy}><Settings2 size={13}/></button><button onClick={()=>remove(s)} disabled={busy} className="danger"><Trash2 size={13}/></button></div></article>):<div className="empty"><strong>No home sections</strong><span>Create a hero, product rail or campaign block to start building the storefront.</span></div>}</Card>
 {preview&&<Card className="home-structure-preview"><div className="card-title">Storefront composition</div><div className="preview-device"><div className="preview-top"><span>PRIYASA</span><span>Home API</span></div>{sections.map((s,i)=><div className={`preview-block type-${s.type.replace(/[^a-z0-9_-]/g,'')}`} key={String(s.id)}><span>{i+1}</span><div><b>{s.title||labelFor(s.type)}</b><small>{labelFor(s.type)} · {s.is_active?'live':'draft'}</small></div></div>)}</div></Card>}
 </div></>}</section>}
