'use client';

import {useEffect,useState} from 'react';
import {Plus,Power,Trash2,RefreshCw} from 'lucide-react';
import {api} from '@/lib/api';
import {API_ROUTES} from '@/lib/api-contract';
import {Badge,Button,Card,ErrorState,Loading,Modal,PageHeader} from '@/components/ui';

type Theme={id:number;key:string;name:string;type?:string;status?:string;version?:number;priority?:number;is_active:boolean;starts_at?:string|null;ends_at?:string|null;tokens?:Record<string,unknown>;assets?:Record<string,unknown>;decorations?:Record<string,unknown>;features?:Record<string,unknown>};
const empty={key:'',name:'',type:'storefront',status:'draft',priority:0,tokens:'{}',assets:'{}',decorations:'{}',features:'{}',starts_at:'',ends_at:''};

export default function Themes(){
 const [themes,setThemes]=useState<Theme[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Theme|null>(null),[form,setForm]=useState({...empty}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setError('');try{const r=await api<Theme[]>(API_ROUTES.cms.themes);setThemes(r.data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load themes')}}
 useEffect(()=>{load()},[]);
 function edit(t?:Theme){setEditing(t||null);setForm(t?{key:t.key,name:t.name,type:t.type||'storefront',status:t.status||'draft',priority:t.priority||0,tokens:JSON.stringify(t.tokens||{},null,2),assets:JSON.stringify(t.assets||{},null,2),decorations:JSON.stringify(t.decorations||{},null,2),features:JSON.stringify(t.features||{},null,2),starts_at:t.starts_at||'',ends_at:t.ends_at||''}:{...empty});setOpen(true)}
 async function save(){setBusy(true);setError('');try{const json=(v:string)=>{try{return JSON.parse(v||'{}')}catch{throw new Error('Theme JSON fields must be valid JSON.')}};const body={key:form.key.trim(),name:form.name.trim(),type:form.type,status:form.status,priority:Number(form.priority),tokens:json(form.tokens),assets:json(form.assets),decorations:json(form.decorations),features:json(form.features),starts_at:form.starts_at||null,ends_at:form.ends_at||null};await api(editing?API_ROUTES.cms.theme(editing.id):API_ROUTES.cms.themes,{method:editing?'PUT':'POST',body:JSON.stringify(body)});setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save theme')}finally{setBusy(false)}}
 async function toggle(t:Theme){setBusy(true);setError('');try{await api(t.is_active?API_ROUTES.cms.deactivateTheme(t.id):API_ROUTES.cms.activateTheme(t.id),{method:'POST',body:'{}'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to change theme')}finally{setBusy(false)}}
 async function remove(t:Theme){if(!confirm('Delete this inactive theme?'))return;setBusy(true);try{await api(API_ROUTES.cms.theme(t.id),{method:'DELETE',body:'{}'});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete theme')}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Theme Studio" description="Manage storefront themes, schedules, tokens and activation without editing storefront code." action={<div className="form-actions"><Button onClick={load} disabled={busy}><RefreshCw size={14}/> Refresh</Button><Button className="primary" onClick={()=>edit()}><Plus size={14}/> New theme</Button></div>}/>{error&&<ErrorState error={error} onRetry={load}/>} {!themes.length&&!error?<Loading/>:<Card><div className="table-wrap"><table className="table"><thead><tr><th>Theme</th><th>Status</th><th>Priority</th><th>Schedule</th><th/><th/></tr></thead><tbody>{themes.map(t=><tr key={t.id}><td><b>{t.name}</b><div className="muted">{t.key} · v{t.version||1}</div></td><td><Badge>{t.is_active?'Active':t.status||'Draft'}</Badge></td><td>{t.priority||0}</td><td>{t.starts_at||'—'} → {t.ends_at||'—'}</td><td><div className="form-actions"><Button onClick={()=>edit(t)}>Edit</Button><Button disabled={busy} onClick={()=>toggle(t)}><Power size={13}/>{t.is_active?'Deactivate':'Activate'}</Button></div></td><td>{!t.is_active&&<Button onClick={()=>remove(t)}><Trash2 size={13}/></Button>}</td></tr>)}</tbody></table></div></Card>}{open&&<Modal title={editing?'Edit theme':'Create theme'} onClose={()=>setOpen(false)}><div className="form"><div className="form-grid"><label>Key<input value={form.key} onChange={e=>setForm({...form,key:e.target.value})}/></label><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Type<input value={form.type} onChange={e=>setForm({...form,type:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Priority<input type="number" min="0" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})}/></label><label>Starts at<input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Ends at<input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label></div>{[['tokens','Tokens JSON'],['assets','Assets JSON'],['decorations','Decorations JSON'],['features','Features JSON']].map(([k,l])=><label key={k}>{l}<textarea rows={5} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<div className="form-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save theme'}</Button></div></div></Modal>}</section>
}