'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { apiMessage } from '@/lib/format';
import { PageHeader, Card, Button, Badge, Loading, ErrorState, Empty, Modal } from '@/components/ui';

type Theme={id:number|string;key:string;name:string;type?:string;status?:string;version?:number;priority?:number;is_active?:boolean;starts_at?:string|null;ends_at?:string|null;tokens?:Record<string,unknown>;assets?:Record<string,unknown>;decorations?:Record<string,unknown>;features?:Record<string,unknown>};

type Result={success?:boolean;data?:Theme[]|Theme;message?:string};
const blank={key:'',name:'',type:'campaign',status:'draft',priority:0,tokens:'{}',assets:'{}',decorations:'{}',features:'{}',starts_at:'',ends_at:''};

export default function ThemeManager(){
 const [themes,setThemes]=useState<Theme[]>([]),[editing,setEditing]=useState<Theme|null>(null),[open,setOpen]=useState(false),[form,setForm]=useState({...blank}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setError('');try{const r=await api<Result>('/admin/cms/themes');setThemes(Array.isArray(r.data)?r.data:[])}catch(e){setError(apiMessage(e,'Unable to load themes'))}}
 useEffect(()=>{load()},[]);
 function edit(t?:Theme){setEditing(t||null);setForm(t?{key:t.key,name:t.name,type:t.type||'campaign',status:t.status||'draft',priority:t.priority||0,tokens:JSON.stringify(t.tokens||{},null,2),assets:JSON.stringify(t.assets||{},null,2),decorations:JSON.stringify(t.decorations||{},null,2),features:JSON.stringify(t.features||{},null,2),starts_at:t.starts_at||'',ends_at:t.ends_at||''}:{...blank});setOpen(true)}
 async function save(){setBusy(true);setError('');try{const parse=(s:string)=>JSON.parse(s||'{}');const body={...form,priority:Number(form.priority),tokens:parse(form.tokens),assets:parse(form.assets),decorations:parse(form.decorations),features:parse(form.features),starts_at:form.starts_at||null,ends_at:form.ends_at||null};const r=await api<Result>(editing?`/admin/cms/themes/${editing.id}`:'/admin/cms/themes',{method:editing?'PUT':'POST',body:JSON.stringify(body)});if(!r.success)throw new Error(r.message||'Save failed');setOpen(false);await load()}catch(e){setError(apiMessage(e,'Unable to save theme'))}finally{setBusy(false)}}
 async function action(id:Theme['id'],verb:'activate'|'deactivate'|'delete'){if(verb==='delete'&&!confirm('Delete this inactive theme?'))return;setBusy(true);try{await api(`/admin/cms/themes/${id}/${verb}`,{method:verb==='delete'?'DELETE':'POST'});await load()}catch(e){setError(apiMessage(e,'Theme action failed'))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Storefront Themes" description="Manage campaign themes independently from the storefront code." action={<Button className="primary" onClick={()=>edit()}>+ New theme</Button>}/>{error&&<ErrorState error={error} onRetry={load}/>} {!themes.length&&!error?<Loading/>:<Card>{themes.length?<div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Key</th><th>Type</th><th>Version</th><th>Priority</th><th>Status</th><th/></tr></thead><tbody>{themes.map(t=><tr key={String(t.id)}><td><b>{t.name}</b></td><td>{t.key}</td><td>{t.type||'—'}</td><td>{t.version||1}</td><td>{t.priority||0}</td><td><Badge>{t.is_active?'Active':t.status||'Draft'}</Badge></td><td><div className="form-actions"><Button onClick={()=>edit(t)}>Edit</Button>{t.is_active?<Button onClick={()=>action(t.id,'deactivate')}>Deactivate</Button>:<Button className="primary" onClick={()=>action(t.id,'activate')}>Activate</Button>}{!t.is_active&&<Button onClick={()=>action(t.id,'delete')}>Delete</Button>}</div></td></tr>)}</tbody></table></div>:<Empty title="No storefront themes" text="Create the first campaign theme."/>}</Card>}{open&&<Modal title={editing?'Edit theme':'New storefront theme'} onClose={()=>setOpen(false)}><div className="form-grid">{[['key','Key'],['name','Name'],['type','Type'],['status','Status']].map(([k,l])=><label key={k}>{l}<input className="wide-control" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Priority<input className="wide-control" type="number" value={form.priority} onChange={e=>setForm({...form,priority:Number(e.target.value)})}/></label>{(['tokens','assets','decorations','features'] as const).map(k=><label className="full-span" key={k}>{k}<textarea className="wide-control note" rows={5} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<div className="form-actions"><Button onClick={()=>setOpen(false)}>Cancel</Button><Button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save theme'}</Button></div></div></Modal>}</section>
}
