'use client';

import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,Check,ChevronRight,Palette,Plus,Power,RefreshCw,Save,Settings2,Trash2} from 'lucide-react';
import {api} from '@/lib/api';
import {apiMessage} from '@/lib/format';
import {Badge,Button,Card,ErrorState,Loading,Modal,PageHeader} from '@/components/ui';

type Theme={id:number|string;key:string;name:string;type?:string;status?:string;version?:number;priority?:number;is_active?:boolean;tokens?:Record<string,unknown>;assets?:Record<string,unknown>;decorations?:Record<string,unknown>;features?:Record<string,unknown>;starts_at?:string|null;ends_at?:string|null;published_at?:string|null};
type Setting={key:string;value:unknown;configured?:boolean};
const FESTIVE_PRESETS=[
 {key:'default',name:'Default',icon:'✦',description:'Always-available Priyasa storefront'},
 {key:'navratri-2026',name:'Navratri 2026',icon:'🪔',description:'Festive Navratri styling and decorations'},
 {key:'dussehra-2026',name:'Dussehra 2026',icon:'🏹',description:'Dussehra campaign presentation'},
 {key:'diwali-2026',name:'Diwali 2026',icon:'🪔',description:'Diwali lights, offers and festive accents'},
 {key:'holi-2026',name:'Holi 2026',icon:'🌈',description:'Holi campaign palette and decorations'},
 {key:'independence-day-2026',name:'Independence Day 2026',icon:'🇮🇳',description:'Independence Day campaign styling'},
 {key:'republic-day-2026',name:'Republic Day 2026',icon:'🇮🇳',description:'Republic Day campaign styling'},
];
const blank=():Theme=>({id:'new',key:`priyasa-${Date.now()}`,name:'Priyasa Store',type:'storefront',status:'draft',version:1,priority:100,is_active:false,tokens:{primary:'#FC2779',surface:'#ffffff',ink:'#111111',muted:'#6E6E6E'},assets:{},decorations:{},features:{search:true,wishlist:true,reviews:true,ratings:true,flash_sale:true,coupons:true,recommendations:true,pwa:true}});

function dateLabel(value?:string|null){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});}
function presetKey(name:string){return name.toLowerCase().replace(/\s+/g,'-');}

export default function Themes(){
 const[themes,setThemes]=useState<Theme[]>([]),[settings,setSettings]=useState<Setting[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[editing,setEditing]=useState<Theme|null>(null),[json,setJson]=useState({tokens:'{}',assets:'{}',decorations:'{}',features:'{}'});
 const themeKey=String(settings.find(s=>s.key==='storefront.theme_key')?.value||'default');
 const themeMode=String(settings.find(s=>s.key==='storefront.theme_mode')?.value||'automatic');
 const current=themes.find(t=>t.key===themeKey)||themes.find(t=>t.is_active)||themes.find(t=>t.key==='default');
 const published=useMemo(()=>themes.filter(t=>['published','active'].includes(String(t.status))&&t.is_active),[themes]);
 async function load(){setLoading(true);setError('');try{const[r,s]=await Promise.all([api<any>('/admin/cms/themes'),api<any>('/admin/settings')]);const raw=r.data;setThemes(Array.isArray(raw)?raw:Array.isArray(raw?.data)?raw.data:[]);const rows=s.data?.settings;setSettings(Array.isArray(rows)?rows:[])}catch(e){setError(apiMessage(e,'Unable to load storefront themes and controls.'))}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 function edit(t:Theme){setEditing({...t});setJson({tokens:JSON.stringify(t.tokens||{},null,2),assets:JSON.stringify(t.assets||{},null,2),decorations:JSON.stringify(t.decorations||{},null,2),features:JSON.stringify(t.features||{},null,2)})}
 function editNew(){edit(blank())}
 const update=(p:Partial<Theme>)=>setEditing(v=>v?{...v,...p}:v);
 async function save(){if(!editing)return;const parsed:any={};try{for(const k of Object.keys(json)){const v=JSON.parse((json as any)[k]);if(!v||typeof v!=='object'||Array.isArray(v))throw new Error(`${k} must be a JSON object.`);parsed[k]=v}}catch(e){setError(e instanceof Error?e.message:'Invalid theme JSON.');return}setBusy(true);setError('');try{const body={key:editing.key.trim(),name:editing.name.trim(),type:editing.type||'storefront',status:editing.status||'draft',version:Number(editing.version||1),priority:Number(editing.priority||0),is_active:Boolean(editing.is_active),tokens:parsed.tokens,assets:parsed.assets,decorations:parsed.decorations,features:parsed.features,starts_at:editing.starts_at||null,ends_at:editing.ends_at||null};const r=editing.id==='new'?await api('/admin/cms/themes',{method:'POST',body:JSON.stringify(body)}):await api(`/admin/cms/themes/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});setMessage(r.message||'Theme saved.');setEditing(null);await load()}catch(e){setError(apiMessage(e,'Unable to save theme.'))}finally{setBusy(false)}}
 async function setControl(key:string,mode:'manual'|'automatic'){setBusy(true);setError('');setMessage('');try{await api('/admin/settings',{method:'PUT',body:JSON.stringify({settings:{'storefront.theme_key':key,'storefront.theme_mode':mode}})});setMessage(mode==='automatic'?'Automatic seasonal scheduling is enabled.':`${themes.find(t=>t.key===key)?.name||key} is selected for the storefront.`);await load()}catch(e){setError(apiMessage(e,'Unable to update storefront theme control.'))}finally{setBusy(false)}}
 async function activateAndApply(t:Theme){setBusy(true);setError('');setMessage('');try{if(!t.is_active)await api(`/admin/cms/themes/${t.id}/activate`,{method:'POST'});await api('/admin/settings',{method:'PUT',body:JSON.stringify({settings:{'storefront.theme_key':t.key,'storefront.theme_mode':'manual'}})});setMessage(`${t.name} is selected as the manual storefront theme.`);await load()}catch(e){setError(apiMessage(e,'Unable to apply theme.'))}finally{setBusy(false)}}
 async function activate(t:Theme){setBusy(true);setError('');try{await api(`/admin/cms/themes/${t.id}/activate`,{method:'POST'});setMessage(`${t.name} activated.`);await load()}catch(e){setError(apiMessage(e,'Unable to activate theme.'))}finally{setBusy(false)}}
 async function deactivate(t:Theme){setBusy(true);setError('');try{await api(`/admin/cms/themes/${t.id}/deactivate`,{method:'POST'});setMessage(`${t.name} deactivated.`);await load()}catch(e){setError(apiMessage(e,'Unable to deactivate theme.'))}finally{setBusy(false)}}
 async function remove(t:Theme){if(t.is_active)return setError('Deactivate the active theme before deleting it.');if(!window.confirm(`Delete ${t.name}?`))return;setBusy(true);try{await api(`/admin/cms/themes/${t.id}`,{method:'DELETE'});setMessage('Theme deleted.');await load()}catch(e){setError(apiMessage(e,'Unable to delete theme.'))}finally{setBusy(false)}}
 return <section className="content"><PageHeader title="Storefront Themes" description="Control the live Priyasa visual system, seasonal scheduling and full theme CRUD." action={<Button className="primary" onClick={editNew}><Plus size={15}/> New theme</Button>}/>
 {message&&<div className="form-success">{message}</div>}{error&&<ErrorState error={error} onRetry={load}/>} 
 {loading?<Loading/>:<>
 <Card><div className="integration-card-head"><div><div style={{display:'flex',alignItems:'center',gap:9}}><Settings2 size={19}/><h2 style={{margin:0}}>Seasonal Theme Control</h2></div><p style={{marginTop:6}}>One control point for manual campaigns or automatic date-based festive activation.</p></div><Badge>{themeMode==='automatic'?'Automatic':'Manual'}</Badge></div>
 <div className="section-grid" style={{marginTop:18}}><div className="quick"><div><b>Mode</b><span>{themeMode==='automatic'?'Automatic scheduling':'Manual selection'}</span></div><div><b>Selected key</b><span><code>{themeKey}</code></span></div><div><b>Resolved theme</b><span>{current?.name||'Default'}</span></div></div><div className="quick"><div><b>Published + active</b><span>{published.length} themes</span></div><div><b>Current schedule</b><span>{current?.starts_at||current?.ends_at?'Scheduled':'Always eligible'}</span></div><div><b>Version</b><span>v{current?.version||1}</span></div></div></div>
 <div className="form-actions" style={{marginTop:16}}><Button onClick={()=>setControl('default','automatic')} disabled={busy||themeMode==='automatic'}><CalendarDays size={14}/> Enable automatic scheduling</Button><Button onClick={()=>load()} disabled={busy}><RefreshCw size={14}/> Refresh</Button></div></Card>
 <div style={{margin:'22px 0 10px'}}><h2 style={{marginBottom:4}}>Festive presets</h2><p style={{margin:0}}>Apply a published preset directly, or open it in the full editor below.</p></div>
 <div className="grid-cards">{FESTIVE_PRESETS.map(p=>{const t=themes.find(x=>x.key===p.key)||themes.find(x=>x.key===presetKey(p.name));const applied=themeMode==='manual'&&themeKey===p.key;return <Card key={p.key}><div className="integration-card-head"><div className="module-icon" style={{fontSize:20}}>{p.icon}</div>{applied?<Badge><Check size={13}/> Selected</Badge>:t?.is_active?<Badge>Active</Badge>:<Badge>{t?'Available':'Not seeded'}</Badge>}</div><h2>{p.name}</h2><p>{p.description}</p><p><code>{p.key}</code>{t?.starts_at||t?.ends_at?<> · {dateLabel(t.starts_at)} → {dateLabel(t.ends_at)}</>:null}</p><div className="form-actions" style={{marginTop:14}}>{t?<><Button className="primary" onClick={()=>activateAndApply(t)} disabled={busy||applied}><Check size={14}/>{applied?'Applied':'Apply'}</Button><Button onClick={()=>edit(t)}><Palette size={14}/> Edit</Button></>:<span style={{fontSize:13,opacity:.7}}>Create this preset in Theme CRUD</span>}</div></Card>})}</div>
 <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',margin:'26px 0 10px'}}><div><h2 style={{marginBottom:4}}>All themes</h2><p style={{margin:0}}>Create, publish, schedule, activate and maintain storefront themes.</p></div><span style={{fontSize:13,opacity:.7}}>{themes.length} total</span></div>
 <div className="grid-cards">{themes.map(t=><Card key={String(t.id)}><div className="integration-card-head"><div className="module-icon"><Palette size={21}/></div>{t.is_active?<Badge><Check size={13}/> Active</Badge>:<Badge>{t.status||'draft'}</Badge>}</div><h2>{t.name}</h2><p><code>{t.key}</code> · v{t.version||1} · priority {t.priority||0}</p><div className="quick"><div><b>Type</b><span>{t.type||'storefront'}</span></div><div><b>Schedule</b><span>{t.starts_at||t.ends_at?`${dateLabel(t.starts_at)} → ${dateLabel(t.ends_at)}`:'Always eligible'}</span></div><div><b>Features</b><span>{Object.keys(t.features||{}).filter(k=>Boolean((t.features||{})[k])).length} enabled</span></div></div><div className="form-actions" style={{marginTop:14}}><Button onClick={()=>edit(t)}><Palette size={14}/> Edit</Button>{t.is_active?<Button onClick={()=>deactivate(t)} disabled={busy}><Power size={14}/> Deactivate</Button>:<Button onClick={()=>activate(t)} disabled={busy}><Power size={14}/> Activate</Button>}{t.status==='published'&&<Button className="primary" onClick={()=>activateAndApply(t)} disabled={busy||themeMode==='manual'&&themeKey===t.key}><ChevronRight size={14}/> Apply</Button>}<Button onClick={()=>remove(t)} disabled={busy||Boolean(t.is_active)}><Trash2 size={14}/></Button></div></Card>)}{!themes.length&&<Card><div className="empty">No themes exist yet. Create and activate a production theme.</div></Card>}</div></>}
 {editing&&<Modal title={editing.id==='new'?'Create storefront theme':'Edit storefront theme'} onClose={()=>!busy&&setEditing(null)}><div className="section-grid"><label className="form">Key<input value={editing.key} onChange={e=>update({key:e.target.value})}/></label><label className="form">Name<input value={editing.name} onChange={e=>update({name:e.target.value})}/></label></div><div className="section-grid"><label className="form">Status<select value={editing.status||'draft'} onChange={e=>update({status:e.target.value})}><option>draft</option><option>published</option></select></label><label className="form">Priority<input type="number" value={editing.priority||0} onChange={e=>update({priority:Number(e.target.value)})}/></label></div><div className="section-grid"><label className="form">Starts at<input value={editing.starts_at||''} onChange={e=>update({starts_at:e.target.value||null})} placeholder="2026-10-01T00:00:00+05:30"/></label><label className="form">Ends at<input value={editing.ends_at||''} onChange={e=>update({ends_at:e.target.value||null})} placeholder="2026-12-31T23:59:59+05:30"/></label></div>{(['tokens','assets','decorations','features'] as const).map(k=><label className="form" key={k}>{k}<textarea value={json[k]} onChange={e=>setJson(v=>({...v,[k]:e.target.value}))} spellCheck={false} style={{minHeight:110}}/></label>)}<label className="form">Active flag<select value={editing.is_active?'active':'inactive'} onChange={e=>update({is_active:e.target.value==='active'})}><option value="inactive">Inactive</option><option value="active">Active</option></select></label><div className="form-actions"><Button onClick={()=>setEditing(null)} disabled={busy}>Cancel</Button><Button className="primary" onClick={save} disabled={busy}><Save size={14}/>{busy?'Saving…':'Save theme'}</Button></div></Modal>}
 </section>;
}
